### ISSUE TITLE
Blood: Issues with recent changes

### ISSUE THREAD

**Issue by mjr4077au** [coelckers/Raze#101]
At least under Linux, I get a crash to the shell due to an assertion fail:

```
player 1 of 1 (1 nodes)
logo.smk: Unable to open video
gti.smk: Unable to open video
movie/cs1.smk: Unable to open video
raze: /home/mrichters/Repos/Raze/source/blood/src/db.cpp:70: void Blood::InsertSpriteSect(int, int): Assertion `nSector >= 0 && nSector < 4096' failed.
Aborted (core dumped)
```

**Comment by coelckers** [comment]
I'm off to bed, can you check that the alignment packing is still active? I may have accidentally deleted it.

**Comment by mjr4077au** [comment]
I just started having a look sorry. On a the train but forgot to charge my laptop so won't be able to put much into it at the moment 😢.

I can't see anything to do with struct alignment/packing that might cause an issue (was looking for #pragma pack/pop statements).
