### ISSUE TITLE
[New base] [SW] Clear input before intermissions and cutscenes

### ISSUE THREAD

**Issue by sinisterseed** [coelckers/Raze#106]
The intention here was to easily skip them when requested without playing in full, but it's just way too easy to skip them accidentally as it currently is.

I was checking them out today and skipped them multiple times accidentally because I was still moving and the game ate my input ;(.

This is especially obnoxious on the first episode on Darkwoods of the Serpent since the boss cannot be killed the first time around, and the cutscene starts playing when its health drops to a certain level...

**Comment by markanini** [comment]
This happens to me too.

**Comment by mjr4077au** [comment]
I've been looking at this. In screenjob.cpp under `AdvanceJob()`, all input is cleared. Despite the name, the function is ran for the first job and not just when running multiple jobs one after another as this function resets the clock to 0.

Is it possible here that the screenjob comes up when you've mentally committed to doing an action like moving, firing weapon etc and its just getting caught in the first few ms of the job?

**Comment by coelckers** [comment]
I've added a 0.1 second input lockout to the screen job class. That should be enough to flush out any residual input in the system queues. Any more and it becomes a problem.
