### ISSUE TITLE
[BUG] [General] Pink screen when using Vulkan

### ISSUE THREAD

**Issue by durip** [coelckers/Raze#1086]
### Raze version

Raze 1.10.0

### Which game are you running with Raze?

Duke Nukem 3D

### What Operating System are you using?

Mac OS

### Please describe your specific OS version

Mac OS Sonoma 14.4.1

### Relevant hardware info

Apple M1 Max

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

When I set render to Vulkan and restart game whole screen is pink - see screenshot
OpenGL work OK.

![Screenshot 2024-04-22 at 20 15 27](https://github.com/ZDoom/Raze/assets/13102223/e16213c7-1a86-4ac5-b2e5-7adad2fc5790)
[raze.txt](https://github.com/ZDoom/Raze/files/15067333/raze.txt)

### Steps to reproduce the behaviour.

Explain how to reproduce
1.  Set Render to Vulkan
2. Restart game
3. Pink screen

### Provide a Log

Mac13,1 running macOS Sonoma 14.4.1 (23E224) 64-bit ARM
Vulkan device: Apple M1 Max
Vulkan device type: integrated gpu
Vulkan version: 1.2.280 (api) 0.2.2016 (driver)
Vulkan extensions: VK_KHR_16bit_storage VK_KHR_8bit_storage VK_KHR_bind_memory2 VK_KHR_buffer_device_address VK_KHR_calibrated_timestamps VK_KHR_copy_commands2 VK_KHR_create_renderpass2 VK_KHR_dedicated_allocation VK_KHR_deferred_host_operations VK_KHR_depth_stencil_resolve VK_KHR_descriptor_update_template VK_KHR_device_group VK_KHR_driver_properties VK_KHR_dynamic_rendering VK_KHR_external_fence VK_KHR_external_memory VK_KHR_external_semaphore VK_KHR_fragment_shader_barycentric VK_KHR_format_feature_flags2 VK_KHR_get_memory_requirements2 VK_KHR_imageless_framebuffer VK_KHR_image_format_list VK_KHR_incremental_present VK_KHR_maintenance1 VK_KHR_maintenance2 VK_KHR_maintenance3 VK_KHR_map_memory2 VK_KHR_multiview VK_KHR_portability_subset VK_KHR_push_descriptor VK_KHR_relaxed_block_layout VK_KHR_sampler_mirror_clamp_to_edge VK_KHR_sampler_ycbcr_conversion VK_KHR_separate_depth_stencil_layouts VK_KHR_shader_draw_parameters VK_KHR_shader_float_controls VK_KHR_shader_float16_int8 VK_KHR_shader_integer_dot_product VK_KHR_shader_non_semantic_info VK_KHR_shader_subgroup_extended_types VK_KHR_spirv_1_4 VK_KHR_storage_buffer_storage_class VK_KHR_swapchain VK_KHR_swapchain_mutable_format VK_KHR_synchronization2 VK_KHR_timeline_semaphore VK_KHR_uniform_buffer_standard_layout VK_KHR_variable_pointers VK_KHR_vertex_attribute_divisor VK_EXT_4444_formats VK_EXT_buffer_device_address VK_EXT_calibrated_timestamps VK_EXT_debug_marker VK_EXT_descriptor_indexing VK_EXT_extended_dynamic_state VK_EXT_extended_dynamic_state2 VK_EXT_extended_dynamic_state3 VK_EXT_external_memory_host VK_EXT_fragment_shader_interlock VK_EXT_hdr_metadata VK_EXT_host_query_reset VK_EXT_image_robustness VK_EXT_inline_uniform_block VK_EXT_memory_budget VK_EXT_metal_objects VK_EXT_pipeline_creation_cache_control VK_EXT_pipeline_creation_feedback VK_EXT_post_depth_coverage VK_EXT_private_data VK_EXT_robustness2 VK_EXT_sample_locations VK_EXT_scalar_block_layout VK_EXT_separate_stencil_usage VK_EXT_shader_atomic_float VK_EXT_shader_demote_to_helper_invocation VK_EXT_shader_stencil_export VK_EXT_shader_subgroup_ballot VK_EXT_shader_subgroup_vote VK_EXT_shader_viewport_index_layer VK_EXT_subgroup_size_control VK_EXT_swapchain_maintenance1 VK_EXT_texel_buffer_alignment VK_EXT_texture_compression_astc_hdr VK_EXT_vertex_attribute_divisor VK_AMD_gpu_shader_half_float VK_AMD_negative_viewport_height VK_AMD_shader_image_load_store_lod VK_AMD_shader_trinary_minmax VK_IMG_format_pvrtc VK_INTEL_shader_integer_functions2 VK_GOOGLE_display_timing VK_NV_fragment_shader_barycentric VK_NV_glsl_shader
Max. texture size: 16384
Max. uniform buffer range: -1
Min. uniform buffer offset alignment: 16
Resolution: 1920 x 1200

**Comment by alexey-lysiuk** [comment]
Is it better with Raze 1.10.2?

**Comment by billhollings** [comment]
This issue was re-posted as a [regression issue](https://github.com/KhronosGroup/MoltenVK/issues/2220) to MoltenVK.

I'm happy to see it was successfully patched here!

However, can you let me know the nature of your patch, so we can determine if something in MoltenVK really should be fixed there? Thanks.
