### ISSUE TITLE
Allow `vid_fps` to archive out to INI file?

### ISSUE THREAD

**Issue by mjr4077au** [coelckers/Raze#111]
A lot of people have autoexec.cfg files mostly to just flick this CVAR on. Is there any harm in just allowing it to write to the INI file? For a lot of other games, this is a persistent setting.

**Comment by coelckers** [comment]
Really? it's one of those things I only use occasionally and surely do not want it to persist.

**Comment by sinisterseed** [comment]
I don't use this either, but honestly this does sound like something that should persist, to avoid having to toggle it every time.

Most curious... I thought it saved.

**Comment by coelckers** [comment]
I'd end up toggling it a lot more if it persisted.

**Comment by mjr4077au** [comment]
It's not so much for me, I use a 3rd party overlay when I want an FPS counter these days. It's just something that came up on Discord and I thought I'd ask the question.

**Comment by mjr4077au** [comment]
I think with this one, we'll just leave it as it is. It's meant to be a debugging command more than anything else, I was just asking on behalf of someone on Discord.
