### ISSUE TITLE
[SW] HUD mode 7 (the one with the minimal design and the boxes around each thing) does not show armour 

### ISSUE THREAD

**Issue by Mechanical-sanity** [coelckers/Raze#112]
So I was playing through Shadow warrior level 1, and realized that the HUD does not show armour percentage

**Comment by sinisterseed** [comment]
You're referring to the partial HUD I think.

That is not a bug, but simply how it was designed. It displays the inventory items, ammo, and health percentage, but not the armor.

**Comment by coelckers** [comment]
Generally these modes are all part of the original design and therefore won't be changed.
