### ISSUE TITLE
[Blood] Caleb's voice overlaps when it should stop immediately

### ISSUE THREAD

**Issue by Kizoky** [coelckers/Raze#113]
Video: [https://cdn.discordapp.com/attachments/674506785666760706/760107567434563604/ineedakey.mp4](url)

Steps to reproduce:
1. Go to any door you don't have a key for
2. Spam the use key

You can also do it with easter eggs that force Caleb to speak

I haven't investigated if other Build games are affected

**Comment by mjr4077au** [comment]
Sorry that this one has sat for a bit but I'll try to take a look on Sunday night my time (GMT +10:00) unless someone else can beat me to it.

**Comment by sinisterseed** [comment]
This is fine in GDX.

I had some time to fiddle with things, but my endeavor proved fruitless. I'm sure it's something stupid somewhere, but I can't find it. I initially thought the values were wrong, so I changed the code for the sounds to `-1, 1, false`. No dice.

Then I noticed GDX had a `pPlayer.nPlayer` after the strings/message, but adding that makes the project fail to compile. Elusive bug...

**Comment by mjr4077au** [comment]
@coelckers can I please ask for peer review on this when you get a chance? I addressed the specific issue but not sure whether something more holistic needs to be considered.

It's probably a bit too brute force to put a check in `sndStartSample()` to stop a sound if playing before playing another?

**Comment by coelckers** [comment]
The ideal solution would be a using a dedicated sound channel for all voices that are not allowed to overlap. But I have no idea how many sounds that applies to.

**Comment by mjr4077au** [comment]
Me either, and the use of numeric constants instead of enums is pretty agonising when it comes down to determining what sound is what.
