### ISSUE TITLE
[Blood] After firing each shot of the guns akimbo for the Sawn off shotgun, there are weird sprite glitching

### ISSUE THREAD

**Issue by Mechanical-sanity** [coelckers/Raze#114]
Get a guns akimbo powerup and fire the shotguns. It always happens.

**Comment by coelckers** [comment]
Yeah, it's a badly defined animation, I was told it's a vanilla bug in the game data.

**Comment by Mechanical-sanity** [comment]
> Yeah, it's a badly defined animation, I was told it's a vanilla bug in the game data.

Do you plan on fixing it?

**Comment by coelckers** [comment]
This isn't a problem in the code but in game provided data. I cannot fix that animation data.

**Comment by Mechanical-sanity** [comment]
> This isn't a problem in the code but in game provided data. I cannot fix that animation data.

Blood GDX does not show the same behavior.

**Comment by sinisterseed** [comment]
NBlood does, though, but I seem to recall GDX doing the same. I'll have to double check on this one, maybe GDX did something to fix it.

**Comment by sinisterseed** [comment]
> NBlood does, though, but I seem to recall GDX doing the same. I'll have to double check on this one, maybe GDX did something to fix it.

Eh, the more you know.

GDX does do something different here. The Shotgun flicker can't be reproduced there, just in NBlood.

**Comment by coelckers** [comment]
Interesting, will check this out later.
