### ISSUE TITLE
Enemies Missing After Death

### ISSUE THREAD

**Issue by zaekeon** [coelckers/Raze#117]
I was testing Redneck Rampage last night and it seems when you die and restart the level that all of the enemies are gone from the level.  You can reproduce it just by starting a new game and dying immediately and when you respawn everything on the map is gone.

**Comment by mjr4077au** [comment]
If you're on 0.7.1, can I kindly suggest you please try a devbuild which are available [here](https://devbuilds.drdteam.org/raze/)? This issue should be resolved in master.

We're working on the 0.7.2 release which hopefully might be out this weekend. There's a number of things we wanted to bundle in which has taken a bit longer than anticipated.
