### ISSUE TITLE
New Menu System: Default skill is now lowest available for each game.

### ISSUE THREAD

**Issue by mjr4077au** [coelckers/Raze#118]
Not sure if this was intentional or not so just flagging it here.

**Comment by coelckers** [comment]
Surely not intentional. It looks like the default is not initialized.

**Comment by coelckers** [comment]
Fixed. Just a copy/paste error, the menu was set to the default for the episode, which is always the first one...

**Comment by mjr4077au** [comment]
Yay for one-liners! 😁.
