### ISSUE TITLE
[Duke]: Unable to quit game on current master.

### ISSUE THREAD

**Issue by mjr4077au** [coelckers/Raze#121]
Comes to the below screen after pressing Y to quit. Unable to backtrace until tonight but it's not in the release.

![image](https://user-images.githubusercontent.com/48643140/95690944-15182200-0c67-11eb-90f6-8f141b6b372c.png)

**Comment by coelckers** [comment]
That looks like the shareware quit screen. Apparently the menu blocks it. Should also be looked into before fixing the blocking menu.

**Comment by mjr4077au** [comment]
Working like a champion now 😁.
