### ISSUE TITLE
Menu misalignments

### ISSUE THREAD

**Issue by coelckers** [coelckers/Raze#122]
The spinning selectors in Duke are slightly shifted to the right, overlapping with "Alien World Order" on the left side. They should also adjust to wider texts,

In RR the caption is not properly stretched.

**Comment by sinisterseed** [comment]
Wasn't this always there though, at least to an extent?

I noticed this before but I thought it is what it is.

**Comment by coelckers** [comment]
No, this comes from the menu replacement.

**Comment by sinisterseed** [comment]
Very well.

Then I think SW can do with a minor adjustment too, by shifting the text a pixel or two to the right, so it doesn't touch that grey bar on the left.

![gfgfgfgfgf](https://user-images.githubusercontent.com/57503728/95758096-a8c21080-0cb0-11eb-8f65-338f498cf279.png)

**Comment by coelckers** [comment]
fixed
