### ISSUE TITLE
[g86ad57667] [General] Restarting after death when saves are present breaks the games

### ISSUE THREAD

**Issue by sinisterseed** [coelckers/Raze#124]
The player ends up in some sort of broken state looking up when this happens, stuck in place, with the timer still going, and the teleport effect plus gibblets start flying around when they spam Use.

To reproduce: Start a game, warp to a map, die, press Use and let the game auto reload.

Now the game is broken. It fixes itself after reloading a save, restarting the game, or warping to another map.

**Comment by sinisterseed** [comment]
Related to this actually, and it isn't game specific either: https://forum.zdoom.org/viewtopic.php?f=340&t=70195

**Comment by coelckers** [comment]
fixed. It was a missed piece of code I had to temporatily disable when working on the menus.
