### ISSUE TITLE
[Since forever?] [Exhumed] Permadeath screen does not render correctly

### ISSUE THREAD

**Issue by sinisterseed** [coelckers/Raze#126]
I've only recently become aware of the existence of such a screen.

And it does not render correctly at all, palette or not. To trigger it, simply die for good. When you do, this shows up, but displays incorrectly:

![gfgfgfgf](https://user-images.githubusercontent.com/57503728/95762740-ceeaaf00-0cb6-11eb-8deb-e31b52fd6732.png)

According to GDX this is not meant to bring up any sound effects either - currently, for us, it plays the laughter that can be heard in the intro or the pharaoh, which it should not. 

Likewise, it also plays the rest of the intro videos all over again, which it supposedly shouldn't. After that screen shows up, the player needs to skip it manually and they're simply returned to the main menu.

**Comment by coelckers** [comment]
fixed
