### ISSUE TITLE
RRRA: Motorcycle and boat control broken.

### ISSUE THREAD

**Issue by coelckers** [coelckers/Raze#128]
When starting to drive the view pitches fully upward and won't recenter again.

I'm also not sure what to think about mouse sensitivity for vehicle control. It's far too responsive for something fast moving.
Raze 0.6 is unfortunately not useful for comparison here because the mouse barely turns the vehivcles. In any case, I think the maximum response should be capped a bit.

**Comment by mjr4077au** [comment]
I'll take a further look at this tonight but thought I tested all of this. Must have been a regression with the change to the fixedhoriz class somewhere...

The mouse sensitivity is strange with the vehicles as its not scaling right depending on the framerate. If you turn off vsync, does it slow down for you? I notice a massive difference between cl_syncinput 1 and cl_syncinput 0 at 144Hz.
