### ISSUE TITLE
[Duke]: General sprite weirdness until within a certain proximity.

### ISSUE THREAD

**Issue by mjr4077au** [coelckers/Raze#129]
Hard to demonstate as the capture software really dropped the frame-rate, but the shotgun and the atomic health pickup has a sort of interpolation jitter until close enough.

The atomic health pickup appears to sit too high and drops down once within a certain range as well.

https://youtu.be/mGw5vyBW6bQ

**Comment by coelckers** [comment]
Welcome to the wonderful world of Duke. You can notice something similar but far more easily noticable on the medkit in the ticket booth you can blow open with the RPG.

Duke works very strangely. Many actors are idle if no player can see them, they only start interacting with the world if they are seen - and that unfortunately also includes the effects of gravity.
Why? Most likely because calling the CON scripts on them every frame was too expensive in 1996.

**Comment by mjr4077au** [comment]
I was about to comment "but this doesn't happen in EDuke32 IIRC", but then I checked and it did... 😛. They don't have the interpolation jitters we have but I believe a better interpolation solution will come at some point in the future.

**Comment by coelckers** [comment]
That effect was always there in Raze, in both old frontends. So I checked what stupid thing the code was doing and it wasn't something smart. :imp:

**Comment by sinisterseed** [comment]
The jitter is something I never noticed, but it's so subtle I probably don't have such a good eye for some details 😉.

Them falling down or whatever when making visual contact is just typical CON though. There are plenty of occasions in the game where this can be noticed, but easiest on E1L5 IMO. When you blow up that secret wall near the cave secret with the dancing naked lady around the fire, you will see medkits and other items falling from the sky as you climb up the mountain.

Duke Nukem™.

**Comment by mjr4077au** [comment]
I think it's more the 144Hz display vs an eye being better than another, it definitely helps for a lot of things 😄.

I know the game is rough so its all good, was more an exploratory "can anything be done here" question 😉.

**Comment by mjr4077au** [comment]
Regarding the interpolation jitters I mentioned, I isolated them back to 7043092fd07da6935abe9ebd371dc032c5ff243e. 

It's hard to capture on video but blowing out the vent at the start of E1L1 and the street sign down near the dumpster fire in E1L1 showed very apparent issues. All sprites also jitter on the spot until they're within view of the player.

https://youtu.be/hTVYCm7eN7k
https://youtu.be/6CSkXrtlQPo

Hopefully everything else should be all good 😁.
