### ISSUE TITLE
[Blood] Auto detector detects Blood Cryptic Passage twice

### ISSUE THREAD

**Issue by Mechanical-sanity** [coelckers/Raze#130]
If you put all the cryptic passage stuff in blood, the autoloader will show you the option for it twice

**Comment by mjr4077au** [comment]
Can you please advise specifically where you have Blood and Cryptic Passage on your disk in relation to Raze? Below is with Blood: Fresh Supply from Steam just via registry detection.

![image](https://user-images.githubusercontent.com/48643140/96209388-36f10c00-0fbb-11eb-9ede-610e5703b4ca.png)

**Comment by sinisterseed** [comment]
Indeed, do you put the game files in the port's directory in it in addition to letting it scan the registry?

If so, that's normal.

**Comment by Mechanical-sanity** [comment]
> Can you please advise specifically where you have Blood and Cryptic Passage on your disk in relation to Raze? Below is with Blood: Fresh Supply from Steam just via registry detection.
> 
> ![image](https://user-images.githubusercontent.com/48643140/96209388-36f10c00-0fbb-11eb-9ede-610e5703b4ca.png)

I only have one copy of blood within the Raze folder. It just shows Cryptic passage twice, despite me not having more than one copy. I placed the blood folder directly into the Raze folder. I only put in the files required

**Comment by coelckers** [comment]
It clearly picks up two versions of it. Can you make a screenshot of your game picker?

**Comment by sinisterseed** [comment]
> do you put the game files in the port's directory in it **in addition to letting it scan the registry?**

**Comment by Mechanical-sanity** [comment]
> It clearly picks up two versions of it. Can you make a screenshot of your game picker?

But the thing is, if I delete the file or move it out, it doesn't detect anything. I've even tested it by removing the cryptic passage files from the folder. It detected blood and only blood. No cryptic passage. Anyways, here's a screenshot: 
![Untitled](https://user-images.githubusercontent.com/40319751/96267101-6c82fe80-0f95-11eb-872f-bd4405144406.png)

**Comment by sinisterseed** [comment]
If that is so, and it picks up CP twice, that's normally an indication that you probably have some duplicate files, but without a list of all your files, it'll be just a guessing game.

**Comment by Mechanical-sanity** [comment]
I can tell you for sure that there is not a duplicate file set

**Comment by sinisterseed** [comment]
Does it make a difference if you just zip up CP's files and place it in Raze's root directory, without it extracted into Blood too?

I tried to reproduce this but I'm not having any luck, so I can only assume the game detector finds some duplicate files somewhere. A screenshot of your Blood or Raze folder would be helpful.

You can also fire up both CP addons that Raze detects, then quit the game. At startup, the generated .log file should tell you what lumps it added and their location.

**Comment by coelckers** [comment]
> You can also fire up both CP addons that Raze detects, then quit the game. At startup, Raze generates a .log file which should tell you what lumps/files it adds along with their respective location, and see whether the loaded files differ in any way for both cases.

I just wanted to suggest the same thing. Just check where the data comes from. But keep in mind that due to the messy way these files are provided the options are limited. I'd rather detect it twice than not at all.
RR's Route66 has the same problems, btw., going as far that the GOG version of the game accidentally overrides a sound from the core game with its R66 replacement.

**Comment by Mechanical-sanity** [comment]
> Does it make a difference if you just zip up CP's files and place it inside Raze's root directory, without it extracted into Blood's too?
> 
> I tried to reproduce this but I'm not having any luck, so I can only assume the game detector finds some duplicate files somewhere. A screenshot of your Blood or Raze folder would be helpful.
> 
> You can also fire up both CP addons that Raze detects, then quit the game. At startup, Raze generates a .log file which should tell you what lumps/files it adds along with their respective location, and see whether the loaded files differ in any way for both cases.

The logs show that they load from the exact same folder, so I dont think a screenshot would help

**Comment by coelckers** [comment]
How do your search path sections in the INI look? It must be picking up this thing through two different settings then.

**Comment by Mechanical-sanity** [comment]
I just keep the .ini files as is. To check, I removed the original .ini file and allowed the engine to create a new one. It didnt work

**Comment by sinisterseed** [comment]
You are dodging the original question, though.

What Graf was asking was how does the beginning of you .ini look like, specifically this part where the paths are checked:

> # This file was generated by Raze 0.7.1_alpha-272-ga9ad043c3
> # These are the directories to automatically search for game data.
> # Each directory should be on a separate line, preceded by Path=
> [GameSearch.Directories]
> Path=.
> Path=./*
> Path=$PROGDIR
> Path=$PROGDIR/*
> Path=$STEAM
> 
> # These are the directories to search for add-ons added with the -file
> # command line parameter, if they cannot be found with the path
> # as-is. Layout is the same as for GameSearch.Directories
> [FileSearch.Directories]
> Path=$PROGDIR
> Path=$GAMEDIR
> 
> # These are the directories to search for soundfonts that let listed in the menu.
> # Layout is the same as for GameSearch.Directories
> [SoundfontSearch.Directories]
> Path=$PROGDIR/soundfonts

**Comment by mjr4077au** [comment]
Had a play with this and can confirm. Basically copied my entire "One Unit Whole Blood" directory into Raze as Blood and received the following:

![image](https://user-images.githubusercontent.com/48643140/96385849-400ff200-11e2-11eb-824a-ee8d92328ef4.png)

I've come to have it listed three times, with all copies working and all copies being sourced from the "Blood" directory under Raze's root.

I'll see what can be done here about the detection but will err on the side of caution because as Graf said, having it show up more than once is better than not at all.

**Comment by sinisterseed** [comment]
So it gets picked up if the whole folder is tossed in? Fascinating.

I wonder what messed with it then, if it gets picked up just fine via registry scan, but gets listed twice when it's placed in Raze's directory.

**Comment by mjr4077au** [comment]
I ran out of time unfortunately on the train into work this morning. Will have a further look tonight or tomorrow. It's probably something in the grpinfo.txt file that needs amending.
