### ISSUE TITLE
[ga9ad043c3] [Duke] View pitch gets reset after reloading a save

### ISSUE THREAD

**Issue by sinisterseed** [coelckers/Raze#131]
To reproduce, simply look up/down, make a save, and reload.

After that, the view gets automatically re-centered instead of being restored to what it was.

**Comment by coelckers** [comment]
The pitch is properly saved but gets reset right away. Looks like some input thing isn't properly preserved.

**Comment by mjr4077au** [comment]
With the saving, you helped me with this for Duke. The only thing I can think of is this line setting the bit which was an attempt to preserve the bit if it was set and not unconditionally apply it. https://github.com/coelckers/Raze/blob/94e8213caf90dd18861646bf50fb3adc0c5a879a/source/games/duke/src/savegame.cpp#L291

**Comment by mjr4077au** [comment]
I'm still isolating the cause here. Ignore the above comment, the resetting appears to be coming from elsewhere as the horizon re-centers faster than the algorithm in `sethorizon()`.
