### ISSUE TITLE
[ga9ad043c3] [SW] RC cars and vehicles are silent

### ISSUE THREAD

**Issue by sinisterseed** [coelckers/Raze#132]
Seems RC cars have gone silent.

[silentrccars.zip](https://github.com/coelckers/Raze/files/5396267/silentrccars.zip)

**Comment by sinisterseed** [comment]
Actually more than that. The vehicles and the turret on Zilla Construction are also silent.

**Comment by coelckers** [comment]
Sector objects again. They sure screwed them up badly that they constantly break when looking at them strangely...

**Comment by sinisterseed** [comment]
I just wonder what broke them this time, a couple of days ago they were still fine.

**Comment by mjr4077au** [comment]
I'll be able to do some bisecting tonight if the European team is about to clock off. Can't get onto it now as I have a baptism to go to this morning ☺️

**Comment by mjr4077au** [comment]
This one wasn't too bad in the end and was a two liner to get resolved. Very nice that this was chunked into smaller commits to make it easier to isolate 😁.
