### ISSUE TITLE
[SW, Perhaps Others]: Quicksave menu (F6) brings up actual save menu (F2).

### ISSUE THREAD

**Issue by mjr4077au** [coelckers/Raze#133]
Raising on behalf of 'Zaratul' from Discord who kindly made the report. Have corroborated but not in a position to investigate further at the moment.

**Comment by coelckers** [comment]
It does, unless you save once and define a quicksave slot. I've been thinking anyway to default this to the rotating quicksave feature which IMO is magnitudes better than this 90's nonsense.
I do not know, though, how the Build games handled quicksaving originally.
