### ISSUE TITLE
[Duke WT] Strange performance issues in WT levels.

### ISSUE THREAD

**Issue by mjr4077au** [coelckers/Raze#135]
This was reported on Discord and I've been able to corroborate. Below are screenshots from WT on my Core i7 4770k and NVIDIA GTX 970 with no frame-rate cap and vsync disabled.

Output of `stat fps` in bottom left corner, with FPS in top left.

Bad perf:
![Duke_0007](https://user-images.githubusercontent.com/48643140/96572779-fd046a80-1318-11eb-8eae-fe29d8684b54.png)

Good perf (just turned to look behind me):
![Duke_0008](https://user-images.githubusercontent.com/48643140/96572799-04c40f00-1319-11eb-9805-439cbc31b3b7.png)

There's something that's taking a lot of time to draw, I wouldn't expect such an FPS hit and draw time on my system.

**Comment by mjr4077au** [comment]
This is under Linux, so it's a cross-platform issue.

![Duke_0009](https://user-images.githubusercontent.com/48643140/96574804-a77d8d00-131b-11eb-99dc-83836b3d525d.png)

![Duke_0008](https://user-images.githubusercontent.com/48643140/96574834-af3d3180-131b-11eb-8b1a-ce523d8b508b.png)

**Comment by sinisterseed** [comment]
Honestly I think this is just how WT runs in general.

It runs pretty much the same for me in GDX, so perhaps it just isnt well optimized, which wouldnt be surprising considering the renderer they were originally designed for.

**Comment by coelckers** [comment]
The WT levels are considerably larger than the stock ones and we all know that Polymost is slow. Is this a debug or release build?

**Comment by sinisterseed** [comment]
Release me thinks, second screenshot shows over 400fps, can Debug builds be this fast?

**Comment by coelckers** [comment]
Sure  with a scene that only shows a handful of walls that can be.

**Comment by coelckers** [comment]
What do you get in these locations? I can't test for the next 4 hours.

**Comment by sinisterseed** [comment]
With a Release build I actually get more frames when uncapped than MJ does lol. With 4x MSAA:

![Duke_0001](https://user-images.githubusercontent.com/57503728/96585841-cc0c4180-12e8-11eb-86b0-ca95c1bef32b.png)

![Duke_0000](https://user-images.githubusercontent.com/57503728/96585838-cadb1480-12e8-11eb-86c2-d3b7dcd7f912.png)

**Comment by coelckers** [comment]
But you see the same frame rate drop, that's what I wanted to know.

**Comment by sinisterseed** [comment]
Of course.

**Comment by coelckers** [comment]
My frame rate is even higher - 170 vs 800 in those two places, but it's clearly the same effect. Currently there's no good stats of how many elements get rendered but this clearly points at scene complexity as the cause.

**Comment by sinisterseed** [comment]
It'a bit surprising insofar as there aren't many objects in view either, it's as if staring at the entire map by just sitting there looking that way, which is also where the map continues I think.

**Comment by mjr4077au** [comment]
What about with the stats counter down the bottom. 4ms to 5ms to actually to the drawing is around 16x higher than any other level in any of the other games from my own experience. I was just wondering if there was some kind of render stall with the WT code path. I'm yet to do any real profiling though.

**Comment by mjr4077au** [comment]
The OP came back to me on Discord and says he gets similar on EDuke32 so it's probably just a genuine stall with the renderer. Shall we just close it down for now?

**Comment by sinisterseed** [comment]
I suppose we could do some investigation honestly, perhaps we can determine where all the frames are getting lost.

And if not, a story for another time or when we get to the new render 😉.

**Comment by coelckers** [comment]
Yes. The Build engine is actually very sensitive toward a few mapping issues. Do something slightly 'wrong' and it will get slow. 
One thing that can really bring it down is sectors with more than a handful of lines. I'll have to do a little tweak to the automap drawer to render all lines, even those normally hidden to see what is up with that.

**Comment by mjr4077au** [comment]
Thanks for looking all the same and appreciate the insight as always 😁

**Comment by sinisterseed** [comment]
Nice, I'm curious what we discover there 👌.
