### ISSUE TITLE
Exhumed raze-x64-0.7.1_alpha-293 - Invincibility item not working.

### ISSUE THREAD

**Issue by Axldomi** [coelckers/Raze#137]
The "invincibility" item is not working in Exhumed under Raze. 

You can activate it, but it won't make you invincible. Rather important bug as it makes some sections of the game unbeatable. 

PCExhumed doesn't have this issue.

**Comment by sinisterseed** [comment]
Confirmed.

Nasty one, since it's required on some maps, LEV5 has a section that comes to mind right now. Well, at least the other items are fine.

**Comment by coelckers** [comment]
Any place I can find and test the item?

**Comment by sinisterseed** [comment]
> Any place I can find and test the item?

That will not be necessary. Just give yourself the inventory and warp to an early map with lava nearby, such as LEV4 or 5, use the Scarab, and jump into it. Or let the enemies eat you since it doesn't stop that either.

**Comment by Axldomi** [comment]
You can easily test it by using cheats to get all items (type "loboswag" during game or "give all" in console). And then select the item in the inventory. See screenshot (item next to the health bar).
![Exhumed_0000](https://user-images.githubusercontent.com/71838912/96833273-6fbc3580-1440-11eb-8879-a0090c868af9.png)
