### ISSUE TITLE
DN3D - raze-x64-0.7.1_alpha-293 - Activate god mode after death

### ISSUE THREAD

**Issue by Axldomi** [coelckers/Raze#138]
In the original Duke Nukem 3D, you could use the god code to revive yourself **after death** (by typing DNKROZ).

In Raze you can do the same, but the camera/viewpoint isn't corrected. See screenshot attached.
![Duke_0001](https://user-images.githubusercontent.com/71838912/96753406-216f4e00-13d0-11eb-8e7e-704abb1590b9.png)

**Comment by sinisterseed** [comment]
Also true.

It seems the perspective doesn't get reset at all after using that cheat, it simply preserves the view the way it was upon death.
