### ISSUE TITLE
Blood - raze-x64-0.7.1_alpha-293 - E3M4 Morgue sprites

### ISSUE THREAD

**Issue by Axldomi** [coelckers/Raze#140]
In E3M4 "The Sick Ward", in the morgue section, the sprites that will explode upon entering are highlited in Raze. 

NBlood on the other hand, displays them correctly. See comparison below. Screenshot 1 RAZE - Screenshot 2 NBlood.

![Raze](https://user-images.githubusercontent.com/71838912/96848070-3d1c3800-1454-11eb-85cc-2fb9e9ba8da6.png)

![NBlood](https://user-images.githubusercontent.com/71838912/96848086-43121900-1454-11eb-8621-be79a3aa245d.png)

**Comment by sinisterseed** [comment]
Hm, this one is quite curious.

If my eyes don't deceive me, the dead human sprites are also darker than they should be.

**Comment by Axldomi** [comment]
> If my eyes don't deceive me, the dead human sprites are also darker than they should be.

Yes, but I suppose this could be due to personal brightness settings.

**Comment by sinisterseed** [comment]
Looking at the environment in the two screenshots seems to prove the contrary though, the brightness levels appear to be the same, which makes me pretty confident that this is a bug and not a difference created by different settings.
