### ISSUE TITLE
[Exhumed]: Reload after death state not clearing right.

### ISSUE THREAD

**Issue by mjr4077au** [coelckers/Raze#141]
While testing #137, I died and respawned. In addition to having items, I can also see my dead corpse from before.

![Exhumed_0000](https://user-images.githubusercontent.com/48643140/96852044-6795e180-14a4-11eb-9ead-aea53b61a281.png)

**Comment by coelckers** [comment]
Exhumed does not reset the game state if you can resume with another life. Only after losing all lives you get sent back to the menu. This is different from traditional 3D shooters.

**Comment by mjr4077au** [comment]
Ah right, sorry my mistake! 😁
