### ISSUE TITLE
[BLOOD] Ease of Use for Mod Loading

### ISSUE THREAD

**Issue by Doruk-Aksoy** [coelckers/Raze#142]
You should most definitely consider the option of including a "Load Addon" or something of that sorts that other popular Blood ports come with that allow you to simply load an .ini file on the fly and run with it. That'd make it far easier to run mods with.

**Comment by boggydigital** [comment]
I had luck using "-ini filename.ini" in the "Additional parameters" field. It's quirky a bit in my experience - at least on macOS you do that, Raze re-launches, you delete "Additional parameters" and then it starts with that add-on (Death Wish in my example). 🤷‍♂️

**Comment by coelckers** [comment]
It has been GZDoom's philosophy to leave mod loading to dedicated launchers and I'd prefer to use the same approach here.
The main problem here simply is that we got 3 platform dependent GUI dialogues for these things plus a pure terminal fallback for Linux. As a result these were always kept to the required minimum to properly start the game.

I do not know if someone tried to use a simple Doom launcher like ZDL with Raze - but just for that use case I added a '-iwad' parameter that's a synonym for '-gamegrp'. The biggest issue with Build engine mods is that many of them require additional parameters to actually start the game. This was simpler in Doom where the presence of the data is normally enough.

**Comment by boggydigital** [comment]
Hey @coelckers, any chance you can weight in on my comment above? That sounds like a bug and I'm happy to file a separate report, want to make this is not supposed to be this way.

Prereqs - have Blood files ready (I'm using GOG.com One Unit Whole Blood files, not Fresh Supply IIRC), as well as Death Wish files (with Music add-on) extracted to that folder. Have that Blood folder somewhere where Raze would find (in my case I added a folder as Path=... in ~/Library/Preferences/raze.ini on macOS)

Here is how it works:

- I start Raze - Additional Parameters is already pre-filled with "-ini dw.ini" from previous runs
- Select BLOOD (BLOOD: One Unit Whole Blood) from the list and click "OK"
- (dialog flashes and appears again)
- Now clear Additional Parameters, select BLOOD and press OK again
- The game starts and New Game shows Death Wish episodes

If I clear Additional Parameters in the first dialog the game starts and New Game shows Blood episodes.
If I don't clear Additional Parameters, select BLOOD and click OK - dialog would flash as many times as I would click OK, so I have to clear it at some point to proceed.

**Comment by mjr4077au** [comment]
@boggydigital any chance you could please share a screenshot of what the launcher looks like on macOS? I've never seen it and didn't realise it had an "Additional Parameters" field.

Having a field like that on the Windows and SDL launcher could be beneficial, at the very least would bring the launchers up to feature parity.

@coelckers thoughts on having the launcher for all games done in some kind of cross-platform toolkit like Qt or GTK? It'd ensure consistency amoung operating systems and should simplify things a bit, at the expense of increased dependencies.

**Comment by boggydigital** [comment]
Would be happy to help - attached is a Raze launcher screenshot, along with GZDoom screenshot that looks pretty much the same - and that's where I got used to that field, I wasn't aware it's not available on other OSes...

<img width="977" alt="raze" src="https://user-images.githubusercontent.com/69746/103503411-fc07b300-4e08-11eb-8aba-46a3ef40efd3.png">
<img width="979" alt="gzdoom" src="https://user-images.githubusercontent.com/69746/103503409-fa3def80-4e08-11eb-9e35-3bdc749c9345.png">

**Comment by mjr4077au** [comment]
Thanks bruv 😁. It actually looks like the SDL launcher, just with the addition of that text field.

I'll wait for Graf to chime in as to whether we should have this on the other launchers as well. I'm personally for it. Someone can go "hey how do I run X?", and someone can go "paste this into there and off you go".

**Comment by coelckers** [comment]
Some improvements with fc314b6616e14b83a40e8dca9cbe94caa2e4f08c
It will now autodetect .inis in loaded files and also load .zips where all content is in a subdirectory, like with Death Wish.
This should allow using drag & drop with most mod distributions for Blood without having to unpack them.
