### ISSUE TITLE
[Redneck Rampage] Vehicles cannot be controlled when using a joystick

### ISSUE THREAD

**Issue by duke912** [coelckers/Raze#150]
Playing with an xbox one controller, when you get to a vehicle (bike, boat, etc) only steering with the right analog works, left analog does nothing (you can't go forward/backward).

**Comment by mjr4077au** [comment]
This is more of a feature request since the code for this doesn't exist in the first place.

Making it work in the sense that the analog stick actually does something is easy enough, but making it work properly (varied speed depending on how much you actuate the analog stick) is a lot harder.

Leave it with me 😄.

**Comment by mjr4077au** [comment]
@duke912 can you please download the CI artifact from the top right of [here](https://github.com/coelckers/Raze/runs/1355788118) and test? I won't have access to a controller until the weekend so its completely untested.

There's probably some refinement to do as the keyboard input feels slightly off now but it's very difficult to do this on the train from a laptop, hence why its in a branch for now.

Any feedback good, bad, or otherwise is welcome 👍

**Comment by duke912** [comment]
> @duke912 can you please download the CI artifact from the top right of [here](https://github.com/coelckers/Raze/runs/1355788118) and test? I won't have access to a controller until the weekend so its completely untested.
> 
> There's probably some refinement to do as the keyboard input feels slightly off now but it's very difficult to do this on the train from a laptop, hence why its in a branch for now. A problem I can forsee for now is that if you set the sensitivity beyond 1 in the menu, you'd likely have a very, very fast vehicle so I should cap it at 1.0 when on a vehicle.
> 
> Any feedback good, bad, or otherwise is welcome 👍

I just tested the artifact, and even though it works, it's inverted for some reason (forward moves backward and vice-versa), also, you may want to check the right analog steering, I just compared it to WASD and mouse, and it turns the vehicle so slow it almost impossible to keep the bike on track in the second level of the first episode in Rides Again, same thing on boat. Nice work by the way.

**Comment by mjr4077au** [comment]
That's my bad on the inversion, I can easily fix that and will do soon for you.

Does boosting the sensitivity help with the right stick or does it stay the same?

**Comment by duke912** [comment]
> That's my bad on the inversion, I can easily fix that and will do soon for you.
> 
> Does boosting the sensitivity help with the right stick or does it stay the same?

It stays the same, tested with max and lowest sensitivity.

**Comment by mjr4077au** [comment]
Thanks, thought so which is why I asked. I might leave it until tonight so I can do some proper testing myself. Only another 12 hours until I'll be home 😁

**Comment by mjr4077au** [comment]
@duke912 can you please give the artifact from here a go? https://github.com/coelckers/Raze/runs/1362123723

* Forward/reverse polarity issues fixed.
* Almost completely redone vehicle input for mouse and controllers.
* Ensured forward/reverse sensitivity can't increase the acceleration of the bike beyond what a keyboard can achieve.

**Comment by duke912** [comment]
> @duke912 can you please give the artifact from here a go? https://github.com/coelckers/Raze/runs/1362210736
> 
> * Forward/reverse polarity issues fixed.
> * Almost completely redone vehicle input for mouse and controllers.
> * Ensured forward/reverse sensitivity can't increase the acceleration of the bike beyond what a keyboard can achieve.
> 
> EDIT: Updated link, found an issue affecting the boat.

Tested it and it works perfectly fine, on bike and boat.

**Comment by sinisterseed** [comment]
And better than ever too, I'd say 😉 .

**Comment by mjr4077au** [comment]
Merged the work branch into master. Thank you very kindly to everyone who tested this 😄.
