### ISSUE TITLE
[General] Add Toggle Crouch bind option to Blood and Shadow Warrior

### ISSUE THREAD

**Issue by duke912** [coelckers/Raze#151]
By now, Toggle Crouch only works in Duke and Redneck, I tried to use the bind command to add toggle crouch to a button in Blood, but it doesn't work.

**Comment by coelckers** [comment]
That action does not exist in Blood. In Shadow Warrior it should work. 
Keep in mind that these games are totally separate modules, not all features exist in all games.

**Comment by duke912** [comment]
> That action does not exist in Blood. In Shadow Warrior it should work.
> Keep in mind that these games are totally separate modules, not all features exist in all games.

Yep, just tested in shadow warrior and it works fine. So, it's not possible to add in Blood?

**Comment by coelckers** [comment]
It may be possible but the game currently simply has no handling for that action so it requires a bit of work.

**Comment by mjr4077au** [comment]
I'll take this one onboard.
