### ISSUE TITLE
Exhumed - 0.7.3 - Level 20 Alien Ship Crash

### ISSUE THREAD

**Issue by Axldomi** [coelckers/Raze#152]
Played through the whole game using Raze 0.7.3 and never experienced a crash. However level 20 crashes as soon as I shoot the very first control panel.

**Comment by sinisterseed** [comment]
Most... peculiar.

For me it doesn't crash but... freezes somehow in place in this frame after I shoot the first panel. The sound is still going on, and I can look around, but not move or do anything else.

![Exhumed_0000](https://user-images.githubusercontent.com/57503728/98018830-afecc200-1e09-11eb-82ec-cb3887328f96.png)

**Comment by Axldomi** [comment]
I'm sorry, that's what I actually meant by "crash". I get the exact same issue : the screen freezes somehow... and I can't move anymore. I'll try to be more precise next time.

**Comment by sinisterseed** [comment]
Then it's more akin to freezing or hanging, although in this situation that's not entirely accurate either.

**Comment by coelckers** [comment]
Any savegame for quick testing?

**Comment by Axldomi** [comment]
Here you go.

[save0000.zip](https://github.com/coelckers/Raze/files/5483708/save0000.zip)

**Comment by sinisterseed** [comment]
> Any savegame for quick testing?

Wouldn't have been necessary honestly. Simply warping to the map and throwing a "give weapons" is just enough.
