### ISSUE TITLE
[Duke/RR]: E1L2 - Toxic psychedelic cactus has no effect

### ISSUE THREAD

**Issue by mjr4077au** [coelckers/Raze#154]
At the start of the level, there's a cactus on the left after the two old coots you encounter. Running over the cactus is meant to change the screen's tint and FOV but it currently has no effect.

Haven't bisected the issue yet, just reporting for now.

**Comment by coelckers** [comment]
The cactus is working. All I noticed is that the distorted view seems to reset periodically for one frame.
Keep in mind: Only an orange cactua gives you strange colors.

**Comment by coelckers** [comment]
The view problem is something deeply buried in Polymost's projection code. For some value pairs in renderSetAspect it will not create a proper projection but this code is far too obtuse to be understood. :sob:

**Comment by mjr4077au** [comment]
No worries, I know how it is with these games. It is working in RedNukem if it can be of any reference.

**Comment by coelckers** [comment]
I can only tell you that the effect is working on all the cactuses I tested, except for the problem with the projection which seems to have a problem at one point.

**Comment by coelckers** [comment]
Looks like the projection hiccup is fixed after reordering the code for later addition of frame rate control.

**Comment by coelckers** [comment]
Is fixed now. The missing bit of info here was that this bug only occured when riding a vehicle. When walking into the cactus everything was correct.
