### ISSUE TITLE
RR psychedelic cactus effect is frame rate dependent

### ISSUE THREAD

**Issue by coelckers** [coelckers/Raze#155]
Code contains no synchronization whatsoever.

**Comment by sinisterseed** [comment]
Well that's new.

WoI never expected somethjng framerate dependent to exist in these games, just like Doom. At which point does it break exactly?

**Comment by mjr4077au** [comment]
I still get the same issue that I reported initially regardless of whether `cl_syncinput` is true or false. Just to clarify we're talking about the same thing, grabbed some recordings:

Us with synchronised input: https://youtu.be/bBUEY0SGuMQ
RedNukem (only has synchronised input): https://youtu.be/IwcTDft06RM

**Comment by coelckers** [comment]
I never tried smashing the cactus with the bike. You never mentioned that important piece of info.

**Comment by mjr4077au** [comment]
> I never tried smashing the cactus with the bike. You never mentioned that important piece of info.

I did though, but perhaps could have been clearer. When I said "Running over the cactus", I meant on the vehicle like when you run over something in your car. I actually haven't tried walking over it on foot.

**Comment by coelckers** [comment]
In GDX the cactus does not start drug mode when smashed with the bike. It just gets blown into pieces.
Of course it's very hard to test because the vehicle controls are nearly unplayable. I tried it twice to no avail.

**Comment by coelckers** [comment]
Ok, found it. GDX had it wrong - the problem was caused by some very messy #if/#else conditionals in the RR reconstruction source which were easy to misinterpret.

**Comment by mjr4077au** [comment]
I haven't tried GDX but will later on. Are you saying the controls in GDX/RedNukem are bad, or ours are? Happy to make improvements of course. I normally just use WASD for vehicles. The mouse could probably use some work and the mouse input has a degree of variance between synchronised and unsynchronised input.

**Comment by mjr4077au** [comment]
> Ok, found it. GDX had it wrong - the problem was caused by some very messy #if/#else conditionals in the RR reconstruction source which were easy to misinterpret.

Nice one, glad we got there in the end. Sorry for the loose report, will be more specific and include an example moving forward 👍🤘

**Comment by mjr4077au** [comment]
Marking this one as closed. Graf fixed the issue and the remaining issues about the scaling being a bit hitchy at the start and end of drug mode have been resolved in c823e33bb3e9099d23e773482385a692023b6d10.
