### ISSUE TITLE
[RRRA]: E1L2 crash when trying to open gate without key

### ISSUE THREAD

**Issue by mjr4077au** [coelckers/Raze#157]
[save0000.zip](https://github.com/coelckers/Raze/files/5503953/save0000.zip)

If you press Use here to open the gate, Raze will hard crash. If you give yourself the keys via cheats, the gate opens fine. Perhaps some more uninitialised data?

**Comment by mjr4077au** [comment]
Backtraced to 36370b71e23023e36076345d9bd8e62fb15a865d but the problem isn't overly apparent to me. When I looked saw things that looked like possible fixes, they'd already been addressed in successive commits.

**Comment by coelckers** [comment]
Nothing mysterious here, it was just a missing null pointer check that originally accessed undefined memory.

**Comment by mjr4077au** [comment]
Nice one :grin:. Will have a better look in the future.
