### ISSUE TITLE
[Duke]: Hard crash after dying twice

### ISSUE THREAD

**Issue by mjr4077au** [coelckers/Raze#158]
Steps to reproduce:

1. Start a new game (I used E1L1 on Let's Rock difficulty).
2. Give yourself all weapons and kill yourself with rocket launcher (or die by some other means).
3. Repeat step two.
4. Hard crash occurs.

Have not started backtracing yet.

**Comment by mjr4077au** [comment]
Backtraced to f3f0fd0a3aaa1cb61601ef7600367fe40d9f7dc9 but like the other report, not quite sure what's going on here.

**Comment by coelckers** [comment]
Problem was with bad serialization of sound sources. I've added a workaround for this so that it works until the actor system can be fully refactored.

**Comment by mjr4077au** [comment]
🚀
