### ISSUE TITLE
[gaed8a450f] [SW] Crouched position is not always restored

### ISSUE THREAD

**Issue by sinisterseed** [coelckers/Raze#166]
I can reproduce this by saving when crouched using the new crouch toggle, ending the game, starting a new chapter, ending the game again, and reloading that save. When it loads I'll be standing instead of crouching.

Curiously, it works fine if I die and press Use to restart.

**Comment by mjr4077au** [comment]
Will take a look tomorrow, just jumped into bed.

**Comment by sinisterseed** [comment]
Sleep well 😄 .

I may have an idea for why this happens. I think it may actually be just #97 in effect.
