### ISSUE TITLE
[gaed8a450f] [SW] Explosions can ruin fog in certain conditions

### ISSUE THREAD

**Issue by sinisterseed** [coelckers/Raze#167]
Most curious.

I found this on Skyline, if I start throwing grenades through this window, their explosion is somehow causing the fog to freak out, but it comes back after the explosion.

![ShadowWarrior_0000](https://user-images.githubusercontent.com/57503728/98531727-709af700-2289-11eb-8eb5-ef62609e0cc3.png)

![ShadowWarrior_0001](https://user-images.githubusercontent.com/57503728/98531732-71338d80-2289-11eb-8843-7903980bfe1b.png)

**Comment by coelckers** [comment]
That's what happens if you fake fog with a brightness fade. If something brightens up the entire scene the fog will go away for that effect.

**Comment by sinisterseed** [comment]
Surprisingly it happens only when doing that, I couldn't do it outdoors.

**Comment by coelckers** [comment]
I have a suspicion about that: It checks whether the explosion happens in a foggy sector, but the inside isn't. But I cannot find the code to do this stuff.

**Comment by sinisterseed** [comment]
Perhaps this is a side effect of something else if it didn't tied to the fog.

**Comment by coelckers** [comment]
That effect is clearly intended to brighten up the scene - but with fog that only makes the fog go away.

**Comment by sinisterseed** [comment]
Indeed, that's exactly what I was thinking of too.

Now the question is where is that little something.

**Comment by coelckers** [comment]
With my recent change not to use palette fog anymore this problem is gone as well.
