### ISSUE TITLE
Duke - 0.7.3_alpha-286 - Can't move after dying, reviving and disabling god mode

### ISSUE THREAD

**Issue by Axldomi** [coelckers/Raze#172]
Use the following steps:

1. Get yourself killed
2. Revive yourself using godmode cheat "DNKROZ"
3. Disable godmode by again using the cheat "DNKROZ". You can now no longer move. You can still shoot, but no longer move.

**Comment by mjr4077au** [comment]
Will take this one onboard and see what went wrong here, likely something in `FinalizeInput()`.
