### ISSUE TITLE
SW TD - 0.7.3_alpha-286 - Inversed card reader

### ISSUE THREAD

**Issue by Axldomi** [coelckers/Raze#173]
In level 6 "Weapons Research Center" of Twin Dragon, I noticed the red card reader is upside down. See screenshot below.

This appears correctly in the DOS version and in Redux. I've supplied a savegame below.

[save0000.zip](https://github.com/coelckers/Raze/files/5518901/save0000.zip)

![ShadowWarrior_0002](https://user-images.githubusercontent.com/71838912/98705367-ef715c00-237d-11eb-9f45-beec038b5a64.png)

**Comment by sinisterseed** [comment]
Indeed it is fine in Redux & DOS.

I noticed this too, but seemed to recall it was the same everywhere. Not really, apparently.

**Comment by Phredreeke** [comment]
This is very strange. If it was just the Redux version then I would imagine they hardcoded a fix for it but DOS seems unlikely.

Can you test the DOS version with voxels disabled to see if it is still drawn the correct way?

**Comment by coelckers** [comment]
> 
> 
> Indeed it is fine in Redux & DOS.
> 
> I noticed this too, but seemed to recall it was the same everywhere. Not really, apparently.

What about VoidSW and SWP? You always test the engines Raze is not based on so it doesn't help determining where the bug comes from. I know I once made a change to the voxel placement code for another misplaced voxel - no idea if that's the cause.

**Comment by mjr4077au** [comment]
This also happens in VoidSW. I imagine there's flags that get passed to rotatesprite that are wrong? It happens whether voxels are on or off.

**Comment by Phredreeke** [comment]
I recall it being like that in BuildGDX as well, hence my surprise hearing it doesn't happen in DOS (and something I attributed to a mapping error)

I'll check VoidSW if no one beats me to it

**Comment by coelckers** [comment]
> 
> 
> This also happens in VoidSW. I imagine there's flags that get passed to rotatesprite that are wrong? It happens whether voxels are on or off.

The 3D view does not use RotateSprite. 
It'd be interesting to know if it is a Polymost issue and SWR actually fixed it.

**Comment by sinisterseed** [comment]
This is more curious than that.

It seems in VoidSW & us, the panel is flipped if it's rendered as both a voxel and sprite. But in SWP, it renders fine as voxel but it's flipped as sprite.

I think it may be a combination of two factors - the sprite was misplaced originally and it renders fine as voxel, but as a sprite it shows the original error.

**Comment by coelckers** [comment]
That's indeed interesting. It may just be that in the older ports the voxel rendering code was not fully orientation aware, but at some point EDuke32 fixed this - but since we use that code the fix just backfires in this particular case.

**Comment by Phredreeke** [comment]
Yeah, that sounds a lot like another bug (the key in TD's Crazy Train)

Seems the TD devs never bothered testing without voxels (at least it's not as bad as Wanton, where boss encounters are flagged to only occur on the two highest difficulties)

**Comment by sinisterseed** [comment]
> Yeah, that sounds a lot like another bug (the key in TD's Crazy Train)
> 
> Seems the TD devs never bothered testing without voxels (at least it's not as bad as Wanton, where boss encounters are flagged to only occur on the two highest difficulties)

You mean the invisible yellow key inside the cave?

That's not related to the voxel code. We still don't know what exactly it is, but it can't be that because it gets invisible as sprite as well. And I noticed such instances on other maps as well.

The boss in Wanton yeah, that wasn't too cool. But thankfully there are community fixes out there, and we've also fixed that bug if I recall correctly.

**Comment by coelckers** [comment]
All SW ports out there have a fix for the boss bug, as well as the missing anime girls.

**Comment by Phredreeke** [comment]
> You mean the invisible yellow key inside the cave?
> 
> That's not related to the voxel code. We still don't know what exactly it is, but it can't be that because it gets invisible as sprite as well. And I noticed such instances on other maps as well.

the key is flagged as only visible from one side. My guess is that the voxel code was at some point optimised to only draw when the sprite it replaces is visible.

**Comment by sinisterseed** [comment]
> > You mean the invisible yellow key inside the cave?
> > That's not related to the voxel code. We still don't know what exactly it is, but it can't be that because it gets invisible as sprite as well. And I noticed such instances on other maps as well.
> 
> the key is flagged as only visible from one side. My guess is that the voxel code was at some point optimised to only draw when the sprite it replaces is visible.

It's marked to be visible from one side? But that's even more puzzling.

As it renders fine in SWR and DOS. In the case of SWR one could assume it does something different, but that doesn't explain why it shows fine in DOS.

**Comment by coelckers** [comment]
> the key is flagged as only visible from one side. My guess is that the voxel code was at some point optimised to only draw when the sprite it replaces is visible.

Can you tell me the sprite index of that key? Then I can look what SWR did there and possibly replicate the fix.

**Comment by Phredreeke** [comment]
> As it renders fine in SWR and DOS. In the case of SWR one could assume it does something different, but that doesn't explain why it shows fine in DOS.

Turn off voxels and check again.

> Can you tell me the sprite index of that key? Then I can look what SWR did there and possibly replicate the fix.

I think it comes down to SWR using seven year old Polymost code. BuildGDX fixed it by hardcoding a maphack.

**Comment by coelckers** [comment]
Ok, but I still need something to look for. If WangGDX patches this it has to use that index for it.

**Comment by Phredreeke** [comment]
I've been told it is sprite 212
