### ISSUE TITLE
[VS2019 16.8.0] Compile failure

### ISSUE THREAD

**Issue by sinisterseed** [coelckers/Raze#175]
It seems Raze no longer compiles:

![vbbv](https://user-images.githubusercontent.com/57503728/98835625-5576e580-2449-11eb-9dc9-6e97fb587ea7.png)

**Comment by coelckers** [comment]
Oh nice. New compiler, new problems. :-1:

**Comment by sinisterseed** [comment]
Also new CMake 😉 .

Just a regular day in programming, you could say.

**Comment by coelckers** [comment]
I wonder what they did here. C++'s std::sort function no longer works with our TArrays.

**Comment by mjr4077au** [comment]
Something like this came up with 16.5.0 as well IIRC.
