### ISSUE TITLE
[Shadow Warrior] Upscaled HUD weapons loads incorrectly

### ISSUE THREAD

**Issue by duke912** [coelckers/Raze#176]
I just tested the -nowidescreen option, but it doesn't fix the glitched weapons sprites when using upscaled packs, even the non-widescreen friendly sprites loads incorrectly. There is a workaround by Phredreeke on zdoom forum:

https://forum.zdoom.org/viewtopic.php?f=354&t=67251&p=1170430#p1170430

But all it does is just disables the hd sprites for all weapons, meaning it's not exactly a fix.

**Comment by duke912** [comment]
UPDATE: Just tested latest dev build (alpha-304) and all the upscaled HUD weapons are loading as they should, but all the voxels are missing (keys, weapons, objects, etc).

**Comment by mjr4077au** [comment]
If you're using palette emulation, this was fixed 4 hours ago in 483e0b6574d57ba0bedf1e788663684b6cddd903 but might not be in a devbuild.

When on the main repository page, the green tick represents the Continuous Integration status. This is a workflow that tests builds and ensures the game compiles. It leaves artifacts behind you can use to get a quick copy without waiting for a daily devbuild.

![image](https://user-images.githubusercontent.com/48643140/99004621-88c58b80-2593-11eb-9721-6a2bd633430d.png)

Click on "Details" for any one of those items, then download the artifact from the top right corner.

![image](https://user-images.githubusercontent.com/48643140/99004690-a692f080-2593-11eb-9241-89e079e53002.png)

Hopefully with this absolute latest build, your issues are resolved 😄.

**Comment by duke912** [comment]
Yep, it did work, the voxels are loading now. Think you can close this one now

**Comment by mjr4077au** [comment]
Thanks for reporting back, I'm glad it's all working for you now 😁. Have a great weekend!
