### ISSUE TITLE
[Duke]: Liztrooper aiming issues

### ISSUE THREAD

**Issue by mjr4077au** [coelckers/Raze#177]
Unsure whether this is happening to any other actors but when you land in the street in E1L1 and he takes his first shot from the crate, it appears he shoots horizontally instead of aiming for me.

Screenshot below shows him aiming overhead instead of at me. It appears when flying they can't make contact either.

![Duke_0000](https://user-images.githubusercontent.com/48643140/98906293-eb297800-2510-11eb-9d13-3ac48616799e.png)

**Comment by sinisterseed** [comment]
Is this actually different from vanilla though?

Keen eyes sir, if true, never noticed it lol.

**Comment by mjr4077au** [comment]
It's recent which is good, it's fine in 0.7.3. Not sure I'll be able to go through it tonight, girlfriend wants to speed quality time with me (basically watch TV with her and not be on the PC).
