### ISSUE TITLE
[Blood/SW] - [0.7.3_alpha-304]- Voxels not displayed anymore in paletted mode

### ISSUE THREAD

**Issue by Axldomi** [coelckers/Raze#178]
The latest build doesn't show the voxels anymore in Blood or SW. See screenshots below : 

![ShadowWarrior_0004](https://user-images.githubusercontent.com/71838912/98939936-7f341900-24ea-11eb-86b1-4013be5ff301.png)

![ShadowWarrior_0003](https://user-images.githubusercontent.com/71838912/98939951-84916380-24ea-11eb-8f25-2aab0258229e.png)

**Comment by sinisterseed** [comment]
Funny, you're a fast lad 😉 .

I was just about to mention this, but it's the palette causing this, it still works in truecolor:

![ShadowWarrior_0000](https://user-images.githubusercontent.com/57503728/98940131-32087500-24f3-11eb-8403-200828f0f98e.png)

![ShadowWarrior_0001](https://user-images.githubusercontent.com/57503728/98940134-3339a200-24f3-11eb-8b2f-9a8655a2740a.png)

**Comment by coelckers** [comment]
Hm, so my fix was incomplete...

**Comment by sinisterseed** [comment]
It would seem that way.
