### ISSUE TITLE
Duke3DWT - 0.7.3_alpha-304 - E5M1 - Can't fall through pit

### ISSUE THREAD

**Issue by Axldomi** [coelckers/Raze#179]
See screenshot belows. At the end of the level, you should jump in the pit to reach the ending. You will however get stuck in there and won't fall through.

I've provided a save game as well. 
[save0000.zip](https://github.com/coelckers/Raze/files/5532015/save0000.zip)

![Duke_0002](https://user-images.githubusercontent.com/71838912/98969923-a4874e00-250f-11eb-8f99-c348682dbc9d.png)

![Duke_0001](https://user-images.githubusercontent.com/71838912/98969934-a8b36b80-250f-11eb-9e4b-1029a87292a2.png)

**Comment by sinisterseed** [comment]
Sigh, how the game breaks whdn you're not looking...

And I've only played through various WT parts, but this eluded me completely since I didn't finish them all 😩.
