### ISSUE TITLE
[gd07eeba88f] [Blood] Crouch Toggle not properly stored

### ISSUE THREAD

**Issue by sinisterseed** [coelckers/Raze#181]
Seems to be the same as it was for SW.

Everytime I load a save with Caleb crouched he just gets up. 

I tried to fix it myself by looking at what MJ did for SW, but I'm missing something, and making the game no longer compile 🤣.

**Comment by mjr4077au** [comment]
SW and Blood still maintain their own save game systems. The sooner we piss them off, the better.

**Comment by coelckers** [comment]
Let's fix this on the JSON serializer, once I have tested it. The binary save system was saving far too much extraneous data and this likely played a role here.

**Comment by mjr4077au** [comment]
Confirmed fixed with move of saves to JSON.
