### ISSUE TITLE
Powerslave: Received AL error Invalid Value (0xa003), oalsound.cpp:955 (linux) (0.7.3alpha)

### ISSUE THREAD

**Issue by arrowgent** [coelckers/Raze#183]
powerslave
this pops up on the screen repeatedly and in the terminal
im not sure what its warning about
```
>>>>>>>>>>>> Received AL error Invalid Value (0xa003), oalsound.cpp:955
```
points to oalsound.cpp:955
https://github.com/coelckers/Raze/blob/master/source/common/audio/sound/oalsound.cpp
```
unsigned int OpenALSoundRenderer::GetMSLength(SoundHandle sfx)
{
	if(sfx.data)
	{
		ALuint buffer = GET_PTRID(sfx.data);
		if(alIsBuffer(buffer))
		{
			ALint bits, channels, freq, size;
			alGetBufferi(buffer, AL_BITS, &bits);
			alGetBufferi(buffer, AL_CHANNELS, &channels);
			alGetBufferi(buffer, AL_FREQUENCY, &freq);
			alGetBufferi(buffer, AL_SIZE, &size);
:955			if(getALError() == AL_NO_ERROR)
				return (unsigned int)(size / (channels*bits/8) * 1000. / freq);
		}
	}
	return 0;
}
```

**Comment by arrowgent** [comment]
only thing i notice otherwise is the init:
```
I_InitSound: Initializing OpenAL
  Opened device OSS Default
  EFX enabled
No GENMIDI lump found. OPL playback not available.
script parsing took 16.00 ms

```

attached is openal-info
[openal-info.txt](https://github.com/coelckers/Raze/files/5569655/openal-info.txt)

**Comment by coelckers** [comment]
Yeah, some people are getting that. So far we do not know what particular problem triggers this as I have consistently been unable to get it myself and analyze the data being processed.

**Comment by mjr4077au** [comment]
> Yeah, some people are getting that. So far we do not know what particular problem triggers this as I have consistently been unable to get it myself and analyze the data being processed.

I get spammed this at the start of LEV20 (the one we fixed up in #159) more than any other level. If you warp to this map, go through the cutscene to the spawn point, do you get anything like this at all?

**Comment by arrowgent** [comment]
it begins at the start of the game on level 1 and never stops

ill post a comment in # 159 related to that bug

**Comment by arrowgent** [comment]
https://forum.zdoom.org/viewtopic.php?t=57632
related gzdoom

**Comment by mjr4077au** [comment]
The problem isn't in the backend, but rather in the data Exhumed sends to the backend. You'll observe that none of the other games cause these OpenAL issues.

I believe it's to do with the sounds based on 3D positioning that its trying to play but I haven't been able to isolate, mostly from a knowledge gap issue. Next time I'm on the tools (it's business hours in Sydney, Australia at the moment), I'll have more of a stab at trying to backtrace these.

**Comment by arrowgent** [comment]
agreed, no other games do this.

time being im removing line 130:
```
Printf(">>>>>>>>>>>> Received AL error %s (%#x), %s:%u\n", alGetString(err), err, fn, ln);
```

but let us know if you find something 👍🏿

**Comment by coelckers** [comment]
It was just an uninitialized variable. What was so confusing here was that the call that created the error was some 20-30 calls before where the error was reported - in between there were lots of other properties being set.
