### ISSUE TITLE
Duke3D - 0.7.3_alpha-318- E1M4 - Second Crane lift - Screen Flipping

### ISSUE THREAD

**Issue by Axldomi** [coelckers/Raze#185]
I get extremely weird screen behaviour when the **second** crane picks me up in E1M4: the whole screens begins to flip. Even selecting a new game after that won't stop the flipping. It will only stop when you exit Raze.

I provided a savegame a couple of seconds before the crane will pick up Duke.

[save0001.zip](https://github.com/coelckers/Raze/files/5575033/save0001.zip)

**Comment by sinisterseed** [comment]
Confirmed, it seems we've not completely fixed the cranes. The second crane will cause the screen to spasm out uncontrollably, and it goes away only with a restart.

It's rather curious how only the second crane is affected, but the other is fine.

**Comment by coelckers** [comment]
You seem to have committed this to the wrong branch,. I cherry picked it so that I can review the PR later.

**Comment by mjr4077au** [comment]
That was deliberate, it was relying on changes in that branch. The game won't compile more as `getincanglebam()` isn't in master yet.

**Comment by coelckers** [comment]
I noticed after making the comment. I'm currently reviewing the PR.

**Comment by mjr4077au** [comment]
No worries, boss 😁
