### ISSUE TITLE
Duke3DWT - 0.7.3 alpha-318 - Completing Faces of Death --> Launch Facility

### ISSUE THREAD

**Issue by Axldomi** [coelckers/Raze#187]
In Duke Nukem World Tour they made E1L7 "Faces of Death" an official secret level accessible from The Abyss. If you complete Faces of Death, you are normally brought back to the Abyss.

In Raze however, after finishing Faces of Death, the game drops me in Launch Facility (E1L6).

**Comment by sinisterseed** [comment]
Indeed.

Most curious. This was normally a multiplayer map if I recall correctly that was simply tied to singleplayer through that new extra exit. I tested that exit many times, but I was completely unaware of the fact that Faces of Death had an exit too, I always thought it goes nowhere, oops.

It does indeed take the player back to E1L6. I assume the exit code is wrong here.

**Comment by coelckers** [comment]
The issue is that Duke has no well defined secret exit semantics. If you use a secret exit the level is stored and exiting the secret level goes to the next level after that regular one. Apparently for WT they added a hack for this map that I missed.

**Comment by Phredreeke** [comment]
The placement of Faces of Death doesn't work for a gameplay progression perspective IMO. I guess adding a stub level after the secret level a la Death wish containing just the end of Abyss and the Battlelord would have been too much work.

Anyway this unrelated to the bug at hand and I'm just ranting.

**Comment by coelckers** [comment]
My thoughts precisely. Essentially it is broken either way.
They should have ended the game in Faces of Death instead of returning to the previous one.

**Comment by sinisterseed** [comment]
I would have rather not seen this at all honestly.

I mean Phredreeke is right, this makes no sense for fuck's sake... normal map -> secret multiplayer map -> previous map. Besides yeah, it should have ended there if you decided to take that route instead, but it would've been too anti-climatic for a finale to an episode.

Good design, what can I say.

**Comment by Axldomi** [comment]
Indeed, returning to the Abyss doens't make any sense at all since it forces the player to run through the entire level for the second time.

IMO, the best way forward would be that Raze would end the episode after Faces of Death. I leave it up to you guys to decide what's best.

**Comment by sinisterseed** [comment]
Well, I'm not opposed to that idea, but IMO I think it's best to stick to what was actually intended here by the developers, despite our personal feelings.
