### ISSUE TITLE
Duke3D - 0.7.3_alpha-318 - Battlelord won't attack me anymore.

### ISSUE THREAD

**Issue by Axldomi** [coelckers/Raze#188]
I'm currently playing through episode 2. And in E2M5 "Occupied Territory", one of the Battlelords from the Red Key room, won't attack me anymore.

I've provided a savegame. I don't know if this is a Raze bug or a general bug in Duke Nukem 3D, but I've been playing Build games through Dos and modern sourceports since I was a kid and never experienced this behaviour before.

[save0001.zip](https://github.com/coelckers/Raze/files/5577673/save0001.zip)

![Duke_0002](https://user-images.githubusercontent.com/71838912/99878139-9322fd80-2c03-11eb-8e1a-e877f785155d.png)

**Comment by sinisterseed** [comment]
Peculiar.

If I load your save, I can indeed confirm he doesn't engage anymore, he just wanders around. They do have such a routine, but this particular Battlelord has gotten stuck in it somehow.

I tried warping and going to the map, and he was fine. But the save is glitched regardless of what I'm doing. I've not experienced anything similar before either, or in the other ports, so I'm inclined to say this is indeed a bug, but no idea what conditions actually trigger it.

**Comment by coelckers** [comment]
Do you remember some of these CON scripting bugs n the past? It's probably just another one where a certain condition is not properly checked for and it falls back on a no-op routine it never can get out of anymore.
It will be hard to find out what triggered it, only having the glitched save.

**Comment by sinisterseed** [comment]
I certainly do.

That's why I asked about whether Axl did anything out of the ordinary to trigger this, or simply went to the map (from another save, warped, etc.) and the Battlelord simply glitched that time.

**Comment by Axldomi** [comment]
No, I didn't do anything special to trigger this. I killed the first 2 battlelords and after that I went for the third one, only to find him wandering around doing nothing. At that moment I made the savegame.

**Comment by sinisterseed** [comment]
Alright then.

May be a CON thing then, we've seen some oddities in the past, but in that case it may also mean it's unfixable. We'll see.

The only instances I've had Battlelords not engaging was when they got stuck (yeah it's possible for that to happen in some maps sometimes), but this right here, out in the open, completely ignoring the player, is definitely new.

**Comment by coelckers** [comment]
I cannot even shoot him. Looks like he's dead but somehow refused to die, now walking around as an undead ghost.
But without knowing what triggered this it may be hard to track down.

**Comment by sinisterseed** [comment]
Fascinating, but accordi g to Axl he shouldn't be, that's how he said he found him.

Like I asked in a separate issue, did you upgrade to a new build with a previous save, or started fresh?

**Comment by Axldomi** [comment]
I don't know if this is helpful or not, but he doesn't appear to be dead. You can't shoot him with pistols, but you can however make him normal again with explosions. Fire a few devastator rounds at his feet and he'll be back to normal.

**Comment by coelckers** [comment]
I tried to debug this but I always get stuck in some apparently faulty script logic. Unless this happens again in a way that's easier to check I'm going to write it off as a poorly written monster script.
