### ISSUE TITLE
[Redneck Rampage Rides Again] Error when trying to finish E1L7

### ISSUE THREAD

**Issue by duke912** [coelckers/Raze#189]
I'm getting an error (Trying to open non-existent (null)) at the end of E1L7 in Rides Again.

Save at the end of the level:

[save0000.zip](https://github.com/coelckers/Raze/files/5578884/save0000.zip)

**Comment by sinisterseed** [comment]
I can do better than that with your save in gb97f12a2e.

I can crash the game after jumping down into the canal in that room. But there is something else that looks quite wrong in your save. There are biker sprites standing still, which I suppose are dead enemies, but for some reason they're shown incorrectly.

[CrashReport.zip](https://github.com/coelckers/Raze/files/5579303/CrashReport.zip)

**Comment by duke912** [comment]
I'm using latest version (alpha-318)

**Comment by sinisterseed** [comment]
Did you start fresh, or did you upgrade and continued from an older save?

I can't get those weird bikers glitching at all.

**Comment by duke912** [comment]
> Did you start fresh, or did you upgrade and continued from an older save?
> 
> I can't get those weird bikers glitching at all.

Yes, I did start new game from that version, and for the bikers, they are all loading as they should for me.

**Comment by sinisterseed** [comment]
Curious then, for me some display correctly, while others are in their attack pose despite being dead.

**Comment by duke912** [comment]
Just for a quick test, I downloaded the latest version (alpha-342), started a new game and warped to the same level, played through it again (with God cheat), and I still get the same error when trying to finish the level.
