### ISSUE TITLE
Exhumed - 0.7.3 - alpha-342 - All items - Weapon selection glitched

### ISSUE THREAD

**Issue by Axldomi** [coelckers/Raze#193]
- use the all weapons cheat
- use "previous weapon" command

--> gives you the following result:

![Exhumed_0000](https://user-images.githubusercontent.com/71838912/99906655-a18f1900-2cd8-11eb-9b7f-72f763f0e40d.png)

![Exhumed_0002](https://user-images.githubusercontent.com/71838912/99906664-a81d9080-2cd8-11eb-84b1-704645b447aa.png)

**Comment by sinisterseed** [comment]
Confirmed.

It seems it scrolls through what it should not be able to, which includes the death arms.

**Comment by mjr4077au** [comment]
Thanks for fixing that, clearly slipped through the cracks on me when I was setting the functionality up.
