### ISSUE TITLE
[gb97f12a2e] [SW-TD] Odd Coolie Ghost in Silver Bullet/Crazy Train

### ISSUE THREAD

**Issue by sinisterseed** [coelckers/Raze#194]
At the beginning of this map, in the sewer that gets blown up via the pipes, are some Coolie Ghosts, but one of them is glitchy.

It takes a lot of effort to kill with any of the weapons available at the start (Sword, Uzi, Shotgun), it seems shots and hits just refuse to connect with it for some reason, and its sprite also looks a bit jittery. This doesn't happen in VoidSW, hits connect just fine there without effort. It also seems to completely ignore the player for some reason.

No save to provide here since it's literally at the start of the map. Just levelwarp 12, blow up the pipes in front of you, and jump below.

**Comment by mjr4077au** [comment]
Not sure I can reproduce... Warped to the level on highest difficulty, had two coolie ghosts and they both took normal damage to kill.

Can you test again and also confirm the difficulty you were using?

**Comment by sinisterseed** [comment]
Hm, curious, this is fine now.

I wonder what it was, but sure enough it's not happening anymore.
