### ISSUE TITLE
Main menu can't be bound to a controller button

### ISSUE THREAD

**Issue by sinisterseed** [coelckers/Raze#195]
https://www.doomworld.com/forum/topic/111839-source-port-introducing-raze-thats-one-duked-up-space-marine/?do=findComment&comment=2221864

"I cannot﻿ bind the main﻿ menu to a controller button. In GZDoom, one of the buttons comes prebound to act as the Escape key, ﻿bringing up the menu. I cannot do this on Raze, and have to press ESC manually to exit the game or start a new game, etc. I ﻿﻿tried ﻿bindin Start﻿ ﻿to the﻿ Options menu, but I cant back out into the main menu from there. I apologise if these are known issues﻿, but ﻿﻿feedback is feedback﻿ :﻿p"

Cannot attest this since I don't have any controllers though.

**Comment by duke912** [comment]
If I remember correctly, you need to bind with the console command (to start button): bind pad_start menu_main

Nevertheless, I agree it would be better to have it in the keybinds menu.

**Comment by coelckers** [comment]
Added the missing bindings from GZDoom to the defaults.
Will do a menu option for this later.

**Comment by coelckers** [comment]
Thinking about it, I do not think this option should be in the menu because ESC is hard coded.
