### ISSUE TITLE
[Shadow Warrior] Screen shaking bug in level 2 "Zilla Construction"

### ISSUE THREAD

**Issue by duke912** [coelckers/Raze#197]
When trying to climb the ladder at the side of the turret in the second level of the first episode, the screen start shaking non-stop (until you reload a save).

[save0001.zip](https://github.com/coelckers/Raze/files/5591916/save0001.zip)

The save is in front the glitched ladder.

**Comment by sinisterseed** [comment]
Ouch, this is stupid.

Particularly because I've just warped through some maps today to investigate ladders in particular. And I missed exactly one that was glitched...

**Comment by duke912** [comment]
Just found another one in the boss room from the first level of second episode:

[save0003.zip](https://github.com/coelckers/Raze/files/5592590/save0003.zip)

**Comment by mjr4077au** [comment]
Thanks for the report, a recent regression. I'll do something better with the "settarget()" method used on angles tonight when I'm home from work and have more time.
