### ISSUE TITLE
strange way of counting super secrets in "Level statistics"

### ISSUE THREAD

**Issue by FyiurAmron** [coelckers/Raze#198]
Since, w.r.t. "Level statistics" HUD, max secrets stat is counted without taking SS into account but SS is taken into account for current secret count, with (e.g. in E1M1) 10/11 secrets + super secret, you get the misleading "green" `11/11` count, but after getting 11+SS, you get `12/11`, gray again... note that the level finish screen shows these two reasonably, in two separate portions.

I'd suggest tweaking this to display e.g. "10/11 + 1/1" instead of just the misleading "11/11".

**Comment by coelckers** [comment]
fixed in 82d80f3f07e2d458ee7768f0a9f1c7e2f5348918
