### ISSUE TITLE
[Blood]: Ensure player can't keep triggering already triggered secrets as per comments in #205.

### ISSUE THREAD

**Issue by mjr4077au** [coelckers/Raze#206]
Won't have a chance until tonight, but probably coming from `SECRET_Trigger()`.

**Comment by mjr4077au** [comment]
This one will need further looking into on another night. The backend `SECRET_Trigger()` isn't the issue, rather one of the calls to `evSend()`. Been a long day, will try to isolate on the train in tomorrow morning.

**Comment by coelckers** [comment]
Maybe this can leverage the SECRET_Trigger info to recognize that a secret just got retriggered.
The info in there is meant for the same secret hint system that's present in GZDoom, so it knows which secrets were already credited in order to highlight their hint message.

**Comment by mjr4077au** [comment]
Yeah, that'll work nicely. I was trying to find the root cause but it's like looking for a needle in a haystack. It was only this secret that got triggered as well, not every one.

Thanks for fixing it up ☺️

**Comment by coelckers** [comment]
It's like everything in Blood, overcomplicated, unintuitive and hard to find. Secret triggers are events - in this case it is one event chained to the activation of the revolving wall. The way I understand the system it's virtually impossible to fix because you'd have to edit the event setup for that wall.

**Comment by mjr4077au** [comment]
Absolutely agreed on everything there. I did find the evSend call causing the issue but still needed to backtrack further. I think `pXSprite->triggerOn` keeps getting reset once the door goes through an open/close cycle.

https://github.com/coelckers/Raze/blob/3c83775273592b064ac6610f5fda339b586120fe/source/blood/src/triggers.cpp#L92-L93

Doesn't matter now though of course 😁

**Comment by coelckers** [comment]
Problem is, that call gets used for lots of things, not just the secret, so any change there would have to amount to some gross hacks.

**Comment by mjr4077au** [comment]
Yeah, I know. I was going to try and chase it further up the stack and not do anything there, but all good now 😁.

**Comment by coelckers** [comment]
You wouldn't have gotten far with that - ultimately it's a map bug so all that's have been possible is some hackery.

**Comment by mjr4077au** [comment]
Then I appreciate you stepping in all the more so I wasn't chasing my tail 😁.
