### ISSUE TITLE
libretro port? :)

### ISSUE THREAD

**Issue by DartPower** [coelckers/Raze#207]
Hi there, i have a idea, you want to port to libretro?
This is will be cool. (My dream this is a Raze & ZDoom-based ports in libretro, this is a my own euphoria, and more fans)
(Sorry for my bad english)

Check this also please :)
https://www.libretro.com/index.php/mission/
https://docs.libretro.com/development/cores/developing-cores/
https://www.libretro.com/index.php/powered-by-libretro/
https://docs.libretro.com/development/cores/opengl-cores/

**Comment by coelckers** [comment]
Sorry, it won't happen. The engine driving both ports is too modern to target such an abstraction platform, that goes both for hardware accelerated rendering and for its sound engine.

You'd have to rewrite quite a bit of code to make this happen and it's simply out of scope.
