### ISSUE TITLE
[396e3cd] [Exhumed] Player doesn't face Ramses during the cutscene

### ISSUE THREAD

**Issue by sinisterseed** [coelckers/Raze#208]
![Exhumed_0000](https://user-images.githubusercontent.com/57503728/101034860-459f7c80-3583-11eb-927c-0c18f1c3e4cf.png)

The view gets centered, but the player will be facing the wall to the right when Ramses is speaking instead of looking at him.

[wrongorietation.zip](https://github.com/coelckers/Raze/files/5636651/wrongorietation.zip)

**Comment by mjr4077au** [comment]
Thanks mate, will take a look at this soon.

**Comment by mjr4077au** [comment]
Out of battery as I didn't charge before home, but know where the issue is. Will look tonight.

**Comment by mjr4077au** [comment]
Ok this isn't what I thought, its actually a savegame bug. If I use warptocoords to go to this location on a fresh launch, works perfectly irrespective of `cl_syncinput`. If I go there from a save, either yours or one I made it goes to shit.

Coordinates for reference:

![image](https://user-images.githubusercontent.com/48643140/101158327-a90ed480-367f-11eb-9633-d6ed3e221848.png)

@coelckers any idea what might be causing this?

**Comment by coelckers** [comment]
Probably some variable was missed in the savegame rewrite.

**Comment by sinisterseed** [comment]
Oh damn, really? That flew under my radar, didn't realize it worked fine with no saves.

It's a save issue then, something in the player (probably?) must've been missed.

**Comment by coelckers** [comment]
Shouldn't be too hard to find.

**Comment by mjr4077au** [comment]
Graf fixed this with 99da4151d1656ae7b562172d4f00e76463a1907a 😄.

**Comment by coelckers** [comment]
This was the same thing? Oh, well...

**Comment by mjr4077au** [comment]
Yup seemed to be. Even sinisterseed's save in the initial report works fine now as well 😁.
