### ISSUE TITLE
[396e3cd] [Blood] Godmode resets after completing a map but the game doesn't seem to recognize this

### ISSUE THREAD

**Issue by sinisterseed** [coelckers/Raze#210]
To reproduce, simply start a map, enable godmode in it, and finish it that way. Then die (or not) on the next, but if you do, it seems the actual invincible state does not get written into the save.

On the next level, you will no longer be invincible, but the game doesn't quite seem to recognize this as it will report that the player is now mortal when enabling godmode back - not really, the player is now invincible.

Small example:

> ]god
> You are immortal.
> GAME SAVED
> 
> e1m2: Wrong Side of the Tracks
> GAME SAVED
> You killed yourself!
> 
> ]god
> You are mortal.

Game is lying, I died, pressed "Use" to autoload the last save, and re-enabled godmode. Yet it says I am not. Godmode should also not be resetting after every map.

[godmode.zip](https://github.com/coelckers/Raze/files/5636764/godmode.zip)

**Comment by coelckers** [comment]
Like everything else in Blood the god mode implementation is stupid, overcomplicated and prone to breakage. Instead of just checking the global flag when taking damage, Blood mucks around with the damage control flags and never actually checks if god mode is on.
