### ISSUE TITLE
[d040130] [Blood] Game crashes if loading a save with a firing weapon yet to make contact

### ISSUE THREAD

**Issue by sinisterseed** [coelckers/Raze#212]
To reproduce, simply fire up the game, give yourself the weapons, and fire Napalm.

Now, before it makes contact with anything - in other words, as it's still travelling - make a real quick save. End the game. Restart the game or start another map, end the game again, and reload the save.

The game will crash now, with the crash manager open. I've been doing some endurance tests for the new save format, and something I wanted to test but forgot was this, the full restoration of actors and especially weapons.

[CrashReport.zip](https://github.com/coelckers/Raze/files/5646976/CrashReport.zip)

**Comment by sinisterseed** [comment]
Same procedure for TNT, just crashed again.

**Comment by sinisterseed** [comment]
Well this is getting interesting now, it's not specific to just projectile-based weapons, it happens with hitscan weapons too.

Same procedure, but fired a Shotgun blast at an innocent on E3M1 and quicksaved before it made contact with him this time. And the game went kaput.

[shotgun.zip](https://github.com/coelckers/Raze/files/5646995/shotgun.zip)

**Comment by sinisterseed** [comment]
More awesomeness, same procedure.

You can never be too sure about these things, so I made a collection of crash logs with almost every weapon just in case.

[leech.zip](https://github.com/coelckers/Raze/files/5647016/leech.zip)
[pistolsecondaryfire.zip](https://github.com/coelckers/Raze/files/5647017/pistolsecondaryfire.zip)
[pitchfork.zip](https://github.com/coelckers/Raze/files/5647018/pitchfork.zip)
[proximitydetonator.zip](https://github.com/coelckers/Raze/files/5647019/proximitydetonator.zip)
[tesla.zip](https://github.com/coelckers/Raze/files/5647020/tesla.zip)
[voodoodoll.zip](https://github.com/coelckers/Raze/files/5647021/voodoodoll.zip)

**Comment by coelckers** [comment]
The savegames would be more useful. I can't do much with the crash logs as they only represent the state after the fact.

**Comment by sinisterseed** [comment]
Fair enough. I'll be back shortly.

Yeah, I'm gonna recreate them, didn't expect they'd also be needed.

**Comment by sinisterseed** [comment]
Done.

[bloodsavecollection.zip](https://github.com/coelckers/Raze/files/5647081/bloodsavecollection.zip)
