### ISSUE TITLE
Will the Build Engine demos be supported 

### ISSUE THREAD

**Issue by arivega** [coelckers/Raze#214]
I know that JonoF's port supports it 
and I wonder if Raze will support it as the build engine demos are freeware and were released publically with source

**Comment by sinisterseed** [comment]
There may be some demo capability added in the future, but it will be similar to how they are handled in ZDoom/GZDoom.

The way demos worked in these games was not optimal for our engine so they were inevitably dropped after the migration of the backend following the release of 0.6.0, and the changes to the main loop that inevitably followed afterwards.

So in short, perhaps, but it is not a priority for the time being. And the original demos will not be coming back, that is a definite "no".

**Comment by arivega** [comment]
No I meant this https://www.youtube.com/watch?v=N0qZaIIqVc0

**Comment by coelckers** [comment]
No. That's a completely separate code base from the other games - and for just being able to play such a demo there's too much work involved.
