### ISSUE TITLE
Homebrew formulae / cask?

### ISSUE THREAD

**Issue by boggydigital** [coelckers/Raze#215]
I've noticed that Raze is not available through [Homebrew](https://brew.sh) on macOS. I suspect that's because nobody have submitted it yet (I could be wrong).

I would be happy to [submit and maintain](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md) this and wanted to check with authors if that's fine with you. Homebrew lists ["The author has specifically asked us not to include it"](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/rejected_casks.md) as one of the potential rejection reasons. I skimmed other requirements and it looks like Raze meets all of them.

FWIW [GZDoom](https://github.com/Homebrew/homebrew-cask/blob/1bc56882a508ea9085dea2d758e6b65176cea2a1/Casks/gzdoom.rb) is available as cask through Homebrew and I'm planning to use it as an example.

**Comment by coelckers** [comment]
The GZDoom version there is done by somebody not related to the project.
I'm not against it but  it's not something I'd be willing to invest time in, so if you want to do it, you are welcome of course.

**Comment by boggydigital** [comment]
Great thank you - I'd be happy to do that.

**Comment by boggydigital** [comment]
FWIW it's added and I'm planning to maintain as needed: https://github.com/Homebrew/homebrew-cask/pull/94399
