### ISSUE TITLE
[v0.8x] Palette emulation causes texture corruption

### ISSUE THREAD

**Issue by mgtroyas** [coelckers/Raze#219]
Enabling palette emulation causes texture corruption. Also bilinear/trilinear filtering is not applied with this option.

Windows 10 and AMD Radeon RX580.

This didn't happen on previous versions. Happens on both OpenGL and Vulkan renderers.

![Duke_0000](https://user-images.githubusercontent.com/30797135/101358697-822cea00-389b-11eb-8aa3-17d7802c5e24.png)

**Comment by sinisterseed** [comment]
Vulkan is currently nonfunctional.

I will check the said corruption to see for myself, but regarding texture filtering, that is normal. It is simply how the palette works, it has quite a few technological blocks. No advanced features can work with it, such as Anisotropic Filtering, Texture Filtering, or dynamic lights. It is a take or leave kind of feature, you get the palette but lose advanced visual features in the process.

There is no way to fix this.

**Comment by sinisterseed** [comment]
Tried to reproduce the corruption as well, thinking that it may have been some peculiarity in that area, but it's solid for me, no issues whatsoever.

In this case, I can only suggest you update your drivers if you haven't already, that would be a prime cause for graphical glitches.

**Comment by mgtroyas** [comment]
You're right. I tried Raze 7.3 and corruption is still there. I updated Radeon Software/drivers some weeks ago, so yes it can be the cause.

**Comment by sinisterseed** [comment]
Do you also experience this, or a variation thereof, in 0.6 for instance?

**Comment by mgtroyas** [comment]
No, in 0.6 with same settings (overwriting Raze files), it's fixed. As soon as I overwrite with 8.1 files, the issue returns.

**Comment by sinisterseed** [comment]
Make sure you did delete and let the game generate another configuration file after upgrading, as keeping old important files can lead to bizarre issues sometimes.

That's a bit puzzling if 0.6 was fine. I wonder what's going on here. My guess is, it's something in the palette as I can reproduce a similar effect but in GDX if I enable anisotropic filtering while the palette is enabled. It's also AMD hardware.

**Comment by mgtroyas** [comment]
Did a clean install of 8.1 on an empty folder: only Raze files and the DUKE3D.GRP file. Ran Raze, started a game (L.A. Meltdown rooftop) and as soon as I enabled palette emulation the corruption showed.

Enabling/disabling texture filtering, anisotropic filtering, Multisampling has no instant fix on corruption. But then I tried changing those options, then exiting Raze and running it again: yes, some of those settings is the problem.

I did some tests changing them one by one:
- Multisampling has no effect on the corruption.
- Anisotropic filtering has no effect on the corruption. Although I cannot see changes in image quality, on any case.
- Texture filtering mode: THAT's the problem.
 - None --> no corruption.
 - None (nearest mipmap) --> corruption.
 - None (linear mipmap) --> corruption.
 - None (trilinear) --> corruption.
 - Linear --> no corruption (no bilinear filtering though).
 - Bilinear --> corruption (no bilinear filtering though).
 - Trilinear --> corruption (no bilinear filtering though).

When starting Raze on linear/bilinear/trilinear with palette emulation off as soon I enable palette emulation, bilinear filter is disabled and corruption is shown.

Seems an incompatibility between any mipmap mode different from nearest, and palette emulation.

On Raze 0.6 none of these settings create any image corruption. What's funny is there's also another difference: with linear/bilinear/trilinear filtering enabled, on Raze 0.6 text font on menus is filtered, while in 0.8x (and 0.7x) text is not filtered. Only disabling palette emulation text on menus is then filtered instantly.

**Comment by coelckers** [comment]
That's odd - the texture filtering should be completely off with palette emulation enabled. But apparently some state is still bleeding through. Weird.

The filtering in the menu was intentionally changed to make it consistent, i.e. since palette emulation cannot use filtering, the filter also gets disabled for non-paletted content.

**Comment by sinisterseed** [comment]
Interesting development. Looking at how the corruption is, I had a hunch that it must be something that is still trying to be set while the palette is used instead of being wholly ignored. Similar to GDX I guess, where enabling one of these features also causes a mess of pixels on the whole screen, because it tries to sti apply the effects, despite being unsupported.

At least we found what it is. Good catch 👍. Curiously it doesn't happen with the mipmap modes, only the filtering ones.

**Comment by sinisterseed** [comment]
I was initially wondering how this managed to slip in, but now that I've been trying to reproduce it, I guess I know why.

Because I can't actually reproduce it following the procedure. It's rock solid for me, no corruption anywhere. I wonder if it isn't a change we've made that doesn't play well with AMD hardware.

**Comment by M1sh2** [comment]
I have win 10 x64 version 20H2, processor ryzen 5 1600, videocard RX590 8gb  with driver adrenaline 20.11.2, tested on e1l2, in toilet too, with palette with anisotropy works on both renders. I had another error, i dont know why on new renders of the Graf Zahl colors are inverted (in gzdoom and raze), after deleting configurations, everything works as usually.
![изображение](https://user-images.githubusercontent.com/59886778/101490854-863d3280-3995-11eb-9b91-f83d9b41d504.png)

**Comment by sinisterseed** [comment]
So a full AMD system, but slightly different card this time. And no errors this time. This is making me wonder whether this may be a hardware issue for mgtroyas, though it doesn't explain why he doesn't experience it in the old base.

Regarding Vulkan, we really need to disable it. It is currently selectable but it simply isn't ready yet and doesn't work correctly. Only OpenGL is currently supported.

**Comment by coelckers** [comment]
> So a full AMD system, but slightly different card this time. And no errors this time. This is making me wonder whether this may be a hardware issue for mgtroyas, though it doesn't explain why he doesn't experience it in the old base.
> 

Texture sampler management worked a bit differently in the old version.

**Comment by mgtroyas** [comment]
I just launched the same install from a laptop with integrated Intel graphics and the corruption doesn't happen. So yes, seems something specific to some AMD graphics cards, at least my RX580.

BTW, if palette emulation isn't compatible  with any filtering and mipmaps, I suggest enabling the former disables completely the later, to prevent this issue on the cards that can't handle it.

**Comment by sinisterseed** [comment]
The thing is, that's exactly what it's supposed to do, so we're going to check if there may be some leaks somewhere as well.

**Comment by coelckers** [comment]
@mgtroyas Can you please recheck with the next devbuild? I made a small change to the texture creation code.

**Comment by sinisterseed** [comment]
Or if you want it faster, you can use a CI artifact instead. You can get one from the green check mark next to the commit message, simply press on it - Details - Artifacts - choose a Visual Studio Release build.

**Comment by mgtroyas** [comment]
I can confirm it now works as expected on my setup :)

**Comment by mgtroyas** [comment]
I suppose it's me who must close the issue?

**Comment by coelckers** [comment]
In this case, yes, because it was undefined driver behavior that's specific to your configuration. I was unable to reproduce the problem with my Geforce.

Thanks for confirming.
