### ISSUE TITLE
[SW JSON rework] Missing doors

### ISSUE THREAD

**Issue by sinisterseed** [coelckers/Raze#224]
After reload, various doors effectively disappear, with the exception of their sounds, which continue to play regardless of this.

This is MAP03 after reload, and a similar effect is observed in Seppuku Station with the double doors inside the building as well, right after opening the yellow door.

![ShadowWarrior_0001](https://user-images.githubusercontent.com/57503728/101518044-14132080-398a-11eb-9a68-5420fdf1d9d2.png)

**Comment by coelckers** [comment]
See my remark in #228
