### ISSUE TITLE
[Blood] Wrong Cultists throw dynamite

### ISSUE THREAD

**Issue by GorrillaRibs** [coelckers/Raze#225]
I don't have a dos copy to test on right now to confirm, but if I remember right (confirmed in fresh supply & regular nblood) the beige cultists throw dynamite, but in raze the grey-robed ones do instead. This doesn't happen in nblood (as of the current master), so maybe a fix is as simple as figuring out what they've done?

**Comment by sinisterseed** [comment]
Or maybe we just mixed something up.

This is gonna be a bit frustrating insofar as I just tried to see it for myself to confirm, but of course now no-one wants to bomb me, how convenient. Regardless, your assessment is correct, Fanatics (those are the ones in dark robes) are not supposed to throw dynamite/TNT bundles (varies with difficulty).

**Comment by coelckers** [comment]
It's the green ones that throw dynamite, not the beige ones. There's one that's easy to test right at the start of E6M1.

**Comment by sinisterseed** [comment]
I believe you are mistaken.

It's not just the Acolytes (those are the green cultists you mentioned) who throw dynamite, it's also the beige ones. And the Acolyte is fine.

https://www.blood-wiki.org/index.php/Cultist

**Comment by coelckers** [comment]
Here's what the source reveals:

The shotgun cultist can throw dynamite on skill "Lightly broiled" or higher.
for the other ones the info is conflicting: NBlood has code that lets them throw dynamite only on "Well Done" and "Extra Crispy". GDX has the code but comments it out. So the sources are conflicting and it is unclear which one is correct. It is clear that this code comes from somewhere if it is in NBlood but without any further data available I cannot decide who is correct here.

**Comment by GorrillaRibs** [comment]
I just got done trying out One Whole Unit Blood (the gog version) in dosbox - on lightly broiled or higher the shotgun cultist throws dynamite (seems like sticks of dynamite on lightly broiled and full bundles on higher skills?). Tested by just walking around a couple maps in e1 with the invulnerability cheat so I didn't have to reload a bunch of saves (I can upload a video somewhere, if that helps? Maybe I'm triggering something with my dosbox setup thats unintended behaviour).

The fanatic never seems to throw dynamite in dos, but they do in raze currently (at least on Well Done), so that seems like a bug regardless of the intended behaviour of the shotgun cultist.

**Comment by coelckers** [comment]
Yeah, like I said, it's hard to tell who is right here with two conflicting sources. Did you actually test this on DOS yourself?

**Comment by sinisterseed** [comment]
Yeah, like Graf said, that's because the code is that way. GDX seems to act according to the general consensus that Fanatics and Zealots do NOT throw dynamite/TNT bundles (yes, as I said above, this changes with difficulty), hence the code is commented out.

**Comment by sinisterseed** [comment]
So, we've done some more research, and found out that the reason why the other Cultists don't throw dynamite in DOS after version 1.00 is because something broke in the networking code, which likely got reactivated for us during a rework. DOS later fixed this only for the brown Cultists via an inversion of the flag in their AI code.

In order to preserve the original experience, this will be made into a toggle, and we'll offer the fixed behavior as an option.

**Comment by coelckers** [comment]
This hasn't been addressed yet so it cannot be closed.

**Comment by sinisterseed** [comment]
Ah, yes, oops, that way we may forget about it if something else comes up.

Sorry for doing it prematurely.

**Comment by markanini** [comment]
I can't detect any bug with black cultists throwing dynamite, at least on Lighty Broiled difficulty. Brown and green cultists throw dynamite, that's how it's been in all ports I've tried with v1.21 game data.
