### ISSUE TITLE
[SW JSON rework] Various switches do nothing

### ISSUE THREAD

**Issue by sinisterseed** [coelckers/Raze#226]
Most easily observed on MAP04.

The switches meant to lower a series of three switches does not work, rendering the map impossible to complete.

![ShadowWarrior_0000](https://user-images.githubusercontent.com/57503728/101640563-534c7a80-3a39-11eb-9741-3944c2de2f1e.png)

[switches.zip](https://github.com/coelckers/Raze/files/5666409/switches.zip)

**Comment by coelckers** [comment]
See my remark in #228
