### ISSUE TITLE
[SW JSON rework] Sprites not changing their position

### ISSUE THREAD

**Issue by sinisterseed** [coelckers/Raze#227]
Noticed this on a table on MAP05, when it lowers the sprites on it don't change their position at all.

![ShadowWarrior_0001](https://user-images.githubusercontent.com/57503728/101641258-35cbe080-3a3a-11eb-83c2-254bd189abe0.png)

[sprites.zip](https://github.com/coelckers/Raze/files/5666458/sprites.zip)

**Comment by coelckers** [comment]
See my remark in #228
