### ISSUE TITLE
[SW JSON rework] Turrets crash the game

### ISSUE THREAD

**Issue by sinisterseed** [coelckers/Raze#228]
With the manager open.

Easiest to see is also on MAP05, firing it crashes the game.

[crashyturrets.zip](https://github.com/coelckers/Raze/files/5666487/crashyturrets.zip)

**Comment by sinisterseed** [comment]
Same thing with armed boats and ships. Repairing them works fine, but the game crashes after firing their gun(s).

[boat.zip](https://github.com/coelckers/Raze/files/5666613/boat.zip)

[crashyboat.zip](https://github.com/coelckers/Raze/files/5666614/crashyboat.zip)

**Comment by coelckers** [comment]
I think I put this code aside for the time being. SW seems to be a bit too volatile for a savegame rework. :-1:

**Comment by coelckers** [comment]
After doing a bit of checking on SW I have to conclude that several savegame size optimizations necessary for the JSON system cannot work without first refactoring all the game data to be more serialization friendly. The assumptions I built this on do not work out, making the entire new savegame system problematic. For now this is closed - the code is still there for a time in the future where this can be done.
