### ISSUE TITLE
[94d3d64] [SW] HUD Positioning Issues

### ISSUE THREAD

**Issue by sinisterseed** [coelckers/Raze#229]
An user pointed this out on Discord. It seems there are some glaring issues that eluded us after the settings didn't work at all last time.

The inventory goes offscreen once the scale gets too small on the partial and modern HUD, while on the status bar it changes its position.

![ShadowWarrior_0000](https://user-images.githubusercontent.com/57503728/101789413-f53b9800-3b09-11eb-9031-35a531f8678c.png)

![ShadowWarrior_0001](https://user-images.githubusercontent.com/57503728/101789419-f66cc500-3b09-11eb-820e-152fba20cd59.png)

![ShadowWarrior_0002](https://user-images.githubusercontent.com/57503728/101789420-f66cc500-3b09-11eb-87da-a47dd5283ab2.png)

**Comment by sinisterseed** [comment]
Also Blood, this time around regardless of scaling:

![Blood_0000](https://user-images.githubusercontent.com/57503728/101791017-bd355480-3b0b-11eb-9cdd-dcafe7ae9901.png)

**Comment by sinisterseed** [comment]
In RR the inventory panel is also a bit too low with the full status bar drawn:

![Redneck_0000](https://user-images.githubusercontent.com/57503728/101792674-a55ed000-3b0d-11eb-91d4-271e58bbe368.png)

**Comment by coelckers** [comment]
Can you please split this ticket up so each game has its own one?

**Comment by sinisterseed** [comment]
Fair enough, but since the issue was related I figured they could fit a single ticket.

**Comment by coelckers** [comment]
All in different code...
