### ISSUE TITLE
Work on Pi4

### ISSUE THREAD

**Issue by Exarkuniv** [coelckers/Raze#232]
Im just messing around and see what i can get to work on my Pi4. i managed to get it to compile fine on it. and even got it to see the game dir. 

when i start it. it starts then says i need OpenGL 3.3. im going to guess im out of luck on having this run on a Pi4
and if i am. it was still fun trying to get it to complie and everything

**Comment by mjr4077au** [comment]
Thats awesome to hear you've been able to build it on such a platform! Yes, unfortunately we don't have any Vulkan support as of yet. Once we've got to work on a new renderer, you'll be able to use Vulkan on your Pi4 and play the games. No idea how well they'd run though. How does GZDoom run on such a platform?

**Comment by Exarkuniv** [comment]
I have not tried GZDoom yet. As I have  lzdoom working quite well on it. I do know it's a older engine. 

But for the heck of it. I will give GZDoom a shot tomorrow and see what I might get

**Comment by Exarkuniv** [comment]
@mjr4077au so i got GZdoom to compile but same thing. needs OpenGL 3.3. 
so i will say that its a no at this time. 
im not good enough to get some of the patchs some people have made to get gzdoom to work on the current mesa drivers that are out. 
but it was fun to try
