### ISSUE TITLE
[dd7d661] [Exhumed] Ramses morph sound is garbled

### ISSUE THREAD

**Issue by sinisterseed** [coelckers/Raze#234]
Someone reported this on Discord recently, and I can confirm that the morph sound is definitely not correct for us. It sounds garbled versus GDX and vanilla.

[ramses.zip](https://github.com/coelckers/Raze/files/5678971/ramses.zip)

**Comment by coelckers** [comment]
The code for this sound is an utter mess of mucking around with the sound properties. I'm not sure it can even be done right with a proper sound mixer.

**Comment by coelckers** [comment]
Do you by any chance have a video link to the correct sound?

**Comment by coelckers** [comment]
I'm afraid, but I have no idea what to do here.  It's not the pitch that is wrong but that the sound gets mixed differently by the backends and that's outside our control.

If someone has an idea, please speak up but I am not going to switch back to the old sound code for something this inconsequential.
