### ISSUE TITLE
Some data about Linux Mint

### ISSUE THREAD

**Issue by madame-rachelle** [coelckers/Raze#238]
I'm mostly putting this here as a reference, though someone is welcome to tag this one down if they have the time.

weasel has kindly done a little bit of testing and being my guinea pig getting system-wide installs working for Raze on Mint.

`zmusic`: Currently `sudo make install` puts the libraries in `/usr/local/lib` - this is wrong, for Ubuntu and Mint. It must be moved to `/usr/lib` for those distros. I currently don't know how to detect it, however I have noticed that the environment variable `$_` does reference it.

~~`sudo make install` for Raze itself needs to stick its game data into `/opt/raze`~~ - i was wrong about this, it does not find raze.pk3 no matter what unless it is in the current folder

**Comment by mjr4077au** [comment]
Bringing in this from Discord. I think the project is fine, but rather the share directory isn't being specified when running cmake.

Below is from a PKGBUILD used to build Raze as a package for Arch Linux, which would be then installed by its package manager (please note that I'm not the maintainer of this).

```
build() {
    cd Raze
    mkdir -p build
    cmake -B build \
          -D CMAKE_BUILD_TYPE=Release \
          -D CMAKE_CXX_FLAGS="${CXXFLAGS} -ffile-prefix-map=\"$PWD\"=. -DSHARE_DIR=\\\"/usr/share/raze\\\"" \
          -D DYN_GTK=OFF \
          -D DYN_OPENAL=OFF
    make -C build
}
```

Source: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=raze-git

When installed, this is what I can see via mlocate for anything `raze`:

```
/usr/bin/raze
/usr/lib/raze
/usr/lib/raze/raze.pk3
/usr/share/raze
/usr/share/applications/raze.desktop
/usr/share/icons/hicolor/256x256/apps/raze.xpm
/usr/share/libinput/30-vendor-razer.quirks
/usr/share/licenses/raze-git
/usr/share/licenses/raze-git/buildlic.txt
/usr/share/raze/DUKE3D.GRP
/usr/share/raze/soundfonts
/usr/share/raze/soundfonts/raze.sf2
```

There's probably some packaging errors in terms of some folders being named `raze-git` but you get the idea.
