### ISSUE TITLE
[SW] menu issue

### ISSUE THREAD

**Issue by JimFlasch** [coelckers/Raze#239]
In the latest version of Raze, when playing the swc20 addon for Shadow Warrior (download from https://www.moddb.com/games/shadow-warrior/downloads/swc20/#7767581, extract the .grp file into the Raze directory and drag and drop the it onto Raze.exe to do this) only the title options menu appears onscreen when I select it from the main menu.

**Comment by mjr4077au** [comment]
Thanks for reporting this issue. Incorporating a screenshot for reference purposes. I think with "Shadow Warrior" being drawn at jumbo size, its potentially being drawn after the menu options but before the title.

I'll see what I can find but probably something Graf could work out in two seconds.

![image](https://user-images.githubusercontent.com/48643140/103436529-aa2c2500-4c70-11eb-8442-5e8c31a67ac3.png)

Interesting that it doesn't try to draw "Shadow Warrior" in the title screen though.

![image](https://user-images.githubusercontent.com/48643140/103436559-0abb6200-4c71-11eb-9ba2-8056ce1bce61.png)

**Comment by JimFlasch** [comment]
Does this mean that the menu issue has been fixed?

**Comment by sinisterseed** [comment]
> I note that this issue has been closed. Does this mean that the menu issue has been fixed?

Yes, it was addressed in https://github.com/coelckers/Raze/commit/20db6b0c784b09c8f303acde944eefce08261740 .

**Comment by coelckers** [comment]
It couldn't be "fixed", because the culprit is some bad graphic in the mod. I added a workaround check to keep it from breaking the menu.
