### ISSUE TITLE
Fog after palette emulation

### ISSUE THREAD

**Issue by markanini** [coelckers/Raze#245]
Has been discussed on the forum, adding to the tracker for good measure. Currently with palette emulation enabled fog is applied before the palette. This is true to the original but mods for other ports have swapped the order resulting in improved image quality.
![bfs_fog_render_final](https://user-images.githubusercontent.com/15148553/103441235-cd44dd80-4c4c-11eb-8ae1-13cff66080ce.jpg)
![Screenshot 2021-01-01 161733](https://user-images.githubusercontent.com/15148553/103441252-e2ba0780-4c4c-11eb-9f37-02673e84dc5a.jpg)

**Comment by coelckers** [comment]
Actually, fog is not applied "before" the palette, but is part of the palette.
I really have no idea what you want here - esepcially for a fade to black.

**Comment by markanini** [comment]
In a sense I'd like for fog to operate in a separate layer above palette emulation. To put it in a different way I'd like for palette emulation to be applied to sprites a and textures only, with the additional expected rendering working in truecolor separately before being combined, kind of like a post-shader. When I say truecolor I mean the converted color tables derived from the original palettes as used in truecolor mode.

**Comment by markanini** [comment]
In case you are wondering what I'm asking for maybe this Photoshop analogy will get the idea across. Imagine opening a cutout portrait of Duke and immediately applying a 8-bit color palette. Next you convert to 16-bit color and paint a background with a smooth gradients, and shadows with a brush. Creating a composite of 8-bit subject in a 16-bit color space.

**Comment by coelckers** [comment]
That would give you exactly the same result as the true color renderer with filtering switched off. The entire point of the palette emulation is to fade colors by using the precalculated mapping tables.

**Comment by markanini** [comment]
It looks the same as true color under the condition that you use the parametric color tables for the first part. In the case you apply the indexed color tables it gives you palette emulation, as you know, locking to 8-bit precision. If the processing precision was unlocked after the color tables it would allow for a new combination of rendering looks.

**Comment by coelckers** [comment]
I'd rather go with #134, that looks far more promising than the kind of visual hackery this would involve. It's really not that easy to do a mixed palette emulation / hardware fading renderer.
