### ISSUE TITLE
[Duke]: Replacement frame for 3DR logo not working.

### ISSUE THREAD

**Issue by mjr4077au** [coelckers/Raze#247]
When playing with the HRP, the 3DR logo replacement between the opening radioactive screen and the title screen isn't working for us.

![image](https://user-images.githubusercontent.com/48643140/103475456-6157a600-4e01-11eb-9300-d22511b1f8b4.png)

![image](https://user-images.githubusercontent.com/48643140/103475489-9cf27000-4e01-11eb-8d95-f53463c09be7.png)

**Comment by coelckers** [comment]
Do you have a link to the pack? The one I use does not replace this.

**Comment by mjr4077au** [comment]
Fire this up into TortoiseSVN 😁: https://svn.eduke32.com/listing.php?repname=duke3d_hrp

**Comment by mjr4077au** [comment]
@coelckers when you use this pack from the SVN repo, make sure you edit `duke3d_hrp.def` to exclude the Polymer .def file and include the Polymost .def file (cumbersome, I know).

https://svn.eduke32.com/filedetails.php?repname=duke3d_hrp&path=%2Fduke3d_hrp.def

```
// Extra additions to the game - High Resolution Pack

//if polymost then
//  include duke3d_hrp_polymost.def
//else
  include duke3d_hrp_polymer.def
//endif
```
