### ISSUE TITLE
[Duke]: HUD text with HRP is larger than original text and draws offscreen.

### ISSUE THREAD

**Issue by mjr4077au** [coelckers/Raze#250]
![image](https://user-images.githubusercontent.com/48643140/103476409-6587c180-4e09-11eb-80e1-1c089b34e186.png)

**Comment by coelckers** [comment]
Remember: It was you who lowered the text in the first place. The original alignment did not cut this off. ;)

**Comment by mjr4077au** [comment]
Yes yes, but I was tuning it to the original tiles 😁. Any reason why these high res tiles aren't loading in with the same dimensions as the originals?

This is DN3D 1.3D with its tiles that the HRP is trying to mimic, no issues there:

![image](https://user-images.githubusercontent.com/48643140/103477057-fd3bde80-4e0e-11eb-90a8-04780e6a91f9.png)

It'd be good to have a standardised font scaling no matter the source. We're already doing 3x fudges for DN3D 1.3D/1.5/NAM: https://github.com/coelckers/Raze/blob/b191a482d617e3e192feb84093b536ec8bd9058f/source/games/duke/src/sbar_d.cpp#L127

**Comment by coelckers** [comment]
Which is a textbook example of why fudging will always come with more problems.

**Comment by mjr4077au** [comment]
100% agree.  Whats the best way to get the fonts coming in at a consistent size no matter the origin? Would it be something in `InitFonts_d()` or am I looking in the wrong spot?

**Comment by coelckers** [comment]
Generally the way to go here is to call CheckRealHeight for a reference character in the font and use that for alignment. For hires replacements that requires a bit more work, though.

**Comment by mjr4077au** [comment]
Do the high res textures go through FGameTexture as well or are they loaded in differently? Trying to get the workflow here to see if its something I'm capable of working on.

**Comment by coelckers** [comment]
Hires textures are also FGameTextures, but for determining the real size here a bit more work is needed because a) the replacement needs to be done manually here and b) hires textures can be disabled.
