### ISSUE TITLE
[duke] revolving doors malfunction

### ISSUE THREAD

**Issue by shaggi72** [coelckers/Raze#251]
E1L2
![Duke_0001](https://user-images.githubusercontent.com/10621426/103487717-301dac80-4de6-11eb-9f9e-d23ad0801344.png)
this door turns infinitely
![Duke_0002](https://user-images.githubusercontent.com/10621426/103487735-4b88b780-4de6-11eb-9cb8-8ecf69067051.png)
this wall never turns

I did not try other maps

the problem occurs in 0.8.0 beta 69 and 80, in beta 43 and 38 it works correctly

**Comment by mjr4077au** [comment]
Thanks for the report! Surprisingly _not_ from the recent door commits but rather some seemingly unrelated changes.

Tested and confirmed fixed. If you find anything else, please let us know 😁.
