### ISSUE TITLE
[Blood] Rightward horizontal mouse movement ignored below certain velocity threshold

### ISSUE THREAD

**Issue by seascape** [coelckers/Raze#256]
One of the reasons I was so excited by Raze (fantastic project!) was it'd finally give all these long-suffering Build games first-class mouse control. I noticed one input problem that still persists in Blood, however.

In well-adjusted FPS games normally any mouse movement should result in corresponding in-game viewpoint movement. But in Raze / Blood, rightward mouse movements of insufficient velocity apparently get dropped, resulting in no in-game change of viewpoint.

This is most easily noticeable if you reduce the horizontal axis sensitivity to 1.0 or lower, but occurs at 2.0 and higher as well, which is where I first noticed it. I was trying to finely adjust my aim to point at just the leftmost pixel of a cultist hiding around a corner, but my viewpoint lurched rightward in fits and starts as I variously met the cut-off threshold and failed to meet it. I realized that if I didn't move the mouse fast enough, the input wasn't being read.

Testing suggests this phenomenon only occurs with rightward (positive?) horizontal axis input. Leftward movement and the vertical axis seem fine (they always respond). This problem also does not seem to occur in Duke, SW, or RR. 

Raze version: 0.8.1_beta, Win10

**Comment by mjr4077au** [comment]
Thanks for the report and for your kind words! This was due to a bit of original code still hanging in there to update the player's sprite angle with the angle of the player itself where all the mouse resolution was lost in the process. Redid all that and its nice now 😁.

**Comment by seascape** [comment]
Nice, thanks for the fast fix!

Just out of curiosity, will Raze ever have a unified input system that the games will share? So controls would feel identical in each. Or maybe Raze already does but also has game-specific input code too, which is where this bug lived?

**Comment by coelckers** [comment]
The input code is already shared for the most part - but since these games interpret things a bit differently it won't be possible to unify everything without altering how they originally handle. Blood in particular makes things a lot more complicated than they should.
