### ISSUE TITLE
[Duke] e1m4 "Toxic Dump", secret access problem (maybe)

### ISSUE THREAD

**Issue by d9d6ka** [coelckers/Raze#259]
Hi! Thank for the Raze, it's awesome! Using 0.8.1 beta from the release section.

I have an issue (*maybe*) with accessing a secret on e1m4 near the burning submarine. I can't get into two niches shown on the picture. I can easily do it in eDuke32, but not in Raze.

![Duke_0000](https://user-images.githubusercontent.com/29946047/105032945-863a5300-5a68-11eb-8e6c-747cceab73f3.png)
[save0000.zip](https://github.com/coelckers/Raze/files/5835749/save0000.zip)

I wanna know whether I'm just unlucky or something else. Thanks!

**Comment by coelckers** [comment]
You are right, something about the input code must have changed. Last time I tried that it still worked.

**Comment by sinisterseed** [comment]
It actually still works, but it's harder now, for some reason, I just keep failing at it.

Good to have a report for this, I was almost certain it was just me being bad lol.

**Comment by mjr4077au** [comment]
This one was fine in 0.7.3, but broken by 0.8.0. Hard to backtracer as there were STL changes in MSVC 16.8 that prevent recompilation of older commits without a fix 😢.

**Comment by coelckers** [comment]
I know, but that part is relatively easy to deal with. TArray has two operator* which are not compatible with the STL. 
You got to replace these two with

	T &operator*() const { return *m_ptr; }

on each update.
I'll do some bisecting myself later as well.

**Comment by mjr4077au** [comment]
I know it's not a big deal, just means I can't check out commits and compile is all. I'll stop sooking, shit happens 😁

**Comment by coelckers** [comment]
Like I said, you have to edit that one line each time and it'll compile again. I had to do it all the time when bisecting the repo - so we have to live with it, unfortunately.

It's still good to know that we already have some smaller range of commits in which to look further.

**Comment by coelckers** [comment]
The bug originates from 5e45f988e3d4a3afad01a801db5036fb12bb3c89
Which is unfortunately a bit much to check quickly as I am off to bed now. Have fun finding out what kind of trigonometric mess is at play here... ;)

**Comment by mjr4077au** [comment]
Thanks for backtracing :).

This one luckily wasn't too hard to identify, my git client shows the names of the functions where line changes are so it was easy to ignore all the shoot*() functions 😁

![image](https://user-images.githubusercontent.com/48643140/106254727-2fedc100-626d-11eb-9f48-a74fc098932d.png)

**Comment by coelckers** [comment]
Like I said, I was just about to go to bed so I never looked at the changes after finding the commit.

**Comment by mjr4077au** [comment]
All good man, I just really appreciate the backtrace 😁.

**Comment by coelckers** [comment]
For the next time, if you run into that compile problem, here's what to do:

tarray.cpp ~line 98:

	T& operator[](difference_type i) { return m_ptr[i]; }
	const T& operator[](difference_type i) const { return m_ptr[i]; }

change to
	T& operator[](difference_type i) const { return m_ptr[i]; }

The old code here was flat out wrong and conflicts with some of how STL uses arrays.

**Comment by mjr4077au** [comment]
I remember the commit that came in to fix it so I knew where the change was, I was more just having a whinge due to having to apply it to every checkout. Anyway I can grin and bear it, its not the first time I've had to it through out my tenure with Raze :)

**Comment by coelckers** [comment]
The only alternative would be to rewrite history, inject that fix earlier into the commit history and then stitch all the rest back on. Which isn't something to be done lightly, unfortunately.

BTW, this bug was introduced after that tarray fix, I only had to apply the fix twice on my bisecting. And it's far less of a problem, actually. If you have the file open in Visual Studio, often just performing an Undo will do it.
