### ISSUE TITLE
[REDNECK RAMPAGE] You can't dive

### ISSUE THREAD

**Issue by duke912** [coelckers/Raze#260]
When you press/hold crouch/toggle crouch the character goes underwater, but you can't dive more that that, basically stays just below the surface. Spawn to E1L2 and you can test in the beginning of the level.

Using latest beta version 126.

**Comment by coelckers** [comment]
This is something very recent. I still had a buld of 31/12 lying around where it's working properly.

**Comment by mjr4077au** [comment]
Thanks @coelckers, looks like an oversight on my part.
