### ISSUE TITLE
[f115018] [Exhumed] HUD Torch bouncing is back

### ISSUE THREAD

**Issue by sinisterseed** [coelckers/Raze#262]
It's as if the fixes got reversed.

![Exhumed_0000](https://user-images.githubusercontent.com/57503728/106352696-ce216b80-62ed-11eb-86d5-27200ae1c193.png)

**Comment by sinisterseed** [comment]
Fixed the keys, but the torch icon bouncing is still present.

Curiously, it only bounces in the status bar and partial HUD, the modern HUD is not affected. The more you know lol.

**Comment by coelckers** [comment]
I decided to completely revert MJ's change for the health display. This needs to be dealt with in the backend. All this offset fuckery in the HUD code is only bound to cause more problems.

**Comment by mjr4077au** [comment]
Agreed something better needs doing, but @sinisterseed fixed the issue with my commit in a subsequent one which is why you had the merge conflict backing my original one out.

**Comment by coelckers** [comment]
Yes, I reverted both in the process. That was intentional.
