### ISSUE TITLE
[Blood] fog not applied to voxels

### ISSUE THREAD

**Issue by Phredreeke** [coelckers/Raze#265]
As shown by BuildEnginePics [here](https://twitter.com/BuildEnginePics/status/1358747411523452930)

I tested in Raze 0.6 and there it renders correctly there so I suspect it was introduced sometime during the renderer overhaul for 0.7

**Comment by coelckers** [comment]
The image link seems to be dead.
Is this with palette emulation or true color?

**Comment by vini1264** [comment]
> The image link seems to be dead.
> Is this with palette emulation or true color?

The issue happens if palette emulation is turned on, when i turn off the graves are filtered correctly by the fog
![Blood_0001](https://user-images.githubusercontent.com/52476409/107252103-6795ff00-6a0b-11eb-808e-d4a3a3ed1cfe.png)
![Blood_0000](https://user-images.githubusercontent.com/52476409/107252133-6e247680-6a0b-11eb-8125-9f0db75606f7.png)

**Comment by sinisterseed** [comment]
I think this happened back when we updated some things during the great rework for 0.7, but either way, it is known for a good while now.

You can see the same effect with voxelized items and fog in SW too, easiest on TD's Skyline. What happens here is as follows, as Graf explained back then:

The entire renderer must be able to mix palette-emulated and regular stuff in the same scene - but currently lacks any handling for properly applying fog consistently for both. If it's fixed for the sprites, Iit later has to be redone for voxels and models too.

This doesn't really work in the other ports either, it just goes on, assuming that there is no fog in the lookup and let's the engine apply its own fog as well. Considering that they don't do fog and palette emulation right, it could technically be cheaped out for us too, but with only one fog layer, not two.

And so, it was settled that it will only be properly addressed when the time is right in the future.

**Comment by Phredreeke** [comment]
Right. NBlood has the opposite problem in that fog does not apply when palette emulation is **off**

**Comment by coelckers** [comment]
After checking this a bit closer I decided to use real shader fog unconditionally. With all the lookup madness and many tables not having a foggy equivalent or even an easy means to get one, there is simply no way to have fog work reliably when solely using the palette to apply it.

AFAIK NBlood does both - it applies the fade from the palette and real fog on top of it.
