### ISSUE TITLE
[WWIIGI] Explosives dont break wall in E1L1

### ISSUE THREAD

**Issue by markanini** [coelckers/Raze#266]
I expect the wall to lower and allow me to pass through, like in eduke32.  In Raze the wall stays up. This timestamped youtube link shows the exact spot in the map: https://youtu.be/H1b4EyhUo2A?t=42

**Comment by coelckers** [comment]
I'm having a bit of trouble finding out what chain of actions is supposed to trigger the lowering wall. Does anybody have an idea?
I can see the explosions that are supposed to appear while the wall lowers but the lowering itself does not happen. So the action itself is definitely being triggered, just not completely.
