### ISSUE TITLE
Blood: Fresh Supply no Sounds on Linux

### ISSUE THREAD

**Issue by Frenzied-Pop** [coelckers/Raze#268]
Blood: Fresh Supply on Steam changed the file sounds.rff to lowercase. It's missed during the startup file load. Blood: One Whole Unit works great!

**Comment by coelckers** [comment]
Should work now, but I cannot test myself. The way this code was structured, behavior was undefined with a high likelihood of failing the check.

**Comment by Frenzied-Pop** [comment]
Working now, thank you!
