### ISSUE TITLE
[Platoon Leader] [ba5ede6] PLATOONL.DEF: Missing con file(s).

### ISSUE THREAD

**Issue by markanini** [coelckers/Raze#270]
Downloaded the addon from here: http://dukertcm.com/knowledge-base/downloads-rtcm/wwiigi-addons/ copied the required files according to the wiki but I get the error:
![Screenshot 2021-02-26 200449](https://user-images.githubusercontent.com/15148553/109343692-0628b980-786e-11eb-8f57-3ffe88084c6e.jpg)

**Comment by mjr4077au** [comment]
It's because you have if in a subdirectory, it should be in your main WW2GI directory. Can you move it in and confirm?

**Comment by markanini** [comment]
You are right, the files were in the wrong location.

**Comment by mjr4077au** [comment]
Awesome, I'm glad it's all fixed for you 😁
