### ISSUE TITLE
Crash - Out of vertex memory

### ISSUE THREAD

**Issue by Dzierzan** [coelckers/Raze#272]
I launched DN WT with custom voxels. When I changed the map using DNSCOTTY cheat to E5L7, the game crashed.

![unknown](https://user-images.githubusercontent.com/17529329/109485521-1618e700-7a82-11eb-8600-88375217d9cf.png)

**Comment by coelckers** [comment]
What kinds of voxels are these? They must be massive to overflow the buffer.
In any case, fixing this will require replacing the voxel code with GZDoom's - the way voxels are currently being handled makes it hard to fix.

**Comment by Dzierzan** [comment]
You can get them from here https://github.com/NightFright2k19/duke3d_voxelpack

I suspect it's the Duf Beer blimp The most massive voxels in this repository are Spaceshuttle, Blimp, Radar Dish and Helicopter.

Does GZDoom code rasterize voxels?

**Comment by coelckers** [comment]
It uses the original polygonizer from Ken's old model/voxel code and just renders them through the default pipeline.
This is inefficient as hell and definitely needs to be changed. Redoing the voxel code is at the top of my to-do list anyway but I found it more important to first play through all the games and make sure they work. 
Fortunately the code from GZDoom will take care of the problems here so it won't be a complete rewrite.

**Comment by coelckers** [comment]
Voxel rendering has been transitioned to the backend's code from GZDoom which does not need to allocate from this buffer. E5L7 is working now
