### ISSUE TITLE
[Exhumed] Set inventory keys don't function

### ISSUE THREAD

**Issue by RavenMacDaddy** [coelckers/Raze#273]
I tested this with the new version (0.9.0) to see if this had been resolved, but sadly any keys set for inventory items simply doesn't work - even when the item I want to use is in the item slot.

A direct example of this is in the beginning you get the torch, I set the key to X on my keyboard, but pressing it doesn't do anything.

I didn't this as an open issue, but apologies in advance if I missed something.

Cheers

**Comment by sinisterseed** [comment]
Oof... indeed they broke, just the hotkeys, the others work.

How nice of them, they broke exactly when no-one was looking. No problem though, will be fixed 😉 .

**Comment by coelckers** [comment]
Fixed with 4b9a1465afa85ef1e96354e1adf49c95c7c09392
