### ISSUE TITLE
[Exhumed] Softlock on Kilmaatikahn Boss, the game just stops from here

### ISSUE THREAD

**Issue by vini1264** [coelckers/Raze#277]
So, i was playing Powerslave and i can't beat the Kilmaatikahn Boss and go to the last level, the game just stops when you drain all of the boss health, you can't move or do anything from here.
![Exhumed_0005](https://user-images.githubusercontent.com/52476409/110167663-6f5b8000-7dcc-11eb-92bb-4c452ba32058.png)

**Comment by coelckers** [comment]
Just tried and got no freeze. So right now I cannot say what happens here.

**Comment by sinisterseed** [comment]
In that case, this begs the question - what build were you using there, vini?

I'd check this out for myself too, but uh... I find Kilmaatikahn deeply unsettling, that boss freaks me out every single time lol.

**Comment by vini1264** [comment]
> In that case, this begs the question - what build were you using there, vini? Were you also using any mods?
> 
> I'd check this out for myself too, but uh... I find Kilmaatikahn deeply unsettling, that boss freaks me out every single time lol.

I'm using version 0.9 available here on github, no mods were applied to the game, as i'm showing in this video the game always freeze here:

https://user-images.githubusercontent.com/52476409/110245329-ffb6d380-7f38-11eb-9d32-430c4ef9f711.mp4

**Comment by sinisterseed** [comment]
Grew a second pair of balls in the meantime, to see this for myself.

I can't reproduce the freeze either, after Kilmatikaahn dies he proceeds to the second phase (head) just fine and gets killed normally. After that the exit opens and I can go to the LEV20 just fine.

@vini1264 Could you try a fresh devbuild from here and see if it happens for you there? On our end the error doesn't happen - https://devbuilds.drdteam.org/raze/

If you decide to extract on top of your existing Raze installation, make sure to delete the .INI and .log files to start brand new.

**Comment by coelckers** [comment]
Thanks for testing as well. I was holding off the new release just until I could clear this issue, so hopefully now it can be done.

**Comment by vini1264** [comment]
> Thanks for testing as well. I was holding off the new release just until I could clear this issue, so hopefully now it can be done.

I've used the latest devbuild and the freeze still happens, and i know now what's causing it. The issue relies on the save file, if you create a save game, exit the Raze application and then load from the save file you've created on the boss level, the freezing can be reproduced. So the save system breaks this boss for some reason.

**Comment by sinisterseed** [comment]
Now that, I can confirm, this was the crucial bit of into that was missing.

If I quit and go back to the save on the map, the boss breaks indeed. Game just kinda hangs but not really, I can still change settings and quit normally, but won't be able to keep playing since the game logic, for lack of a better word, is frozen in place.

Also noticed the status bar doesn't fully initialize after quitting the game and loading the save either, oof. Who doesn't love this status bar man, must be the millionth time it breaks in relation to saves:

![Exhumed_0000](https://user-images.githubusercontent.com/57503728/110367676-ae9a0300-8050-11eb-981d-540f5398722c.png)

**Comment by coelckers** [comment]
@sinisterseed  Can you please retest? I wasn't able to reliably repoduce it but one time I ran into a critical error the code did not properly guard against which ended up trashing some important data.

**Comment by sinisterseed** [comment]
It's actually worse than before now.

Instead of just the game logic freezing before she enters her second phase, Raze just hangs completely now, having to terminate the executable manually.

**Comment by coelckers** [comment]
See d7f720664a406d4da84bfb2bf3cb4d2b0daee7cf
