### ISSUE TITLE
[Blood] [57a6bfc] [Voxel enemies] Out of vertex memory

### ISSUE THREAD

**Issue by markanini** [coelckers/Raze#278]
When running this voxel pack https://www.moddb.com/mods/blood-coagulated/addons/blood-coagulated and entering the cultist room in e1m2 Raze shuts down and gives this error. "Out of vertex memory. Tried to allocate more than 2018017 vertices for a single frame"
[save0019.dsave.txt](https://github.com/coelckers/Raze/files/6095914/save0019.dsave.txt)

**Comment by coelckers** [comment]
Already fixed for the next version.
