### ISSUE TITLE
[Exhumed] [Visual bug] When loading, the HP bar is persistent from the last session

### ISSUE THREAD

**Issue by RavenMacDaddy** [coelckers/Raze#282]
Let me give an example...

Let's say I play for a while, I realize I really screwed up and so I load a save.

Well, the HP bar will show the amount that was last presented on screen, even if I load a save.

So let's say I had 1/4 of my HP left when I decided to load my save.

When it loads, it will still show that amount, even though in my loaded save my HP was a lot higher.

It's only a visual glitch however, since as soon as I take damage, the HP bar will show the actual HP amount.

I confirmed this by loading my save, taking damage for a while, then loading my save again.

My HP would be really low from the last session, then I take my first hit after loading the save and the HP bar shows me the correct HP amount again.

Thank you for your time.

**Comment by sinisterseed** [comment]
Yep, there's something going on with it again, causing the status bar elements to not get fully refreshed after loading a save.

Most easily reproduced by going to a map, saving, and quitting the game. In this case, with full health. After restarting the game and loading the save, some elements, notably the health bar, will look empty, but fix themselves after either taking damage or healing.
