### ISSUE TITLE
[Raze] Using the mouse in the menu often doesn't register where you actually clicked

### ISSUE THREAD

**Issue by RavenMacDaddy** [coelckers/Raze#283]
This is a little hard to explain, but basically, sometimes, clicking with the mouse in the menu acts as expected, it clicks where you're pointing your cursor.

However, most of the time, it will click somewhere completely different compared to where the mouse pointer is.

I'll try to get screenshots to illustrate.

![image](https://user-images.githubusercontent.com/67732686/110518432-604a3a00-810c-11eb-8284-13135cc71821.png)

Where I pointed the arrows is where my mouse pointer was positioned.

It registers it as clicking on new game when clicking there on the screen.

This is persistent whether I'm running fullscreen or windowed.

My resolution is 1440p.

I don't know if it could be something like, depending on how far off you're from the center, or depending on if your cursor internally goes outside of the game window so it will be off axis or something - just stream of consciousness. 

I put the Raze title since this is consistent when testing with both Shadow Warrior and Exhumed - all supported titles are probably affected.

**Comment by sinisterseed** [comment]
Not sure what to say about this one, just tried both windowed and fullscreen and I can't reproduce the broken behavior, for me it always opens the correct option.

Are you on the stable 0.9.0, by any chance? There were some mouse related issues in the menu that have been recently fixed, if that is the case, can you download the latest build available here and try again? If extracting over an existing installation make sure to delete the .INI and .log files to start anew: https://devbuilds.drdteam.org/raze/

**Comment by coelckers** [comment]
See #271.
It's already fixed.
