### ISSUE TITLE
[Blood] [8aa59f2] Custom voxels are randombly rotated

### ISSUE THREAD

**Issue by markanini** [coelckers/Raze#286]
Custom voxels (https://github.com/fgsfds/Blood-Voxel-Pack/releases/tag/p9) are rotated arbitrarily whereas in NBlood they line up with the wall. A good spot to see this is in E6M7.
![blud0015](https://user-images.githubusercontent.com/15148553/111236752-e6c2b800-85f3-11eb-85b1-e3801ebc13d6.png)

![Blood_0097](https://user-images.githubusercontent.com/15148553/111236120-6cddff00-85f2-11eb-9f29-269512719e3f.png)
[save0035.dsave.txt](https://github.com/coelckers/Raze/files/6145135/save0035.dsave.txt)

**Comment by coelckers** [comment]
Please update to 0.9.1. There was a bug in the maphack parser that was fixed after 0.9.0

**Comment by markanini** [comment]
I've made sure I'm using the latest build from https://devbuilds.drdteam.org/raze/
I'm suspecting now some remaining bug related to the save/load function because these rotations don't show up at the beginning of the levels.
![image](https://user-images.githubusercontent.com/15148553/111348719-bf65fc80-8680-11eb-82d3-0f721532df5b.png)

![Blood_0102](https://user-images.githubusercontent.com/15148553/111348316-5ed6bf80-8680-11eb-8689-b979666ea2f9.png)

![Blood_0100](https://user-images.githubusercontent.com/15148553/111347869-e96aef00-867f-11eb-8062-b2e0a71aac10.png)
