### ISSUE TITLE
[a12f2778] [General] Player stands up from crouched position when using the Crouch Toggle after entering/leaving the menu

### ISSUE THREAD

**Issue by sinisterseed** [coelckers/Raze#287]
This was initially assumed to be related to the input bits bug, but apparently it's not.

To reproduce, simply open and close the menu, save, or reload a save with the player crouched after getting into the crouched position by using the crouch toggle. The player will always get up.

**Comment by mjr4077au** [comment]
This fix isn't perfect. Even if I gut `InputState::ClearAllInput()` to do nothing whatsoever, when exiting the menu the player still comes up a little bit before crouching again. I need to see what's going on there.
