### ISSUE TITLE
[f4b27bbd27b0f424c92278f56c0469c47125930e] SW: Music won't play, says can't find track.

### ISSUE THREAD

**Issue by mjr4077au** [coelckers/Raze#289]
Commit before  f4b27bbd27b0f424c92278f56c0469c47125930e is ok.

**Comment by sinisterseed** [comment]
Music works just fine for me though.

**Comment by mjr4077au** [comment]
It doesn't for me for SW from Steam, the commit prior works fine for me though... Not sure what's going on here as the commit seems rather benign.

**Comment by sinisterseed** [comment]
Steam as well, and for me it works fine. Curious.

**Comment by mjr4077au** [comment]
I get log entries like:

```
player 1 of 1 (1 nodes)
Can't find CD track 2!
$whirl: Chinatown
Can't find CD track 5!
```

Commit before shows no issue for me. I'll do some investigating tomorrow as I'm exhausted right now.

**Comment by coelckers** [comment]
Can you check what paths it looks in and tell where the music really is?
I suspect it just picks the game from a different location that has no music.
