### ISSUE TITLE
Custom voxels do not rotate

### ISSUE THREAD

**Issue by Dzierzan** [coelckers/Raze#290]
I loaded custom Powerslave voxels and they do not rotate as they should be. Version 0.91.

Link:
https://www.moddb.com/mods/powerslave-voxel-pack

**Comment by coelckers** [comment]
Am I reading the code from upstream correctly that voxel rotation only was available in NBlood and PCExhumed?
I can't find any matching code in EDuke32, RedNukem or VoidSW.

Anyway, I thought it would be best to move the entire feature into the backend so that all games have access to it.

**Comment by mjr4077au** [comment]
I believe IF armour voxels rotate, so maybe there's something there?

**Comment by coelckers** [comment]
Hard to say, but maybe some script-side workaround. AFAIR the feature originates from NBlood so it's likely it didn't even exist when IF was created.

**Comment by mjr4077au** [comment]
I'm not sure myself either, I'd have to investigate to find out how that worked.
