### ISSUE TITLE
[Blood] Music in the menu

### ISSUE THREAD

**Issue by Dzierzan** [coelckers/Raze#291]
Why does Blood have music in menu when DOS Blood doesn't have menu music? Is it intentional? Version 0.91.

**Comment by sinisterseed** [comment]
DOS Blood has the attract demos playing and music plays while those do.

The simple menu is supposed to be completely silent?

**Comment by Dzierzan** [comment]
Yes, if you remove demos, menu is just silent as it should be.

**Comment by sinisterseed** [comment]
I see.

Didn't know that. Let's just say DOSBox gives me grief lol.
