### ISSUE TITLE
[BLOOD] - Insert and Delete keys to tilt your view Left/Right should be disabled

### ISSUE THREAD

**Issue by Flargee** [coelckers/Raze#294]
In both DOS and Nblood, these keys do nothing, even when their option is bound to something. However in Raze, they still work, functioning like as in Duke Nukem 3D. It's harmless gameplay-wise, but is still unintended behavior from Raze.

![Blood_0000](https://user-images.githubusercontent.com/67973708/113648093-0af54000-965a-11eb-8951-48d08c73f7b1.png)

**Comment by coelckers** [comment]
I decided to disable this for the 'classic' config but left it in for the 'modern' ones.
It was actually a deliberate decision to gave all games an orthogonal set of controlling options, even when some of these were not part of all games initially. If that bothers you, don't despair, you can easily clear the bindings in the "Customize Controls" menu.
