### ISSUE TITLE
[SW] Incorrect inventory offset

### ISSUE THREAD

**Issue by SAmik37** [coelckers/Raze#295]
In one of HUD variants there is incorrect inventory offset. Icons of items are lot higher than they should be
![SWbug](https://user-images.githubusercontent.com/82146617/114000133-e6c97700-9884-11eb-90a9-c78310516b60.png)

**Comment by coelckers** [comment]
Oops... I normally do not use that HUD so I never noticed.

**Comment by sinisterseed** [comment]
It's fun when stuff like this breaks when nobody's watching.

I checked them some time ago and they were fine at the time. Now the partial HUD broke this time, goodness.
