### ISSUE TITLE
[Duke] HQ sounds/music don't work

### ISSUE THREAD

**Issue by NineKain** [coelckers/Raze#296]
Duke3d hq music and psx sounds addons .zips dont work when put on raze/autoload

Works flawlessly on eduke32, am I doing something wrong or it doesnt work?

edit: tried this on raze.ini, still doesn't work

```
[Duke.Autoload] 

Path=$PROGDIR/autoload/duke3d_music-sc55.zip
Path=$PROGDIR/autoload/duke3d_psx.zip
```

**Comment by SAmik37** [comment]
You can try to unzip music from archive directly in autoload. At least that method work just fine in EDuke32, didn't test it in Raze

**Comment by NineKain** [comment]
> You can try to unzip music from archive directly in autoload. At least that method work just fine in EDuke32, didn't test it in Raze
> Edit: Nope. That didn't work too

Yeah, I tried various things, a shame. I'm really liking it except for this issue.

**Comment by coelckers** [comment]
Do you have a link to these files?

**Comment by NineKain** [comment]
> Do you have a link to these files?

Sure, https://hrp.duke4.net/download.php

They are "Duke 3D PSX hires sounds", and all 3 "For Duke Nukem 3D & Addons" music packs.

**Comment by coelckers** [comment]
It's partially fixed now. The lookup rules for those .def-less mods were not correct.
But to load these files you have to go to the advanced sound options and enable extended lookup for sounds and music, quit and restart. Then it should work with the coming point release.

The DukeDC music pack requires a little bit of work, though, the method it uses to replace the music never got tested at all and parts of it are actually missing.

**Comment by coelckers** [comment]
DukeDC is also fixed now. Once 1.0.1 is out it should all work.
