### ISSUE TITLE
[Vulkan] Redneck Rampage textures are messed up

### ISSUE THREAD

**Issue by SAmik37** [coelckers/Raze#297]
Find out that some of textures in Redneck Rampage are broken. But that's applies only to Vulkan render, in OpenGL everything is fine. I don't really know if this problem relate to other games too, but i only notice this when i tests Redneck Rampage. And some screenshots to demonstrate a problem
![Base Profile Screenshot 2021 04 09 - 20 05 24 47](https://user-images.githubusercontent.com/82146617/114185757-46508100-9970-11eb-8b2e-89d718a5e593.png)
![Base Profile Screenshot 2021 04 09 - 20 07 40 60](https://user-images.githubusercontent.com/82146617/114185769-494b7180-9970-11eb-8a0b-e7eeecabcc5f.png)

**Comment by coelckers** [comment]
It's already fixed for the next release: e0ee3a67017e0ca3e19203fc32fb26418c17c84f

**Comment by SAmik37** [comment]
Oh, good to know.. :)
