### ISSUE TITLE
Dos Version Hit Distance Limit

### ISSUE THREAD

**Issue by TP555** [coelckers/Raze#298]
Hi

in your current Version 1.0 , is the same problem like in BuildGDX , i know its Dos Version Releated.  !

itsn't possible to Kill Enemies from a far Distance.
Gives there a Option , to fix this ?
Or can you add a Option for both Gameplay Styles  ?

With Latest Rednukem and your Version 0.4.2 see in the Follow Video from a User works it perfect from Far Distance.
Too Self Tested with 0.4.2 and it works  !

https://www.youtube.com/watch?v=nceuHofVR2g First Hit & Kill from Far Distance  !

TP555

**Comment by coelckers** [comment]
I'll have to find out what change in RedNukem addresses this, this may take a bit of time, depending on how obvious it is.

**Comment by TP555** [comment]
Re

ok , good to know. 

Here is an Example Vid. , sometimes the Hitbox will work from far Distance. , but horrible to play , at end  omg.  !!

https://www.youtube.com/watch?v=QVF8sh4DL2c

mfg.

**Comment by coelckers** [comment]
I just added the same logic as present in EDuke32/RedNukem. It was actually more work finding out what they did than reimplementing it because the code is so different...

**Comment by sinisterseed** [comment]
Next version will be 1.4, but until then, you can also grab a devbuild and have fun with it 😉.
