### ISSUE TITLE
[Blood] [1.0.1] Music lookup not working

### ISSUE THREAD

**Issue by markanini** [coelckers/Raze#299]
![Screenshot 2021-04-09 201450](https://user-images.githubusercontent.com/15148553/114223593-4ea8bc00-9970-11eb-9fdd-1943647654ce.png)
I have FLAC fiiles in the "music" subfolder under BLOOD.RFF with file names matching corresponding midi music files. In raze options I have sett "ignore file type for music lookup" to on. No music is loaded in Raze.
![Screenshot 2021-04-09 200837](https://user-images.githubusercontent.com/15148553/114223045-a561c600-996f-11eb-8652-5900b229191f.png)

**Comment by coelckers** [comment]
ff0a3df3023c56e12a1a86ed8b6ebc5a78bf57fe 
I hope it is correct now. The logic is not pretty here...
