### ISSUE TITLE
Multi Mods Load dosn't Work or how to  ?

### ISSUE THREAD

**Issue by TP555** [coelckers/Raze#300]
Hi

How to load more than 1 Mod. ?

raze.exe upscale.pk3 psgdx.def -file psm60.pk3 -mh 1.def
It works every only the First Mod.  !

the Log Detects the Mods

 adding c:/GamesA/Power Slave/raze.pk3, 421 lumps
 adding c:/GamesA/Power Slave/STUFF.DAT, 656 lumps
 adding c:/GamesA/Power Slave/, 16 lumps
 adding upscale.pk3, 1874 lumps
 adding psm60.pk3, 15 lumps
CPU speed: 3000 MHz
CPU Vendor ID: GenuineIntel
  Name: Intel(R) Core(TM) i5-2400 CPU @ 3.10GHz
  Family 6, Model 42, Stepping 7
  Features: SSE2 SSE3 SSSE3 SSE4.1 SSE4.2 AVX HyperThreading
I_InitSound: Initializing OpenAL
  Opened device OpenAL Soft on Lautsprecher (Sound Blaster Omni Surround 5.1)
  EFX enabled
No GENMIDI lump found. OPL playback not available.
script parsing took 23.49 ms
Loading "engine/engine.def"

Loading "psgdx.def"
.....................................Loading module "1.def"

Definitions file "psgdx.def" loaded in 855.950 ms.
Loading "engine/widescreen.def"

Both Mods works fine in Single Mode

raze.exe upscale.pk3 psgdx.def
raze.exe psm60.pk3 1.def

**Comment by mjr4077au** [comment]
Using your first line above, the following should be used:

`raze.exe -file upscale.pk3 -mh psgdx.def -file psm60.pk3 -mh 1.def`

Please report back if you have any issues, but that should work for you :grin:.

**Comment by coelckers** [comment]
I think that in the future when people get more used to how to set this up for automatic loading, these question will go away by themselves once the mods adjust to the different ports out there. But right now it is to be expected that it's still not going smoothly in every case because the rules to do this right are new.
