### ISSUE TITLE
Missing Option to Set the Language

### ISSUE THREAD

**Issue by TP555** [coelckers/Raze#302]
Hi

There is no Setting aviable to set this , i know it from GzDoom where it works.
But i have seen , it must be possible too with Raze , i have found in Raze.pk3 2 Language Data Files.

But you can change the Language , Temporary Workaround.

in the ex. raze-TP555.ini search language=xxx
Finisch ex. language=de

Here are the Aviable Country Codes:

eng enc ena enz eni ens enj enb enl ent enw,cs,de,el,eo,es,esm esn esg esc esa esd esv eso esr ess esf esl esy esz esb ese esh esi esu,fi,fr,hu,it,jp,ko,nl,pl,pt,ptg,ro,ru,sr

![raze 2021-04-10 19-32-30](https://user-images.githubusercontent.com/46653671/114279568-9e9d8680-9a35-11eb-9269-d31bb5fdc3df.png)

**Comment by coelckers** [comment]
Language selection is not officially supported yet. None of the fonts has been extended with international characters and most translations are still incomplete, so it's not really functional yet.

**Comment by TP555** [comment]
Re

ah ok  !
