### ISSUE TITLE
Exhumed / PowerSlave : Return to Ruins Levels issue 

### ISSUE THREAD

**Issue by TP555** [coelckers/Raze#303]
Hi

There are some issues in Level 1 so far

https://lerppu.net/ex/ps_ex_ruinsv1.zip

https://www.youtube.com/watch?v=-aLtVVAOwIQ

**Comment by coelckers** [comment]
"This video is private"

Better post a savegame in the trouble spot - a video cannot be easily debugged.

**Comment by TP555** [comment]
Re

Video Status Fixed.

Savegame
https://workupload.com/file/mka7FUTTg7F

**Comment by coelckers** [comment]
This was introduced in d32dcd5f8eb54720719d521b44d81bfcc7a2bf61 and made worse in 7fcf1c94a1f9cc4624911b65d7e63c6f55fc95e0

That newly added code clearly does not work with slopes.

**Comment by coelckers** [comment]
I added a quick hotfix to work around the issue, but this requires deeper investigation.

**Comment by coelckers** [comment]
Sorry, but I have to reopen this. Walking up stairs is awful now. If I had to choose between this and the original, I'd rather choose the original. Just go to LEV2 and walk up. Ugh...

**Comment by coelckers** [comment]
I absolutely do not understand what kind of shit the game is doing here. When is this effect supposed to happen? I can see it when walking up and down stairs at the start of level 2, but this weird and seemingly broken flag voodoo seems to block this pan effect so in the majority of LEV1 it won't ever happen, even when jumping down a larger distance.
