### ISSUE TITLE
Graphical Corruption When Launching Blood: Cryptic Passage

### ISSUE THREAD

**Issue by V0rt3x667** [coelckers/Raze#308]
When launching Blood: Cryptic Passage from the command line graphical corruption occurs. This does not occur when using the IWAD launcher. Please see examples below and attached. OS: ArchLinux x86_64 (rolling release), Raze 1.0.1 built from source code
![No Issue](https://user-images.githubusercontent.com/25441654/114466408-5ff7ff80-9be0-11eb-958a-63f923b48e69.png)
![IWAD Launcher](https://user-images.githubusercontent.com/25441654/114466413-60909600-9be0-11eb-8881-2cc48092ee01.png)
![graphical corruption](https://user-images.githubusercontent.com/25441654/114466415-61292c80-9be0-11eb-8189-84bc0d2d3d68.png)

. All other game engines are fine including Route66.

I have tried multiple command line variations but cannot replicate the IWAD Launcher which loads Cryptic Passage correctly.

/opt/archrgs/ports/rgs-pt-raze/raze -cryptic
/opt/archrgs/ports/rgs-pt-raze/raze -iwad blood.rff -con cryptic.ini
/opt/archrgs/ports/rgs-pt-raze/raze -gamegrp blood.rff -con cryptic.ini

**Comment by coelckers** [comment]
Can you please post a complete directory listing of your Blood folder including subdirectories? The error you get looks like it cannot load the CP Art files. That'S entirely to be expected for the second and third command line, but -cryptic should work.
So I need to see what files you got.

**Comment by V0rt3x667** [comment]
Please see the below. Thanks.
![Cryptic Files](https://user-images.githubusercontent.com/25441654/114468879-0e517400-9be4-11eb-84c2-bb6de4bb8b85.png)

**Comment by arrowgent** [comment]
CPART07.AR_
CPART15.AR_

are the two files that crypticpassage requires

mine are Capital Letters, from one whole unit blood
