### ISSUE TITLE
[raze v1.01] chat: T message

### ISSUE THREAD

**Issue by arrowgent** [coelckers/Raze#311]
```
Unknown command "+Send_Message"
Unknown command "-Send_Message"

```
when pressing T
no chat box appears
effects all games: duke3d, sw, blood, etc

some features such as "rate" when typed in chat to enable FPS and other cheat codes used T to enter the code
although obviously we have ~ console now (vid_fps & r_showfps)
and no multiplayer feature, which would have been used for Chat:T

options menu: chat=T becomes redundant, if it doesnt work

**Comment by coelckers** [comment]
'T' is bound to chat in all games. Note that the text is shown at the bottom of the screen, not the top!
You can enter cheats there but need to prefix them with # to evade the internal logic of the chat editor.

**Comment by arrowgent** [comment]
```
Unknown command "+Send_Message"
Unknown command "-Send_Message"
```

is not the only message that appears to have output errors
buttons F, i, and K also

```
Unknown command "+Toggle_Crosshair"
Unknown command "-Toggle_Crosshair"
Unknown command "+Map_Follow_Mode"
Unknown command "-Map_Follow_Mode"
Unknown command "+See_Coop_View"
Unknown command "-See_Coop_View"
```
among others
```
Unknown command "+ProximityBombs"
Unknown command "-ProximityBombs"
Unknown command "+See_Coop_View"
Unknown command "-See_Coop_View"
Unknown command "+Jetpack"
Unknown command "-Jetpack"
Unknown command "+BeastVision"
Unknown command "-BeastVision"
Unknown command "+CrystalBall"
Unknown command "-CrystalBall"
```


however it may be true, im using an older raze.ini, these features might have been changed or disabled
but i can rebind them again in options and it has the same error.

in the end, it should be recommended to create a NEW raze.ini when upgrading new version releases
this becomes an issue for people that simply extract a new version
especially linux, i compiled my own and the /.config/raze/raze.ini does not get updated

also: some screenshots.
https://i.imgur.com/D6paGXC.png
https://i.imgur.com/iSwz0Er.png
https://i.imgur.com/MJ3UCak.png
https://i.imgur.com/25X44Mm.png

**Comment by sinisterseed** [comment]
> in the end, it should be recommended to create a NEW raze.ini when upgrading new version releases
> this becomes an issue for people that simply extract a new version
> especially linux, i compiled my own and the /.config/raze/raze.ini does not get updated
> 
> also: some screenshots.
> https://i.imgur.com/D6paGXC.png
> https://i.imgur.com/iSwz0Er.png
> https://i.imgur.com/MJ3UCak.png
> https://i.imgur.com/25X44Mm.png

Essentially, this is one of the reasons why I always recommend starting fresh when upgrading to a new version/recompiling, as old .INIs can lead to all sorts of weird issues, especially when a lot of things change.

**Comment by coelckers** [comment]
When did you update last time? These changes happened between 0.6 and 0.7, more than half a year ago when the entire input system was migrated to GZDoom's.

**Comment by arrowgent** [comment]
indeed my raze ini was created with v0.6 but i used v0.7 and v0.8x since then

its not a big issue as noted: recommending creating a fresh install of the game
but on linux this wouldnt happen due to how the .config & ini are stored and created
also because the ini was from Alpha/Beta to v1.x this is acceptable

i never had these issues with gzdoom, and i get that from drdteam's ppa (debian)
deb https://debian.drdteam.org/ stable multiverse
although these are from v4.x to v4.5.0

**Comment by arrowgent** [comment]
checked other weapon/item shortcuts
no issue appeared with current menudef
https://github.com/coelckers/Raze/issues/311#issuecomment-818880067
