### ISSUE TITLE
Script error, "(path-to-game)/:textures" line 1: Texture definition expected, found 'LZ412'

### ISSUE THREAD

**Issue by Cianez** [coelckers/Raze#315]
As the title says. I have no idea what this is. I'm using the latest Raze 1.0.1. on Redneck Rampage

![immagine](https://user-images.githubusercontent.com/46445923/114753176-71afe300-9d57-11eb-8d66-64e639086af0.png)

I've also tried disabling the autoload folder but to no avail.

**Comment by sinisterseed** [comment]
Are you using mods by any chance?

**Comment by Cianez** [comment]
> 
> 
> Are you using mods by any chance?

I have the upscale pack and a bunch of other things I made myself both inside the autoload folder and outside (such as the 8 track player's songs in .OGG). Rednukem and BuildGDX works just fine, and Raze worked just fine as well before I updated it.

**Comment by sinisterseed** [comment]
Can you please share those mods so we fan investigate?

The startup message alone is nowhere near enough.

**Comment by coelckers** [comment]
What's that "textures" file?

**Comment by Cianez** [comment]
Ah, so it's a file. I believe it's this?

![immagine](https://user-images.githubusercontent.com/46445923/114765106-0e2cb200-9d65-11eb-9772-0096213b34e2.png)

I've tried to add an extension to it, no this error is popping up:

![immagine](https://user-images.githubusercontent.com/46445923/114765237-33212500-9d65-11eb-90bd-58603b156912.png)

**Comment by Cianez** [comment]
Ok so, it started right when I removed these 4 files:

![immagine](https://user-images.githubusercontent.com/46445923/114766153-5a2c2680-9d66-11eb-8b64-9122b5683174.png)

I have no idea why they're there nor what created them. Maybe you want to investigate those files @coelckers and maybe make Raze not parse them to avoid any startup problem?

**Comment by coelckers** [comment]
Those are texture cache files from EDuke32 and its child ports.
The actual problem is that "textures" is a reserved name for Raze - like GZDoom it is used to define textures, of course it cannot do much with those cache files that EDuke32 in its infinite wisdom puts into the game folder instead of some config folder.

**Comment by Cianez** [comment]
Yeah you're probably right. In fact I have all 3 source ports in the same folder.
So you'd suggest to copy the RR installation and use Raze on that instead to avoid being "contaminated" by the other ports?

**Comment by coelckers** [comment]
Addressed in f6c4c19b022a50328e7315888e3a64b0cc3021d8
