### ISSUE TITLE
[Exhumed] Game locks on map screen when using the map CVAR to warp through levels

### ISSUE THREAD

**Issue by vini1264** [coelckers/Raze#316]
Hi, i tried to use the map console command to warp through levels in Powerslave, but the game always locks on map screen and i can't do anything. I'm using the latest Git build of Raze.

https://user-images.githubusercontent.com/52476409/114894364-91d5b580-9ddc-11eb-86da-5bdbd578b572.mp4

.

**Comment by coelckers** [comment]
fixed in 9c5f3f3673712c8a52877ea37ef8e4fa375a6b4f and 61a6321cd64dcd510e2e656c3eee99d3db9a55ee.
