### ISSUE TITLE
[Duke3D] Voxel pack/HRP maphacks not working

### ISSUE THREAD

**Issue by NightFright2k19** [coelckers/Raze#317]
Currently Raze does not seem to really use any maphacks from the Voxel Pack (and therefore the HRP since they are almost identical), showing in E1L1 in several spots already:

- The "Cinema" sign next to the movie theater entrance does not look right
- Switches that are supposed to be hidden (e.g. the one at the register in the cinema foyer) are visible
- Pickups like the rocket launcher under the "Innocent?" sign on the streets are not properly aligned
(...)

My suspicion is that Raze does not recognize the map hashes used in the EDuke32 maphacks. They are needed because sometimes there are different versions of the same map which require different maphacks (e.g. Atomic vs World Tour).

The format is like this (example: E1L1)
```
mapinfo 
{
  maptitle "Hollywood Holocaust"
  // author "Allen H. Blum III"
  mapfile  "E1L1.map"
  mapmd4   944032d239a314088ec7fdd771910362 // 1996-04-19 (1.3D GRP)
  mhkfile  "maphacks/3drealms/E1L1_13d.mhk"
}

mapinfo 
{
  maptitle "Hollywood Holocaust"
  // author "Allen H. Blum III"
  mapfile  "E1L1.map"
  mapmd4   a1ce0037911b2625781a2623588c8b90 // 1996-12-11 (Atomic GRP)
  mhkfile  "maphacks/3drealms/E1L1.mhk"
}
```

**Comment by Dzierzan** [comment]
Hmmm... FYI I tested Blood Voxel Pack and it did detect maphacks just fine.

Here's a screenshot where you can see the voxel on the right rotated:

![image](https://user-images.githubusercontent.com/17529329/115076063-53371c80-9efc-11eb-88db-a8dc8754f78c.png)

And here's from DN: WT

![image](https://user-images.githubusercontent.com/17529329/115076274-a27d4d00-9efc-11eb-95a6-b5abe61a6ea4.png)

And from DN: 3D

![image](https://user-images.githubusercontent.com/17529329/115076394-ca6cb080-9efc-11eb-8c42-457c5efff674.png)

Looks as intended.

**Comment by coelckers** [comment]
Looks correct to me in all described cases.
The map hack definitely gets used as it looks totally different when I rename it.

**Comment by NightFright2k19** [comment]
Retroactively I found out it was my fault since I forgot to include an important .def file. So yeah, it was not a problem with Raze.
