### ISSUE TITLE
[Duke] Switch doesn't work in E4L10 (Alien Queen)

### ISSUE THREAD

**Issue by NineKain** [coelckers/Raze#318]
![Captura](https://user-images.githubusercontent.com/72826232/115075225-0e5eb600-9efb-11eb-930e-7db14c1444c7.PNG)

The one on the right, no matter how hard I try, it's impossible to push.

[save0000.zip](https://github.com/coelckers/Raze/files/6327507/save0000.zip)

save for reference

**Comment by coelckers** [comment]
Fixed in 42b87362ee0b485efe657e7b701f883d30e4cb67
