### ISSUE TITLE
[Blood] Broken Secret Counts at Level Stats screen

### ISSUE THREAD

**Issue by valter12437** [coelckers/Raze#320]
I don't know if it's even possible, and I know it's like this even in the DOS version, but, are there any plans on fixing the broken secret counts?

**Comment by NineKain** [comment]
I'm not an expert or anything, but I suppose you have to edit the maps themselves, and I don't know if that can be done with a sourceport.

**Comment by sinisterseed** [comment]
We have actually done some improvements here, mainly regarding super secrets to avoid silly counts such as "12/11".

Is there something else you mean?

**Comment by valter12437** [comment]
In E3M1, the count was still "10/9", so I imagine the Super Secret got counted. I have not played through the whole game in the new version yet, but if find more examples I will let you guys know.

**Comment by valter12437** [comment]
Okay, so in-game the secret count increases to match the number of secrets found. I meant the Level Stats screen, after you finish the level. I changed the issue title accordingly.

**Comment by valter12437** [comment]
https://user-images.githubusercontent.com/82282361/115142593-0e54d800-a019-11eb-8617-676904be2400.mp4

**Comment by coelckers** [comment]
Blood's secret management is totally broken. Instead of actually counting the secrets (which it apparently cannot do because they are stored in some event list) it relies on a counter specified by the map - if that is off, the display is off.  It's just one of those much too frequent stupidities in this game.

So far I haven't really understood how to retrieve this data from the loaded map.

**Comment by coelckers** [comment]
Well, sorry, but there's nothing I can do. The way Blood handles its secrets makes it totally impossible to count them properly. The game utterly relies on the total count being correct and puts all responsibility in the mapper's hands - and we all know that even the stock levels didn't have it right.

This is yet another of these cases where the Blood devs eschewed a simple and straightforward approach for a ridiculously overcomplicated mess.
