### ISSUE TITLE
[Shadow Warrior] Black item pick up-or and damage screen flashes as of 1.0.2

### ISSUE THREAD

**Issue by valter12437** [coelckers/Raze#322]
The screen flashes black (or rather, darkens) when items are picked up or damage is taken. It worked correctly in 1.0.1.

**Comment by NineKain** [comment]
Exaclty the same in Duke Nukem

**Comment by sinisterseed** [comment]
The screen flash bug has been fixed already, actually - https://forum.zdoom.org/viewtopic.php?f=341&t=72026

It was an uninitialized variable. It will work correctly once more in the next daily build/stable version.
