### ISSUE TITLE
[General] "startgame" CCMD may have broken

### ISSUE THREAD

**Issue by sinisterseed** [coelckers/Raze#323]
I forgot I noticed this recently.

It seems the startgame command has broken, at the very least in Blood. I wanted to levelwarp a few times from the menu but forgot that doesn't work, so I tried "startgame" instead.

Game returns an "unknown command" error, however.

**Comment by coelckers** [comment]
This command never existed. The resetting variant to levelwarp is called levelstart.

**Comment by sinisterseed** [comment]
> This command never existed. The resetting variant to levelwarp is called levelstart.

Ah, yes indeed.

I confused things lol. I was thinking of levelstart. Though I'd say the message should be changed to reflect this, as it recommends a command that doesn't exist.
