### ISSUE TITLE
[Exhumed] Artifacts when rendering with Vulkan

### ISSUE THREAD

**Issue by jrugia** [coelckers/Raze#324]
Running Exhumed through Vulkan produces a lot of artifacts. Issue is not present when using OpenGL.

System:
OS: Linux
GPU: AMD RX 6800
MESA: 21.0.2 / LLVM12
RAZE VERSIONS TESTED: 1.0.1 and 1.0.2

I tried a few games using GZDoom, namely All the Doom's and Heretic/Hexen and the issue is not present.

![2](https://user-images.githubusercontent.com/13750621/115160450-74cd0b00-a098-11eb-9e72-0d84bd35f2a5.jpg)
![1](https://user-images.githubusercontent.com/13750621/115160451-7696ce80-a098-11eb-9862-30d3dff94b38.jpg)

**Comment by NineKain** [comment]
Weird, doesn't happen to me, maybie a driver issue?

**Comment by jrugia** [comment]
Apparently running the game with RADV_DEBUG=nodcc fixes it.

![3](https://user-images.githubusercontent.com/13750621/115161233-c6779480-a09c-11eb-8061-db20c6cf3a43.jpg)

@NineKain  Which GPU are you running?

I'll leave ticket open for now, will test tomorrow on RX 5500 XT.

**Comment by NineKain** [comment]
AMD R7 370, FX-4300 cpu

**Comment by sinisterseed** [comment]
This seems like something specific to the configuration, no issues here in Windows with NVIDIA GPU.

I find it so curious how many anomalies AMD GPUs seem to be experiencing lately.

**Comment by coelckers** [comment]
I think it is related to this: https://forum.zdoom.org/viewtopic.php?f=340&t=71958
But yeah, I also wonder what's up with AMD. They must do something very strange with the textures.
Here's the interesting thing: Apparently it does work properly with the new render code as somebody told me. There must be something off with how Polymost sets up the screen that this garbage happens.

**Comment by sinisterseed** [comment]
Not just that, but it looks like running with "RADV_DEBUG=nodcc" fixes the mess.

**Comment by jrugia** [comment]
Can confirm the issue is also present with RX 5500 XT (RDNA 1) and "RADV_DEBUG=nodcc" fixes it as well.

I tried GZDoom (4.5.0) and the issue is not present with any of the Doom/Heretic/Hexen games.

**Comment by arrowgent** [comment]
yikes.  AMD vulkan bug?
linux & nvidia, i had no issues using vulkan

**Comment by sinisterseed** [comment]
May also be some sort of compile error, as apparently using "RADV_DEBUG=nodcc" fixes the corruption.

**Comment by Cacodemon345** [comment]
This also affects Duke3D. And if you set the multisample/MSAA level to high values the screen with start glitching out and will glitch even further if you either look around or move.

First image is without MSAA, second one is with MSAA set to high values.
![image](https://user-images.githubusercontent.com/38420290/117188887-5f2d4480-adff-11eb-98b7-e41b3ff323c4.png)
![image](https://user-images.githubusercontent.com/38420290/117190236-fe067080-ae00-11eb-9df5-7be305d08f8b.png)

**Comment by coelckers** [comment]
Does 7b45144023562118b54e378392b2f6c6d7ce021d resolve these issues?

**Comment by jrugia** [comment]
@coelckers I just compiled the engine up to commit 79823b4 and removed the 'nodcc' workaround, can confirm the artifacts issue is fixed for me in Exhumed. I've also tried all MSAA settings and the game kept working fine.

**Comment by sinisterseed** [comment]
In that case, this case can probably be closed then.
