### ISSUE TITLE
[DN3D] [New renderer preview] translucent sector boundry too opaque

### ISSUE THREAD

**Issue by markanini** [coelckers/Raze#327]
This lightbeam in the first level of episode 5 is less translucent than in the old renderer.
![Duke_0000](https://user-images.githubusercontent.com/15148553/115788551-06ec5080-a3c4-11eb-9ec7-960f61fea839.png)
![Duke_0001](https://user-images.githubusercontent.com/15148553/115788558-081d7d80-a3c4-11eb-94b2-55f05f3c1e7f.png)

**Comment by markanini** [comment]
![Duke_0002](https://user-images.githubusercontent.com/15148553/115788780-621e4300-a3c4-11eb-9c17-e0ba1106fb17.png)
![Duke_0003](https://user-images.githubusercontent.com/15148553/115788782-634f7000-a3c4-11eb-955d-1a6e640bc840.png)

**Comment by coelckers** [comment]
Fixed in c05df44ad416750e2216ca667b46c197ca861af0
