### ISSUE TITLE
[General] Vulkan causes total freeze on linux nvidia

### ISSUE THREAD

**Issue by cncz42** [coelckers/Raze#328]
Compiled this sourceport from source on linux (specifically from [this](https://aur.archlinux.org/packages/raze) aur package) everything works fine unless you switch to vulkan, for whatever reason shortly after starting the game it will completely freeze the system (oddly audio still goes through) and I need to force power off, normally I would track this to some internal hardware issue but gzdoom vulkan and every other vulkan game doesn't seem to have this issue. Unfortunately due to the total nature of the crash any console log I try to get ends up corrupted or missing, so I'm kind of out of luck for finding debugging info. Any ideas on getting better debug info or replicating the problem?

**Comment by alexey-lysiuk** [comment]
Please post system spec and version of graphics driver.

If it’s in fullscreen, try windowed mode.

**Comment by cncz42** [comment]
Manjaro with kernel 5.11, ryzen 9 3900x with an rtxs 2080ti with driver version 460.67. It doesn't seem to freeze in windowed mode, but what would be causing it to freeze in fullscreen?

**Comment by alexey-lysiuk** [comment]
Do you have vsync enabled in Raze? Is it enabled in GZDoom?

**Comment by cncz42** [comment]
Vsync is disabled in raze and gzdoom, however I do play with a capped framerate at 120 with gsync on both

**Comment by cncz42** [comment]
After some testing it seems that g sync + the fps cap is causing the freeze on vulkan (not the fps cap on its own, nor g sync with no fps limit)

**Comment by cncz42** [comment]
A quick update, also seems to crash on arch linux with the same hardware (no suprise really), it also seems to very rarely happen in gzdoom at level end screens

**Comment by cncz42** [comment]
Update: pinned this problem down to the kwin compositor on the system's end, maybe the vsync is messed up or something

**Comment by cncz42** [comment]
FINAL UPDATE: I can confirm that changing gl_ssao=0 to gl_ssao=3 in raze.ini fixes the issue, I have no idea what in the name of computer hell kde plasma, g sync, no ssao, vulkan, and doom end screens have in common but it fixes it

**Comment by cncz42** [comment]
vid_activeinbackground=true also seems to fix this
