### ISSUE TITLE
Possible Viewpoints buffer memory leak

### ISSUE THREAD

**Issue by emileb** [coelckers/Raze#329]
I may be missing something in my hacked build, but I can't see where:

screen->mViewpoints->Clear()
or
screen->mLights->Clear();

..are called during a game frame, for me it is leading to continually growing Viewpoints buffer size.

**Comment by sinisterseed** [comment]
If you've made changes to the code, we need to know what you did, as this doesn't help us much...

**Comment by emileb** [comment]
Ok this fixes it for me. 
https://github.com/emileb/Raze/commit/cef69fd7077485017b477813250d94153d992d63

But I do not know if this is the correct place to fix it, otherwise I would have done a pull req.

**Comment by coelckers** [comment]
Please make a PR from that commit.
