### ISSUE TITLE
[Since the screenjob rework] Fade in effect seems to be gone

### ISSUE THREAD

**Issue by sinisterseed** [coelckers/Raze#330]
Ever since the rework of the screenjobs to fix some engine instability, it seems like the fade in effect has broken.

In Blood, when the menu background shows up following the intros, it's just an abrupt transition to it now instead of nicely fading in, both GL and Vulkan. 

And in Exhumed, when starting a new game, the fade in effect when the world map opens is also gone (but curiously, the fade **_out_** still works).

**Comment by sinisterseed** [comment]
Same for the 3DR logo in Duke (all versions).

**Comment by coelckers** [comment]
https://github.com/coelckers/Raze/issues/345
