### ISSUE TITLE
[Duke/RR]: Unexplained and unnecessary automatic weapon switching

### ISSUE THREAD

**Issue by RazTK** [coelckers/Raze#333]
1. Load this save game (for Duke it out in D.C.): https://mir.cr/0QTGEETH
2. Switch to any weapon and shoot.
3. The game will switch back to the Shotgun for some reason.

Just as a BTW remark, this was also an issue in BuildGDX (in both Duke and RR) that was fixed, so it may also affect Redneck Rampage but I have yet to play it in Raze to be 100% sure.

**Comment by coelckers** [comment]
Unless you can point me to the relevant commit in GDX I see no change finding the cause in that heap of utter mess that is Duke's weapon code.

**Comment by sinisterseed** [comment]
I'm curious how this was also achieved.

Just tried to recreate this, but can't, my weapons don't autoswitch weirdly.

**Comment by RazTK** [comment]
> Unless you can point me to the relevant commit in GDX I see no chance finding the cause in that heap of utter mess that is Duke's weapon code.

Well, I sent M210 a DM, asking if he can point me to the relevant commit. I'm also going through the commits [https://gitlab.com/m210/BuildGDX/-/commits/develop](url) hoping to find it. While I'm doing that, here's what he had to say about it back then: 

> Hi. I checked your saves. So, the wantweaponfire is a couser. This variable is'nt equals -1, thus weapon is changing
> Usually it's happaning when weapon don't have ammo, then wantweaponfire is changing to other weapon
> I still don't know why this variable didn't reset after switching
> or something like that
> But now we know where to see

> I'm curious how this was also achieved.
> 
> Just tried to recreate this, but can't, my weapons don't autoswitch weirdly.

I don't know exactly how to reproduce it. I wish I knew. I was just playing normally, it happened few times during each map.

**Comment by coelckers** [comment]
The saves do not help me. Duke's code is so utterly spaghetti that I simply cannot find where the weapon switch it triggered. None of the obvious places gets called.

Regarding GDX, the game modules are in separate repos, the one you want to look at is DukeGDX.

**Comment by RazTK** [comment]
I think it's this: https://gitlab.com/m210/RedneckGDX/-/commit/5da7cfdd68ee2fd340f3dd9a98d2b9bff74e7814

**Comment by coelckers** [comment]
No, that wasn't it. Commenting out that piece of code makes no difference.
