### ISSUE TITLE
[scriptable_cutscenes] Can't generate CMake project files

### ISSUE THREAD

**Issue by sinisterseed** [coelckers/Raze#335]
I'm on CMake 3.20.1 here, was about to take a look at the scriptable_cutscenes branch but it seems I can't even generate the project files due to an error while generating:

> CMake Error at source/CMakeLists.txt:1297 (add_executable):
>   Cannot find source file:
> 
>     games/sw/src/2d.cpp
> 
>   Tried extensions .c .C .c++ .cc .cpp .cxx .cu .mpp .m .M .mm .h .hh .h++
>   .hm .hpp .hxx .in .txx .f .F .for .f77 .f90 .f95 .f03 .ispc
> 
> 
> CMake Error at source/CMakeLists.txt:1297 (add_executable):
>   No SOURCES given to target: raze

**Comment by coelckers** [comment]
Just remove that line from the file and compile again.

**Comment by sinisterseed** [comment]
Yup, that fixes it, took so long because I wanted to check that first.

Also pushed the fix.
