### ISSUE TITLE
[scriptable_cutscenes] [Duke] Starting E4 works, but briefly opens the console, returning an error after the intro

### ISSUE THREAD

**Issue by sinisterseed** [coelckers/Raze#340]
> VM execution aborted: tried to read from address zero.
> Called from ScreenJobRunner.DisplayFrame at raze.pk3:zscript/screenjob.zs, line 405
> Called from ScreenJobRunner.RunFrame at raze.pk3:zscript/screenjob.zs, line 509
> E4L1: It's Impossible

**Comment by coelckers** [comment]
fixed in 51aeb6dd39a852118067586d8f07def22852c59c
