### ISSUE TITLE
[scriptable_cutscenes] [Blood] End level screams bleed into cutscenes

### ISSUE THREAD

**Issue by sinisterseed** [coelckers/Raze#341]
Their sound doesn't stop when a cutscene starts playing, this is most obvious when going to E4M8.

Simply start on the chapter and warp to it, after the end level screen disappears, the screams will continue to play for a while.

**Comment by coelckers** [comment]
fixed in 512f1d852bed6c2af5c1a0e08eb2e45ce10c1cd4
