### ISSUE TITLE
[Since forever] [RRRA] Skipping the first intro video skips everything

### ISSUE THREAD

**Issue by sinisterseed** [coelckers/Raze#344]
I brought this up some time ago but no idea what happened with it.

Skipping the intro video in RRRA is not supposed to skip everything at once, making the biker video not play at all. This is different from both GDX and Rednukem.

**Comment by coelckers** [comment]
You are mistaken. In GDX the video is totally broken and skipping it skips everything and I never checked RedNukem.
But this is only ONE video, not three, you cannot simply fast forward it to a given position,

**Comment by sinisterseed** [comment]
Hm, weird.

Gonna have to recheck what Rednukem did then, I wonder if memory is failing me again here.
