### ISSUE TITLE
[scripted_cutscenes] [Duke] Levelwarping causes massive console flood

### ISSUE THREAD

**Issue by sinisterseed** [coelckers/Raze#346]
Forgot this one.

Basically the title, it just leads to console spamming with this stuff:

> E3L1: Raw Meat
> ]levelwarp 4 3
> $PRESSKEY: shade = 7
> $PRESSKEY: shade = 6
> $PRESSKEY: shade = 6
> $PRESSKEY: shade = 6
> $PRESSKEY: shade = 6
> $PRESSKEY: shade = 5
> $PRESSKEY: shade = 5
> $PRESSKEY: shade = 5
> $PRESSKEY: shade = 5
> $PRESSKEY: shade = 4
> $PRESSKEY: shade = 4
> $PRESSKEY: shade = 4
> $PRESSKEY: shade = 4
> $PRESSKEY: shade = 3
> $PRESSKEY: shade = 3
> $PRESSKEY: shade = 3
> $PRESSKEY: shade = 3
> $PRESSKEY: shade = 2
> $PRESSKEY: shade = 2
> $PRESSKEY: shade = 2
> $PRESSKEY: shade = 2
> $PRESSKEY: shade = 2
> $PRESSKEY: shade = 2
> $PRESSKEY: shade = 1
> $PRESSKEY: shade = 1
> $PRESSKEY: shade = 1
> $PRESSKEY: shade = 1
> $PRESSKEY: shade = 1
> $PRESSKEY: shade = 1
> $PRESSKEY: shade = 1
> $PRESSKEY: shade = 1
> $PRESSKEY: shade = 1
> $PRESSKEY: shade = 1
> $PRESSKEY: shade = 1
> $PRESSKEY: shade = 1
> $PRESSKEY: shade = 2
> $PRESSKEY: shade = 2
> $PRESSKEY: shade = 2
> $PRESSKEY: shade = 2
> $PRESSKEY: shade = 2
> $PRESSKEY: shade = 2
> $PRESSKEY: shade = 3
> $PRESSKEY: shade = 3
> $PRESSKEY: shade = 3
> $PRESSKEY: shade = 3
> $PRESSKEY: shade = 4
> $PRESSKEY: shade = 4
> $PRESSKEY: shade = 4
> $PRESSKEY: shade = 4
> $PRESSKEY: shade = 5
> $PRESSKEY: shade = 5
> $PRESSKEY: shade = 5
> $PRESSKEY: shade = 5
> $PRESSKEY: shade = 6
> $PRESSKEY: shade = 6
> $PRESSKEY: shade = 6
> $PRESSKEY: shade = 6
> $PRESSKEY: shade = 7
> $PRESSKEY: shade = 7
> $PRESSKEY: shade = 8
> $PRESSKEY: shade = 8
> $PRESSKEY: shade = 8
> $PRESSKEY: shade = 8
> $PRESSKEY: shade = 9
> $PRESSKEY: shade = 9
> $PRESSKEY: shade = 9
> $PRESSKEY: shade = 9
> $PRESSKEY: shade = 10
> $PRESSKEY: shade = 10
> $PRESSKEY: shade = 10
> $PRESSKEY: shade = 10
> $PRESSKEY: shade = 11
> $PRESSKEY: shade = 11
> $PRESSKEY: shade = 11
> $PRESSKEY: shade = 11
> $PRESSKEY: shade = 12
> $PRESSKEY: shade = 12
> $PRESSKEY: shade = 12
> $PRESSKEY: shade = 12
> $PRESSKEY: shade = 13
> $PRESSKEY: shade = 13
> $PRESSKEY: shade = 13
> $PRESSKEY: shade = 13
> $PRESSKEY: shade = 13
> $PRESSKEY: shade = 13
> $PRESSKEY: shade = 14
> $PRESSKEY: shade = 14
> $PRESSKEY: shade = 14
> $PRESSKEY: shade = 14
> $PRESSKEY: shade = 14
> $PRESSKEY: shade = 14
> $PRESSKEY: shade = 15
> $PRESSKEY: shade = 15
> $PRESSKEY: shade = 15
> $PRESSKEY: shade = 15
> $PRESSKEY: shade = 15
> $PRESSKEY: shade = 15
> $PRESSKEY: shade = 15
> $PRESSKEY: shade = 15
> $PRESSKEY: shade = 15
> $PRESSKEY: shade = 15
> $PRESSKEY: shade = 15
> $PRESSKEY: shade = 15
> $PRESSKEY: shade = 15
> $PRESSKEY: shade = 15
> $PRESSKEY: shade = 15
> $PRESSKEY: shade = 15
> $PRESSKEY: shade = 15
> $PRESSKEY: shade = 15
> $PRESSKEY: shade = 15
> $PRESSKEY: shade = 15
> $PRESSKEY: shade = 15
> $PRESSKEY: shade = 15
> $PRESSKEY: shade = 15
> $PRESSKEY: shade = 15
> $PRESSKEY: shade = 15
> $PRESSKEY: shade = 15
> $PRESSKEY: shade = 15
> $PRESSKEY: shade = 15
> $PRESSKEY: shade = 14
> $PRESSKEY: shade = 14
> $PRESSKEY: shade = 14
> $PRESSKEY: shade = 14
> $PRESSKEY: shade = 14
> $PRESSKEY: shade = 14
> $PRESSKEY: shade = 13
> $PRESSKEY: shade = 13
> $PRESSKEY: shade = 13
> $PRESSKEY: shade = 13
> $PRESSKEY: shade = 13
> $PRESSKEY: shade = 13
> $PRESSKEY: shade = 12
> $PRESSKEY: shade = 12
> $PRESSKEY: shade = 12
> $PRESSKEY: shade = 12
> $PRESSKEY: shade = 11
> $PRESSKEY: shade = 11
> $PRESSKEY: shade = 11
> $PRESSKEY: shade = 11
> $PRESSKEY: shade = 10
> $PRESSKEY: shade = 10
> $PRESSKEY: shade = 10
> $PRESSKEY: shade = 10
> $PRESSKEY: shade = 9
> $PRESSKEY: shade = 9
> $PRESSKEY: shade = 9
> $PRESSKEY: shade = 9
> $PRESSKEY: shade = 8
> $PRESSKEY: shade = 8
> $PRESSKEY: shade = 8
> $PRESSKEY: shade = 8
> $PRESSKEY: shade = 7
> $PRESSKEY: shade = 7
> $PRESSKEY: shade = 6
> $PRESSKEY: shade = 6
> $PRESSKEY: shade = 6
> $PRESSKEY: shade = 6
> $PRESSKEY: shade = 5
> $PRESSKEY: shade = 5
> $PRESSKEY: shade = 5
> $PRESSKEY: shade = 5
> $PRESSKEY: shade = 4
> $PRESSKEY: shade = 4
> $PRESSKEY: shade = 4
> $PRESSKEY: shade = 4
> $PRESSKEY: shade = 3
> $PRESSKEY: shade = 3
> $PRESSKEY: shade = 3
> $PRESSKEY: shade = 3
> $PRESSKEY: shade = 2
> $PRESSKEY: shade = 2
> $PRESSKEY: shade = 2
> $PRESSKEY: shade = 2
> $PRESSKEY: shade = 2
> $PRESSKEY: shade = 2
> $PRESSKEY: shade = 1
> $PRESSKEY: shade = 1
> $PRESSKEY: shade = 1
> $PRESSKEY: shade = 1
> $PRESSKEY: shade = 1
> $PRESSKEY: shade = 1
> E4L3: Shop-N-Bag
> GAME SAVED

**Comment by coelckers** [comment]
fixed in 03b92752444f0a65309a9a853643ff62a8530656
