### ISSUE TITLE
[scriptable_cutscenes] [Duke] Screen is not cleared up immediately after ending the game

### ISSUE THREAD

**Issue by sinisterseed** [coelckers/Raze#347]
This causes the game's last frame to stay on screen for a moment, making it possible to see the status bar leaving a black space after unloading.

To observe simply start any map, then end the game.

**Comment by coelckers** [comment]
What do you mean by "ending the game"?

**Comment by sinisterseed** [comment]
> What do you mean by "ending the game"?

F10.

**Comment by coelckers** [comment]
I changed Duke to go to the menu from thee, just like the other games. Starting the intros from there is a bit problematic and cannot be done without delay - and is not really the desirable action anyway.

**Comment by sinisterseed** [comment]
I see.

Also wanted to say this happens post cutscenes as well. You could see the last frame from before the cutscene started after it ended and proceeded to play the intros again, following the boss fights.
