### ISSUE TITLE
[newrender] [SW] Finishing MAP21 returns the player to the menu

### ISSUE THREAD

**Issue by sinisterseed** [coelckers/Raze#348]
New render, but actually looking at the map progression stuff.

This doesn't seem to work fine with SW. Finishing MAP21 just returns me to the menu instead of the next level.

**Comment by coelckers** [comment]
I cannot reproduce this one, either. Again it properly reads the switch's info and goes to map 11.
Next time, please add savegames so I can check your game state.

**Comment by sinisterseed** [comment]
Just rechecked this one after you say you could not.

Very interesting, I can't do it anymore either. I wonder what happened last time, didn't do anything special other than starting a game and warping to MAP21.
