### ISSUE TITLE
[newrender] [SW] Coolies may be unable to move on movable sectors

### ISSUE THREAD

**Issue by sinisterseed** [coelckers/Raze#349]
After the train arrived in Seppuku Station, I noticed all Coolies got stuck in place, just moving on the spot and doing nothing.

Don't recall ever seeing this before.

[oddcoolie.zip](https://github.com/coelckers/Raze/files/6416335/oddcoolie.zip)

Just one in the save, but all of them were stuck when I entered.

**Comment by coelckers** [comment]
fixed in 0659bda6b6116692ecf8a5f9007997c3d682f40a
