### ISSUE TITLE
[newrender] [Blood] Finishing E1M7 does not play the videos & transitions the player to House of Horrors

### ISSUE THREAD

**Issue by sinisterseed** [coelckers/Raze#351]
It's supposed to play the videos and credits, then return to menu, but instead it does the title.

**Comment by sinisterseed** [comment]
Same for E2M8, and I assume the others too, as a result.

Seems to be a general issue.

**Comment by coelckers** [comment]
Yes, it was broken, but I already fixed it yesterday evening.

**Comment by sinisterseed** [comment]
Yup, also works correctly now, that progression weirdness is gone.
