### ISSUE TITLE
[BLOOD] v1.1.0 - e1m1 crypt door echoes

### ISSUE THREAD

**Issue by arrowgent** [coelckers/Raze#365]
compiled raze v1.1.0 linux

when spamming USE on this "door" the sound echoes overlapping
compared to dosbox & nblood the audio does not echo/overlap
one unit whole blood files, not fresh supply.

![blood](https://i.imgur.com/OdkUhVx.png)
https://i.imgur.com/9Onj3Dv.mp4
https://imgur.com/9Onj3Dv
^ audio

its a small thing, easy to overlook
this might apply to other areas through the game, im not sure
compared to "its locked" on doors you dont have a key for, those will cut & loop properly

**Comment by mjr4077au** [comment]
It's not so much a big, rather sometime that was "fixed" when someone raised it as a bug previously. See 01c494e29d647d93e58e914a92740c8bf899e230 for more information.

**Comment by arrowgent** [comment]
when was this fixed?

it also happens on mirrors
and another fake door on e1m2

if it was fixed in v1.1.1 i'll give it a try, just need to recompile it again

**Comment by sinisterseed** [comment]
How many places like these are, actually? I'm not aware of them. Saves or pics with coords in them would be appreciated.

What we did for "It's locked" and "I need a key" was a temporary fix, actually, hoping that those were the only edge cases, and in time giving them a proper fix. If there's quite a few more locations and sounds, this is gonna need to be addressed at sound engine level than just workarounds.

**Comment by arrowgent** [comment]
ok sure, i can give you a few to try to track down the trigger

e1m2 false door at start
![](https://i.imgur.com/prP3Obj.png)
![](https://i.imgur.com/eFDLu8X.png)

e1m3 mirror on second level
![](https://i.imgur.com/FqhxA3z.png)
![](https://i.imgur.com/UCga955.png)


im not going through the whole game to find every trigger
that should be enough to get started diagnosing????

**Comment by arrowgent** [comment]
the other thing is, interacting with the sinks on e1m1 and e1m2 do not echo/overlap
so those must be a different trigger set?
so how many unique could there be? or how many are using the same definition?

im not versed in blood/build or gzdoom C/C++ to know what definitions are related to these sfx

**Comment by coelckers** [comment]
Simple oversight. These unpositioned sounds are actually limited to one per channel. The play code always stops the old one in NBlood and that part somehow got lost.

Fixed in 60fe1d32fb8cac7e4cdc315c19d8895813111259
