### ISSUE TITLE
[Feature Request] Add "save" and "load" commands

### ISSUE THREAD

**Issue by Matthaiks** [coelckers/Raze#367]
To use key bindings (like `bind F5 "save Quick"` and `F9 "load Quick"`) for instant quicksaving and quickloading. GZDoom supports these commands, Raze says `Unknown command "save"` and `Unknown command "load"`.

**Comment by alexey-lysiuk** [comment]
In Raze, these commands are `quicksave` and `quickload`. They are bound to F6 and F9 by default.

**Comment by Matthaiks** [comment]
GZDoom has `save`, `quicksave`, `load` and `quickload`. Raze has only `quicksave` and `quickload`. There is a difference between _quick_ and _non-quick_ commands.

**Comment by Gaerzi** [comment]
Note that "save quick" is not actually a quicksave. It's just saving to a slot named "quick". Same result but it's a different feature from the quicksave command that also exists in GZDoom. (Same for load and quickload.) The main difference is that you can use save and load with other names if you want.

**Comment by coelckers** [comment]
Raze has also 'rotatingquicksave' as a separate command that will save each savegame to a different slot.
Anyway, with the recent changes to make the savegame system closer to GZDoom's it should be possible to copy over the load and save commands.

**Comment by coelckers** [comment]
Added in 98ca5d5db4b592b7ad803169122dae995f679d71
