### ISSUE TITLE
[NAM] Can't progress through level 1

### ISSUE THREAD

**Issue by vinceho** [coelckers/Raze#368]
Upon entering the APC to progress through level 1, the game stops and I get "Call to undefined function" in the console. This happens in Raze v1.1.1 and v1.1.2. However, it's fine in v1.0.3.

I'm using the GoG game files (NAM.GRP, NAM.RTS, and GAME.CON - renamed to NAM.CON).

Attached save file right before level 1 exit.
[nam-save.zip](https://github.com/coelckers/Raze/files/6488739/nam-save.zip)

**Comment by coelckers** [comment]
It was missing the definition of its summary screen.
Fixed by coincidence in f2d75d414682e449b1c4a8adb37658ddcbb57b99

**Comment by coelckers** [comment]
If you want to continue playing without a new release, open raze.pk3 and copy filter/duke/engine/rmapinfo.txt to filter/nam/engine/rmapinfo.txt and filter/ww2gi/engine/rmapinfo.txt
