### ISSUE TITLE
[All] CMakeLists.txt is outdated

### ISSUE THREAD

**Issue by madame-rachelle** [coelckers/Raze#370]
With the status bar scriptification, it seems that the CMakeLists.txt forgot to be pushed along with the other changes. Leading to errors such as this:

![image](https://user-images.githubusercontent.com/18584402/118393117-5c0a3380-b60b-11eb-96ec-308b783279ec.png)

**Comment by coelckers** [comment]
Strangely enough it never errored out for me, despite the files being gone.
