### ISSUE TITLE
[Since HUD scriptification] Status bar scale moves the position of the stats widget even when the biggest screen size is used

### ISSUE THREAD

**Issue by sinisterseed** [coelckers/Raze#372]
Really minor but it's there.

To reproduce just enable the level stats widget, max out the screen size, play with the status bar scale slider. Even when the HUD is absent the widget moves up and down ever so slightly.

**Comment by coelckers** [comment]
fixed in 25d516c36f14ff0fa55a9fe766aedcc3dc561e32
