### ISSUE TITLE
[Exhumed] Can kill enemies even when not facing them

### ISSUE THREAD

**Issue by sinisterseed** [coelckers/Raze#373]
Spotted this while I was looking for something else, but damn this is huge.

So apparently either autoaim or something else seems to ignore where the player is facing, making it possible to kill enemies who are not in your sight.

Take this save right here. The Anubis dude is to the left. Just go inside and fire in the opposite direction. You will kill him anyway.

[warpingandaimingbugs.zip](https://github.com/coelckers/Raze/files/6489270/warpingandaimingbugs.zip)

**Comment by coelckers** [comment]
Don't laugh. This is really how this game implements autoaim! If the player has a valid target it gets attacked by hitscans regardless of where it is in relation to the player.

**Comment by coelckers** [comment]
I added a proper check - no idea if this should be guarded by a CVar.
In PCExhumed this "autoaim" is unconditional, btw.

**Comment by sinisterseed** [comment]
> I added a proper check - no idea if this should be guarded by a CVar.
> In PCExhumed this "autoaim" is unconditional, btw.
> 

Oh that's interesting. I was afraid we broke this mysteriously. I think this is better guarded behind a CVAR, and have a menu entry for it in Miscellaneous, just like the vanilla turning speed toggle.
