### ISSUE TITLE
[New render] [Exhumed] Awful texture warping on doors

### ISSUE THREAD

**Issue by sinisterseed** [coelckers/Raze#374]
![Exhumed_0000](https://user-images.githubusercontent.com/57503728/118398428-40ca1300-b661-11eb-8627-0e5100faf30f.png)

Well, that's hilarious. Using Vulkan there but not sure it matters.

Save is in #373 .

**Comment by coelckers** [comment]
Looks like it is the same thing as the other wall sprite render bugs.
I cannot reproduce this anymore.
