### ISSUE TITLE
[Exhumed] Inventory items may not start animating again after quiting the game and loading a save

### ISSUE THREAD

**Issue by sinisterseed** [coelckers/Raze#375]
Save is in #373 .

I simply quite the game game and when I loaded the save the inventory items stopped animating. Only way to fix it is by scrolling through it or using an item, otherwise it stays frozen. Map transitions don't fix it if the inventory is carried over.

![Exhumed_0001](https://user-images.githubusercontent.com/57503728/118398734-a36fde80-b662-11eb-9e82-b6770ed44bad.png)

**Comment by coelckers** [comment]
Fixed in 24ce5d61306b2f4e1e782031e69fc0434eefab38

This is one of these mysterious things. By all accounts the old code should have stopped animating the torch as well. I suspect some bugs cancelling each other out...
