### ISSUE TITLE
[New render] [Blood] E1M2 train wheels have disappeared

### ISSUE THREAD

**Issue by sinisterseed** [coelckers/Raze#377]
Rendering correctly in Polymost.

![Blood_0003](https://user-images.githubusercontent.com/57503728/118399334-5e997700-b665-11eb-8e73-314114b75f00.png)

[trainwheels.zip](https://github.com/coelckers/Raze/files/6489309/trainwheels.zip)

**Comment by coelckers** [comment]
Same as the other texture placement related reports.
