### ISSUE TITLE
[New render] [Blood] Light flickering behind E1M1 TNT secret

### ISSUE THREAD

**Issue by sinisterseed** [coelckers/Raze#378]
Doesn't happen in Polymost, where it's just dark.

![Blood_0002](https://user-images.githubusercontent.com/57503728/118400146-12e8cc80-b669-11eb-8a38-49efdb5e8e5b.png)

Too bad I can't time it properly.

**Comment by coelckers** [comment]
fixed in 5e94eaff8e88c795e881529673e6a0577e4b0748
