### ISSUE TITLE
[Blood] [1.1.1] Platforms disapear in newrenderer

### ISSUE THREAD

**Issue by markanini** [coelckers/Raze#385]
Playing Fleshed Out campaign for Blood, in E1M5 platforms disappear depending on angle and distance with testnewrenderer true. 
Mod link:https://www.moddb.com/mods/blood-fleshed-out/downloads/fleshed-out-v17

[save0002.dsave.txt](https://github.com/coelckers/Raze/files/6501879/save0002.dsave.txt)

**Comment by coelckers** [comment]
fixed in f96521a7f45a44d637c88612efa5824207188b1c
