### ISSUE TITLE
[Blood / Commit 5ee4bc] Ammo not displayed in the "classic" status bar

### ISSUE THREAD

**Issue by RazTK** [coelckers/Raze#386]
![Blood](https://i.imgur.com/Faw9phO.png)

Also, is it the episode name that's supposed to be displayed in upper-left corner (it's what being shown right now) or the level name?

**Comment by coelckers** [comment]
Fixed in 75cc66083da3022c6f04d605d835ac1d3bb9b0db

**Comment by RazTK** [comment]
Thanks for the fix, the only thing left is to change the ammo counter to blue instead of red (unless that was intentional?). :>
