### ISSUE TITLE
[Blood][d4eb54d] Key signs flicker

### ISSUE THREAD

**Issue by markanini** [coelckers/Raze#388]
In The e1m7 of the Fleshed Out user campaign key signs flicker in and out depending on angle and distance with newrenderer.
mod link:https://www.moddb.com/mods/blood-fleshed-out/downloads/fleshed-out-v17

[auto0003.dsave.txt](https://github.com/coelckers/Raze/files/6515639/auto0003.dsave.txt)

![Blood_0002](https://user-images.githubusercontent.com/15148553/118975000-c6a4d180-b973-11eb-96d0-ed2795cb4d0d.png)
![Blood_0003](https://user-images.githubusercontent.com/15148553/118975009-ca385880-b973-11eb-845b-26fa6622925d.png)

**Comment by coelckers** [comment]
Yeah, I had a typo in the wall sprite offsetting code that rendered parts of it broken.
