### ISSUE TITLE
[Blood][75ecd17] Distant wall decorations flicker

### ISSUE THREAD

**Issue by markanini** [coelckers/Raze#390]
Similar to #388 but affecting distant wall decorations flickering in and out depending on angle with newrenderer in fo1m7 of the Fleshed Out user campaign.
mod link:https://www.moddb.com/mods/blood-fleshed-out/downloads/fleshed-out-v17
[save0006.dsave.txt](https://github.com/coelckers/Raze/files/6517978/save0006.dsave.txt)
![Blood_0004](https://user-images.githubusercontent.com/15148553/119029328-c672f900-b9a8-11eb-9f3a-e3314b5004d7.png)
![Blood_0005](https://user-images.githubusercontent.com/15148553/119029338-c96de980-b9a8-11eb-9e30-02ad8d76953c.png)

**Comment by coelckers** [comment]
-the logic was a bit wrong. Should be better now.

But one thing has to be clear: Due to the haphazard way in which Build handles wall sprites there will always be cases where they don't display correctly. They will just be different than the ones in Polymost.
