### ISSUE TITLE
Assert with vm_jit 0 - inconsistency in virtual call

### ISSUE THREAD

**Issue by madame-rachelle** [coelckers/Raze#391]
I am not really sure how to fix this because it seems to be a question of intent (why is this function even virtual in the first place?)

The two places this is called, in question, are here:
https://github.com/coelckers/Raze/blob/75ecd173b6f05c591fe74a2d3fdcfc533fb1eef2/wadsrc/static/zscript/screenjob.zs#L379-L382
https://github.com/coelckers/Raze/blob/75ecd173b6f05c591fe74a2d3fdcfc533fb1eef2/source/core/screenjob.cpp#L343-L350

It seems to be easily solved by changing this line https://github.com/coelckers/Raze/blob/master/source/core/screenjob.cpp#L348 - to this:
`VMCall(func, parm, 1, &ret, 1);`

**Comment by coelckers** [comment]
Yeah, the 2 is an error, apparently some copy paste oversight.. Of course it only has one argument.
