### ISSUE TITLE
[Blood] [1.1.2] Skybox palette not used 

### ISSUE THREAD

**Issue by markanini** [coelckers/Raze#393]
Enhancement request. In the E2M1 of the user campaign Death Wish a red monotone palette is used for the sky. When loading custom skyboxes it's not used.
Death Wish link: https://www.moddb.com/mods/death-wish-for-blood/downloads/death-wish-17
Skybox link: https://m210.duke4.net/index.php/downloads/download/9-gdxpacks/64-skyboxes-all-in-one-pack
![Blood_0006](https://user-images.githubusercontent.com/15148553/119181536-0651e300-ba72-11eb-866d-c819fbf5eab4.png)
![Blood_0007](https://user-images.githubusercontent.com/15148553/119181541-07831000-ba72-11eb-9030-d400f599d1e0.png)

**Comment by coelckers** [comment]
Hm, seems I overlooked this part when implementing the skybox code.

**Comment by Phredreeke** [comment]
Skyboxes in the EDuke32 and BuildGDX families of ports don't have palette swap capability. I created separate versions for this pack, but I overlooked said sky/palette combo.

**Comment by coelckers** [comment]
And needless to say, changing this behavior may cause problems with other skyboxes. 
I'll keep it as it is.
