### ISSUE TITLE
Missing triangles in Shadow Warrior $shore.map (Shanghai Shipwreck)

### ISSUE THREAD

**Issue by Talon1024** [coelckers/Raze#396]
When a certain door on Shanghai Shipwreck ($shore.map) is closed, there is a missing floor and ceiling triangle in front of it. Here's a saved game which demonstrates the issue: [save0004.dsave](https://github.com/coelckers/Raze/files/6528171/save0004.zip)

Don't worry about the ZIP extension; I had to do that in order to get the saved game uploaded.

**Comment by coelckers** [comment]
This one was a small logic error in the wall culler.
