### ISSUE TITLE
Polys where there shouldn't be on Shadow Warrior $bath.map

### ISSUE THREAD

**Issue by Talon1024** [coelckers/Raze#397]
On the Bathhouse level of Shadow Warrior ($bath.map), when you walk up the second staircase, there is a piece of the ceiling from another sector which shouldn't be there. Here's a saved game which demonstrates the issue: [save0006.dsave](https://github.com/coelckers/Raze/files/6528180/save0006.zip)

**Comment by Cacodemon345** [comment]
Man doing a Build renderer looks to be a big-time pain...

**Comment by coelckers** [comment]
This one's the same as on CP07, We got a non-Euclidean setup where both layers can be looked into at the same time.
I have no universal fix for this kind of issue, aside from splitting up the sector up front and render it in two parts.

**Comment by coelckers** [comment]
Unlike the one in CP I wasn't able to split the sector in a way that fully eliminates the issue. A tiny sliver of the ceiling can still be seen, but you have to be on the lookout for this to see it. Good enough for now.
