### ISSUE TITLE
[Duke 3D] Skybox texture alignment (Alien World Order)

### ISSUE THREAD

**Issue by Matthaiks** [coelckers/Raze#399]
Smaller status bar breaks skyboxes in Episode 5 (default FOV of 90.0),

Raze 1.1.2

E5L1
![E52](https://user-images.githubusercontent.com/3577122/119265369-bd6f6b00-bbe6-11eb-94a9-3c3ea864d3de.png)
![E51](https://user-images.githubusercontent.com/3577122/119265366-ba747a80-bbe6-11eb-9d94-4b711be175e8.png)

E1L1
![E11](https://user-images.githubusercontent.com/3577122/119265381-c95b2d00-bbe6-11eb-902f-cc143251bec7.png)
![E12](https://user-images.githubusercontent.com/3577122/119265383-c9f3c380-bbe6-11eb-87f1-3d57d7890f80.png)

**Comment by coelckers** [comment]
This is a known issue of the sky code. Unfortunately this wasn't designed well. In Blood the same effect is far more frequent.
