### ISSUE TITLE
Assertion failure at the start of $yamato.map

### ISSUE THREAD

**Issue by Talon1024** [coelckers/Raze#400]
Trying to start a game on Shadow Warrior $yamato.map (Floating Fortress) causes an assertion failure:

    raze: ../source/core/nodebuilder/nodebuild.h:294: int FNodeBuilder::FVertexMap::GetBlock(fixed64_t, fixed64_t): Assertion `x >= MinX' failed.

**Comment by coelckers** [comment]
fixed in 2b8a80c6ce03ffde0b4c828d40943703023754bb
