### ISSUE TITLE
Assertion failure at start of SW: WD $airport.map

### ISSUE THREAD

**Issue by Talon1024** [coelckers/Raze#401]
Trying to start a game on Shadow Warrior: Wanton Destruction $airport.map (Auto Factory) causes this assertion failure:

    raze: ../source/games/sw/src/track.cpp:680: void ShadowWarrior::TrackSetup(): Assertion `low_dist < 20000' failed.

**Comment by coelckers** [comment]
Removed the assert in 1ea09cd3d23c8927d9f64f002695a26d13619f5a
