### ISSUE TITLE
UV mapping issues with Duke3D HRP textures

### ISSUE THREAD

**Issue by Talon1024** [coelckers/Raze#402]
If you load the [Duke Nukem 3D High Resolution pack](https://hrp.duke4.net), some textures are incorrectly UV mapped. For example, there should only be 4 wooden "doors" at the front, but if you load the HRP, there are twice as many "doors" which are half as wide as the originals.

This affects both Polymost and the new renderer.

Here's a saved game: [save0004.zip](https://github.com/coelckers/Raze/files/6528389/save0004.zip)

Screenshot without HRP:
![Duke_0015](https://user-images.githubusercontent.com/6550500/119267262-c0a13180-bbbb-11eb-98f6-ae811edfef1b.png)
Screenshot with HRP:
![Duke_0016](https://user-images.githubusercontent.com/6550500/119267269-c6971280-bbbb-11eb-9149-3ec204449710.png)

**Comment by coelckers** [comment]
It looks correct with the version of the HRP I have, but some of the textures are very different.

**Comment by Talon1024** [comment]
Perhaps the HRP textures have different proportions than the originals? I guess that would explain it, and make sense at the same time.

Perhaps the people making the HRP textures wanted to make the repetition less noticeable by adding more space to textures like the cement floor tile and the wooden "doors".

**Comment by mjr4077au** [comment]
Are you loading the Polymer file or the Polymost file?

**Comment by Talon1024** [comment]
I haven't downloaded the Polymost HRP (AFAIK it's a patch for the Polymer HRP), so I'm using the Polymer HRP.

**Comment by coelckers** [comment]
The HRP is the same, but the .def files are different, you have to edit its startup first.
