### ISSUE TITLE
[raze 1.1.2] all games refuse to launch with no errors in the log

### ISSUE THREAD

**Issue by jali-peno** [coelckers/Raze#404]
im running under opengl on intel hd 4000 with the phdgd ivydrive custom drivers. i havent used this pc in a while but after updating raze this started happening so im assuming its a raze problem. so far ive tested duke nukem 3d atomic edition, shadow warrior and its expansions, one unit whole blood, and cryptic passage, all giving the same result.

upon launching a game, the screen turns black, a 3d realms/monolith logo appears VERY late, dissapears late, and the game doesnt boot to the title screen. the title music plays looping infinitley in the background too.

i checked the log for raze and saw no errors in it at all, and this is a fresh raze 1.1.2 install with no changes made to the config file. below you should see the log.

[raze.log](https://github.com/coelckers/Raze/files/6534177/raze.log)

**Comment by jali-peno** [comment]
sorry if this is a really unhelpful report but im afraid there isnt much else i can provide in terms of info.
all important system specs are in the log file

**Comment by coelckers** [comment]
First, let's try to narrow this down.

Do older Raze versions work?
What about GZDoom? It uses the same backend so a comparison may be useful.

I cannot say much about these drivers and how compatible they are

**Comment by jali-peno** [comment]
gzdooms latest update works fine for me. last time i used this pc i was running a version of raze before 1.0.0 so it very well may have something to do with that update. i thing i was running 9.1 beta last time, i should have checked before updating so sorry in advance

**Comment by coelckers** [comment]
You can still find all released versions on the Github downloads page. So if older ones worked, please try to narrow this down to the first version that doesn't work anymore.

**Comment by mjr4077au** [comment]
@jali-peno just wanted to see if this was still an ongoing issue for you? We just released 1.1.3 a few days ago and thought you might like to try again? 😁 

https://github.com/coelckers/Raze/releases/tag/1.1.3

**Comment by jali-peno** [comment]
thank you guys! idk what the problem was but it seems to work fine now! i tried the big three and they all launched without issue

**Comment by mjr4077au** [comment]
Really glad to hear! Happy gaming 🤘
