### ISSUE TITLE
[Blood] [9382a62] Phantom ship poles too tall

### ISSUE THREAD

**Issue by markanini** [coelckers/Raze#405]
Playing Death Wish campaign for Blood, in DWE2M6 poles look too tall on the Phantom ship with newrenderer.
Mod link:https://www.moddb.com/mods/death-wish-for-blood/downloads/death-wish-17

[save0008.dsave.txt](https://github.com/coelckers/Raze/files/6540821/save0008.dsave.txt)

![Blood_0012](https://user-images.githubusercontent.com/15148553/119532431-28ef3f00-bd85-11eb-901c-beead6187252.png)
![Blood_0013](https://user-images.githubusercontent.com/15148553/119532442-2ab90280-bd85-11eb-9336-2dbbe22f0731.png)

**Comment by coelckers** [comment]
This was the same as #407, the poles were not too tall, but a column of fog was rendered above them.
