### ISSUE TITLE
[Windows] Raze cannot load game data on an unmapped network drive

### ISSUE THREAD

**Issue by prg318** [coelckers/Raze#406]
When raze on Windows is launched and the raze.exe is contained within an unmapped network share that contains game data files, Raze displays the following fatal error message:

```
Fatal Error - Raze 1.1.2 64-bit
Using program directory for storage
Log started: 2021-05-25 12:58:20
OS: Windows 10 (or higher) (NT 10.0) Build 19042
    

Execution could not continue.

Unable to find any game data. Please verify your settings.
```

To workaround this issue, a user can map the unmapped network drive to a drive letter in Windows.  Alternatively, a user can copy the folder containing raze and the game data to local storage.

It would be awesome if raze was able to load game data using unmapped network drive paths in windows (eg: ``\\server\folder\path\to\game\data ``)

**Comment by coelckers** [comment]
This will be a bit tricky to handle. It affects virtually the entire set of file path operation functions inherited from GZDoom, which in turn got them from ZDoom - all this code is from a time where network paths were not a thing to consider.

**Comment by prg318** [comment]
GZDoom actually does support loading game data from unmapped network drives in Windows.  I'm not exactly sure when gzdoom got this functionality, but GZDoom 4.2.2 is able to do this:

```
OS: Windows 10 (or higher (NT 10.0) Build 19042
M_LoadDefaults: Load system defaults.
Using program directory for storage
W_Init: Init WADfiles.
  adding //myserver/scratch/gzdoom/gzdoom.pk3, 615 lumps
  adding //myserver/scratch/gzdoom/game_support.pk3, 2512 lumps
  adding ./heretic1.wad, 1374 lumps
```

**Comment by madame-rachelle** [comment]
While I don't see much issue with fixing this, in my experience network shares are massively insecure and leave the system prone to instability. All it takes is some rough network conditions and some packet loss and zombie processes become a huge problem. But - to each their own. (There are better ways to handle needing to share data over the network, using some sort of iSCSI NAS system is ideal)

**Comment by prg318** [comment]
It looks like the issue stems from within ``source/core/searchpaths.cpp``.  The ``str.Substitute("//", "/");`` in ``CollectSearchPaths()`` will render a network path (eg: //server/folder) unusable.

Maybe CollectSearchPaths() could substitute double slashes for slashes, but start evaluating at the second character of the string so that network paths are not mangled?

I've commented out the double-slash substitution on my branch, and Raze happily loads game data from unmapped network folders:
https://github.com/prg318/Raze/tree/network-load

I will absolutely admit that SMB has its fair share of problems, but it can be a pretty convenient way to continue saved games on different machines - and it would be great to be able to accomplish this with Raze without needing to map network shares to a drive letter (which can have its own set of problems )

**Comment by madame-rachelle** [comment]
Alright. Instead of removing that line, though, I'm just going to put in special handling to allow UNC paths.

**Comment by madame-rachelle** [comment]
Fixed with this commit:

https://github.com/coelckers/Raze/commit/fd97da05b7a11192cf33f6d72e4a53a25555f5b2

I tested it by RemoteApp'ing into my command prompt and running from `\\tsclient\c`.

**Comment by prg318** [comment]
Just tested fd97da0 and it works great! 

Thanks madame-rachelle and coelckers for your awesome efforts on both raze and gzdoom.  Your work is absolutely appreciated!

**Comment by madame-rachelle** [comment]
Thank you for your feedback. :)
