### ISSUE TITLE
[Blood] [9382a62] Missing white skybox

### ISSUE THREAD

**Issue by markanini** [coelckers/Raze#407]
Playing Death Wish campaign for Blood, in DWE2M8 the skybox is missing the white out effect in the section after the fire key with newrenderer. Happens regardless of stock or custom skybox.
Mod link:https://www.moddb.com/mods/death-wish-for-blood/downloads/death-wish-17
[save0009.dsave.txt](https://github.com/coelckers/Raze/files/6543594/save0009.dsave.txt)
![Blood_0014](https://user-images.githubusercontent.com/15148553/119597287-068b0f00-bde1-11eb-8354-d66363762803.png)
![Blood_0015](https://user-images.githubusercontent.com/15148553/119597291-07bc3c00-bde1-11eb-922b-c55b9ce99574.png)

**Comment by coelckers** [comment]
fixed in 2e9732ce79a8da0bd9d42e31df13f06371bab767
