### ISSUE TITLE
[Duke/WT] Some monsters may turn invulnerable

### ISSUE THREAD

**Issue by sinisterseed** [coelckers/Raze#410]
There was a report for this way back in the days of 0.7, but it seems to be more frequent in WT for some reason.

Civvie encountered this mainly on Red Ruckus. I'm gonna give it a few spins to see if I can trigger it in another save again, but last time that happened, the save wasn't of too much help.

**Comment by sinisterseed** [comment]
Got 'em, on E5L2.

One of the monsters was invulnerable when I arrived. I think saving on a previous area before reaching them, quitting the game, and loading the save afterwards may trigger this bug. I saved in the water section, and after I restarted the game, this guy may have become invulnerable.

[invulnerablemonster.zip](https://github.com/coelckers/Raze/files/6547055/invulnerablemonster.zip)

**Comment by coelckers** [comment]
I cannot load this savegame. Please try to do this with Nightfright's add-on version so that it doesn't depend on local paths.

**Comment by sinisterseed** [comment]
Meanwhile, 6 months later, it seems I cannot trigger the bug anymore. Last time it was somewhat effortless to trigger on E5L2, but now, tried some 5 different ways to trigger it and all failed.

I would love to think this may have been the last we've seen of this stupidity, but who knows when it may resurface for the nth time? Maybe the issue was elsewhere and it got fixed by accident too? Can only guess at this point.

**Comment by sinisterseed** [comment]
Actually, due to the inability to trigger this bug anymore since the issue was originally opened, I've decided to close it for the time being. Should this issue resurface again in the future, in a fashion that is easier to reproduce, it can just be reopened at a later time. But for now, it can't be triggered anymore.
