### ISSUE TITLE
[Blood] Heart in HUD has wrong offsets

### ISSUE THREAD

**Issue by Dzierzan** [coelckers/Raze#413]
Compare that:

![heart](https://user-images.githubusercontent.com/17529329/119877508-6b518100-bf29-11eb-96af-b6b317b9744a.gif)

**Comment by Dzierzan** [comment]
So I presume it's unfixable? Not worth fixing? Super low priority? I just wanna say that at least write a comment why you close an issue.

**Comment by sinisterseed** [comment]
> So I presume it's unfixable? Not worth fixing? Super low priority? I just wanna say that at least write a comment why you close an issue.

https://github.com/coelckers/Raze/commit/39b84c40634b52520f72b55edc8ae86a09d7954d

Don't worry, it was fixed. Graf probably just forgot to reply.

**Comment by Dzierzan** [comment]
OK, I had "WTF" moment, thanks.
