### ISSUE TITLE
[Blood] [Shadow Warrior] Shadows are reflections in the new renderer

### ISSUE THREAD

**Issue by valter12437** [coelckers/Raze#414]
Shadows are behaving like reflections in the new renderer.

![Blood_0010](https://user-images.githubusercontent.com/82282361/120051167-f304c180-bff5-11eb-905b-0dcacb1ce519.png)

![ShadowWarrior_0004](https://user-images.githubusercontent.com/82282361/120051174-f8faa280-bff5-11eb-97d7-61661dc8eb0a.png)

**Comment by coelckers** [comment]
Look correct in the latest Git revision
