### ISSUE TITLE
[SW:WD, newrenderer] "Great wall" in the Redwood Forest

### ISSUE THREAD

**Issue by Talon1024** [coelckers/Raze#417]
If you're playing the Redwood Forest level of Shadow Warrior: Wanton Destruction, a "Great Wall" appears in the distance where there should be none.

[Here's a saved game](https://github.com/coelckers/Raze/files/6565951/save0009.zip)

And screenshots from Polymost and newrenderer, respectively:
![ShadowWarrior_0016](https://user-images.githubusercontent.com/6550500/120098603-de631f00-c104-11eb-9b77-57313f9e5e61.png)
![ShadowWarrior_0015](https://user-images.githubusercontent.com/6550500/120098604-e0c57900-c104-11eb-85a5-14bc6b7d7519.png)

**Comment by coelckers** [comment]
Fixed, but unlike Polymost with the right color.
BTW, that blood splat on that foggy wall in that screenshot looks quite hilarious...

I guess that's the price for using render hacks like this.
