### ISSUE TITLE
[Blood] Transparent voxels are not transparent

### ISSUE THREAD

**Issue by Dzierzan** [coelckers/Raze#419]
I already reported this and it was supposed to be fixed. This was tested using Raze 1.1.2 and the using master branch of Blood Voxel Pack.

![image](https://user-images.githubusercontent.com/17529329/120898230-45636500-c62a-11eb-88a4-52b7108290a6.png)

**Comment by The-King-of-Toasters** [comment]
I tried this with the new in-progress renderer and the voxels became transparent again. Set `testnewrenderer 1` to see if that fixes it.

**Comment by Dzierzan** [comment]
@The-King-of-Toasters 

Yeah, that seems to be fine in a new renderer.

**Comment by coelckers** [comment]
fixed in 333d38e48a155a7fa43c42b4af433794b4af4d4d
