### ISSUE TITLE
Playing Blood with the voxel pack leads to incorrect models being chosen

### ISSUE THREAD

**Issue by The-King-of-Toasters** [coelckers/Raze#422]
I bisected this bug back to 454816299. The correct voxel models were placed and rendered, now only some of them are. It's most evident with the first secret:

![good](https://user-images.githubusercontent.com/9159492/121355343-22f78180-c973-11eb-86bc-09c95cbf5fdb.png)
![bad](https://user-images.githubusercontent.com/9159492/121355345-23901800-c973-11eb-9b01-72906bbcefb2.png)

**Comment by Shockwave508** [comment]
Can confirm this happens to me as well, only instead of a sawblade its a fire-alarm.

**Comment by Dzierzan** [comment]
@The-King-of-Toasters @Shockwave508 If you use the master branch, please remove `MODELS.INI` from the zip and try again.

**Comment by mjr4077au** [comment]
That's not a fix for this issue. This one's unfortunately still ongoing.

**Comment by coelckers** [comment]
Order of initialization was not correct.
Strangely enough, it was correct for SW but not for Blood.

b06ad5c77ffb800d326909a363e83f8e218e0f90
