### ISSUE TITLE
[Shadow Warrior] No ability to have hitscan-only autoaim?

### ISSUE THREAD

**Issue by srludicolo** [coelckers/Raze#423]
It's pretty simple, haha. I find hitscan-only autoaim to be the equilibrium that I play best with. The option for this is in every build engine game that Raze supports, iirc. Shadow Warrior seems to be the odd one out in this case. Even Redneck Rampage supports it, despite the infamously janky autoaim. I love Shadow Warrior, and I think the experience of playing it on Raze would be even better with this feature :)

**Comment by sinisterseed** [comment]
There should be, though. Under Miscellaneous if I recall?

It must have broken again if it stopped working.

**Comment by sinisterseed** [comment]
No, actually, there isn't.

But I'm confident it existed since it was fixed once before.

**Comment by sinisterseed** [comment]
> Keep in mind that SW is totally different code than Duke and RR, which share maybe 50%. So Duke having the feature automatically translates to RR, but not to Blood and not to SW. Exhumed's "Autoaim" is even worse but again totally different code.

I know, that wasn't my point though.

I just seem to recall this was fixed at some point for SW too, or I may be getting confused again.

**Comment by coelckers** [comment]
Added in 2af2d29084892c32bb5cbce3a05edbfcae66ab22
Fortunately the code had this already cleanly separated for hitscan and projectile attacks.
