### ISSUE TITLE
[1.1.2]Autload for Duke addons not loading

### ISSUE THREAD

**Issue by markanini** [coelckers/Raze#424]
In the user ini I added the following line, which worked as expected.
```
[Duke.Autoload]
Path=$PROGDIR/WT-skyboxes.zip
```

But when I tried specifying for World Tour it didn't load using the following

```
[Duke.Worldtour.Autoload]
Path=$PROGDIR/WT-skyboxes.zip
```

**Comment by Gaerzi** [comment]
Note that "Duke.Worldtour" is specifically for the add-on version generated by Nightfright's script.  The full version apparently uses "Duke.Duke.15".

**Comment by coelckers** [comment]
The main problem here is that due to its messy setup the full version can only be detected after parsing the CON scripts. Which is too late for setting up the autoload.

**Comment by coelckers** [comment]
I'm sorry, but this is out of my hands. Please use NightFright's GRP creator if you need this feature. With the existing setup there is no way to detect the extension before the file system has been set up.
