### ISSUE TITLE
[Redneck Rampage: Rides Again] Lack of widescreen sprite for HUD bike

### ISSUE THREAD

**Issue by Dzierzan** [coelckers/Raze#426]
There's no widescreen sprite for the bike despite it has been already made. Is it perhaps commented out? I tested that using the latest Raze version.

**Comment by Dzierzan** [comment]
Why `help wanted` label? I just looked inside pk3. Apparently someone forgot to add 7170 (it's in def).

![7170](https://user-images.githubusercontent.com/17529329/121799435-64668600-cc2c-11eb-8be9-7a5d6c57530b.PNG)

**Comment by coelckers** [comment]
No idea how this one got lost...
