### ISSUE TITLE
[Powerslave] “Unable to find any game data. Please verify your settings.”

### ISSUE THREAD

**Issue by mjohanning99** [coelckers/Raze#430]
I have successfully compiled Raze on my Pop!_OS 20.10 machine, but whenever I attempt to start the program, it throws the error which can be seen at the top of this issue at me. I have put my game data into ~/.config/raze and have even copied the binary `raze` file into the game data directory and tried running it directly from there — to no avail. I am using the GoG version of the game and thought it would work without any problems and I am honestly not entirely sure what I could be doing incorrectly. 

When downloading the Windows .exe file and running that in Wine, it works without any issues. If all else fails, I'll simply continue using the Windows executable, though I would like to find out what the problem with my Linux install might be.

**Comment by mjr4077au** [comment]
I don't have any problems myself under Linux:

![image](https://user-images.githubusercontent.com/48643140/123248866-c0ce7d00-d52b-11eb-824f-ee44e0e2f453.png)

Can you try in a subfolder like I have? I believe there's a detection issue under Linux with game content directly in the config directory for Raze.

**Comment by alexey-lysiuk** [comment]
Honestly, such reports without file listing and complete directory structure should be marked as invalid. It seems like people think that we like guessing games.

**Comment by mjr4077au** [comment]
> Honestly, such reports without file listing and complete directory structure should be marked as invalid. It seems like people think that we like guessing games.

Agreed but in this instance there was a feature parity break between Unix systems and Windows. Just a one-liner to fix up which is nice.
