### ISSUE TITLE
[Shadow Warrior] Weapon layer sprites don't move together with the main weapon sprite. 

### ISSUE THREAD

**Issue by Dzierzan** [coelckers/Raze#431]
Take a closer look at this Missile Launcher. When it fires, you can see the main sprite moves first and then its sprite layers. It doesn't happen in VoidSW and BuildGDX. It appears this issue have all weapons with layers.

![missile](https://user-images.githubusercontent.com/17529329/122204120-0c838580-ce9f-11eb-98cd-eed3c6aed901.gif)

**Comment by mjr4077au** [comment]
Finally had a chance to look into this one properly, goes back to 66cb7f61a41f33f6a252eaeb45841e9414c293f7 on the 15th of August.

@coelckers I might need to ask for your help on this one, not sure what needs to happen to fix this.

**Comment by coelckers** [comment]
I had to disable the recoil animation to see something here. It looks like one sprite in the firing animation has a slightly different size that results in some minor shifting around when being rendered. You can see that right before the recoil starts the weapon shifts up a bit, that's the frame with the bad display
