### ISSUE TITLE
Visibility option for Duke 3D

### ISSUE THREAD

**Issue by doon343** [coelckers/Raze#432]
I know that this option is in EDuke32 (Like the picture), but I was wondering if it is possible that this could be added to Raze. Thanks!
![visoption](https://user-images.githubusercontent.com/86077898/122459784-f34e0800-cf76-11eb-8e42-a1e062a6da52.PNG)

**Comment by Calinou** [comment]
Last time I checked, it's available as a console command: `r_ambientlight 2`

**Comment by doon343** [comment]
> Last time I checked, it's available as a console command: `r_ambientlight 2.5`
> 
> It's not exposed to the GUI yet though.

Thanks!
