### ISSUE TITLE
Display path where game data files should be installed in the "No game data files found" error message

### ISSUE THREAD

**Issue by Calinou** [coelckers/Raze#434]
I'm trying to help out someone on macOS to install Raze, but they don't know which folder they should install the game files to. They've looked into `/Library/Application Support/Raze` which should be correct per the source code. We haven't been able to get it to work so far, not even with `/Library/Application Support/Raze/duke/duke3d.grp` + `duke.rts` in the same folder. (We also tried casing and naming variations such as `Duke` and `Duke.Duke`, and all 3 variants work here on Linux.)

They're running a M1-based Mac with Big Sur, so maybe the Library path changed due to sandboxing?

I suggest the search paths should be displayed in the error message that tells you where you should put the game data files. This would also help users on other platforms.

**Comment by alexey-lysiuk** [comment]
Depending on OS, there can be several paths to look for game data. On macOS, `~/Documents/Raze` works as well (if user didn’t prohibit access to Documents for Raze app).

**Comment by Calinou** [comment]
> Depending on OS, there can be several paths to look for game data. On macOS, `~/Documents/Raze` works as well (if user didn’t prohibit access to Documents for Raze app).

That path works, thanks :slightly_smiling_face:

**Comment by alexey-lysiuk** [comment]
`open ~/Library/Preferences/raze.ini` command in Terminal will open config file with the default text editor. All paths are listed at the beginning of this file, with self-explanatory comments. Of course, you can add your own if needed.
