### ISSUE TITLE
Update language.csv with translation for `DSPLYMNU_AMBIENT_LIGHT` from #436

### ISSUE THREAD

**Issue by mjr4077au** [coelckers/Raze#443]

**Comment by coelckers** [comment]
Can you please request access to the spreadsheet at https://docs.google.com/spreadsheets/d/1QvRvEcBOtXuJ5lBBThAF-rLjGFHhXiSN1x8wfBpW3rk/edit?usp=sharing ?

**Comment by mjr4077au** [comment]
Done, but I think it's for the wrong file?

![image](https://user-images.githubusercontent.com/48643140/123251123-2f143f00-d52e-11eb-88c1-7ce2558fdb60.png)

**Comment by coelckers** [comment]
Yes, that's the wrong file. Sorry. The two links look identical when viewed in the browser. Here's the correct one:

https://docs.google.com/spreadsheets/d/1pvwXEgytkor9SClCiDn4j5AH7FedyXS-ocCbsuQIXDU/edit?usp=sharing

**Comment by mjr4077au** [comment]
I've added the missing line but am unsure of the procedure to update the language.csv file in the project.

I also wanted to clarify, for the other tranlsations I just ran "Ambient Light" through Google Translate. For the most part, it had verified ticks on the translation. Is this the procedure for simple strings?

**Comment by sinisterseed** [comment]
Same, I also want to know how to update the file in the project, but keep forgetting to ask.

It's been so long since it saw an update...

**Comment by coelckers** [comment]
You have to download the sheets as CSV files, rename them accordingly and copy them into wadsrc.

For translations I would not recommend using Google Translate, unless you want to fill in a single string in an otherwise complete language. That goes particularly if you cannot read the target language at all. Even checked translations are often contextually incorrect so the least you should do is translate it back and see that something sensible comes out.

This one was simple enough so that most are probably correct.

**Comment by Gaerzi** [comment]
Yeah, automated translators are not truly reliable. For example I've just read a text translated from English to French where the word "[nail](https://www.wordreference.com/enfr/nail)" was translated sometimes as "clou" and sometimes as "ongle"...

For "ambient light" I could see a translator turning it into the equivalent of "mood lighting" for some languages.

**Comment by mjr4077au** [comment]
Between what you both have said, might be best to take the translations for this string out. I thought it was simple enough as well but who's to say, really. Is the German one at least right? 😅

**Comment by sinisterseed** [comment]
Can agree on that. Unless someone speaking the respective languages themselves find suitable translations, I think it's best to leave GT lines out just in case.

GT is very hit or miss with them depending on language, sometimes it's right, other times very far away from reality. It did manage to have some use for me in a few cases, where I GT some lines from Russian to mine, and the result was actually *not bullshit*.
