### ISSUE TITLE
[SW]: Menu spacing differs upon initial load vs. level loaded.

### ISSUE THREAD

**Issue by mjr4077au** [coelckers/Raze#444]
![Screenshot at 2021-06-24 21-13-53](https://user-images.githubusercontent.com/48643140/123253900-591b3080-d531-11eb-8b60-c226b8d13967.png)

![image](https://user-images.githubusercontent.com/48643140/123253964-689a7980-d531-11eb-853e-9fba88073932.png)

**Comment by sinisterseed** [comment]
I'm rather liking the new spacing myself :v .

**Comment by mjr4077au** [comment]
It's not bad, but the main menu should look authentic no matter what.

**Comment by coelckers** [comment]
The spacing needed to be increased for localization. It is so tight that any accents would overlap. Yes, this definitely needs better handling.

**Comment by sinisterseed** [comment]
Yay for a nice, unexpected change.

**Comment by coelckers** [comment]
Fixed in 3512fe8fba96d22f8ba0fbec6d015ca7b0cc7ab4
It will now use the chosen language's character set to set the needed spacing.
