### ISSUE TITLE
Blood -map crashes Raze at command line

### ISSUE THREAD

**Issue by MrRocket** [coelckers/Raze#445]
Thank you for recently fixing the -map parameter, it now works as expected for D3D and SW. 
Although I just noticed that Raze crashes when running Blood with -map from command line. ~ the command works fine in the console however.

**Comment by mjr4077au** [comment]
Thanks for the report, will take a look when I get a chance to do so :)

**Comment by MrRocket** [comment]
Ah, thanks!
I also just now noticed that when loading a map via -map through command line that the music for D3D and SW doesn't play the correct music. Then again, the correct music is played when loading a map/level through the in-game console.

**Comment by coelckers** [comment]
Fixed in 0f7d3d0cbbdb6958f0e7d37dfdd7977d4c3edade

**Comment by MrRocket** [comment]
Nice! 
This fixed the -map loading and music for all the above games. ;)
