### ISSUE TITLE
Both -file and -map needed to run user made .map from command line. 

### ISSUE THREAD

**Issue by MrRocket** [coelckers/Raze#449]
Testing user made maps. It seems that both parameters are needed in order to run a [.map file] from command line..
For example, if I want to run a map file called AlexCity.MAP, I would need to load the file up like so: 
-file AlexCity.MAP -map AlexCity.MAP

I'd imagen though that -file AlexCity.MAP should only need to be what's added, but currently that's not the case.

I've only tested this in D3D so far.. Will post up if I encounter the issue with other supported games.

**Comment by MrRocket** [comment]
Ah, it seems that -map is working to load the file, instead of -file.
But does this mean that -map works for both changing a level AND loading a file?

**Comment by coelckers** [comment]
No. It depends on the directory the file is in. If your map is in the same one as the main game, it will be loaded automatically.
