### ISSUE TITLE
(Duke Nukem 3D) Add option in options menu to enable/disable World Tour's new voice lines

### ISSUE THREAD

**Issue by doc-pacman44** [coelckers/Raze#453]
Just the title. Also, is there a console command I can type in to disable the new voice lines?

**Comment by mjr4077au** [comment]
It should already be there. I don't have WT available on my work PC to have a look but it should be under the sound options.

**Comment by doc-pacman44** [comment]
I know, but for some reason when you enable the original sounds everything sounds muffled, which is why I think it would be cool to add an option for the original duke lines.

**Comment by mjr4077au** [comment]
You're using the original Duke lines, they sound muffled because they're low resolution sounds and OpenAL uses bicubic upsampling by default.

Under Sound > Advanced > OpenAL settings, you can change the resampling from Default to Nearest which will make it sound like what you're after.

**Comment by coelckers** [comment]
The sounds are indeed this bad - the only way to get some higher frequency in is by adding high frequency noise - like what happens when the upsampled data is not properly filtered (i.e. made even worse! :stuck_out_tongue: )

**Comment by sinisterseed** [comment]
True story.

And this is just the tip of the iceberg. Duke's sound system is laughably bad and has various issues with a proper 3D system such as OpenAL. Its reverb was also a cheap hack in the original which required a few rounds of tweaks to get right in the new system, and it still isn't perfect.

Either way, this feature is already present, if you enable it the new lines will be used only when necessary and the rest will be revert to the original files. Force disabling them entirely sounds like a downgrade for the experience the developers intended to me - even of the new voice lines are admittedly mediocre.
