### ISSUE TITLE
[Duke, newrenderer] Assertion failure on E2L7

### ISSUE THREAD

**Issue by Talon1024** [coelckers/Raze#454]
If I walk towards the large orange gear in the slime pit, Raze crashes with an assertion failure if the new renderer is in use:

    raze: ../source/core/nodebuilder/nodebuild.h:294: int FNodeBuilder::FVertexMap::GetBlock(fixed64_t, fixed64_t): Assertion `x >= MinX' failed.

[Here's a saved game.](https://github.com/coelckers/Raze/files/6751201/save0001.zip) To reproduce, just walk forward.

**Comment by coelckers** [comment]
Does not happen anymore. Most likely fixed by 5d3f7947bfad37e759cac125e5cc81eb31becaef
