### ISSUE TITLE
[Question] Running on the Pi4 via Vulkan?

### ISSUE THREAD

**Issue by vanfanel** [coelckers/Raze#456]
Hi there,

I saw an old thread about running RAZE on the Pi4, on the ZDoom forums here:
https://forum.zdoom.org/viewtopic.php?f=357&t=67567
It involves "faking" OpenGL 3.3 via this env variable:

`MESA_GL_VERSION_OVERRIDE=3.3compat ./raze
`
The engine runs for Duke3d (provided I copy the soundfont to ~/.config/raze/soundfonts, or it segfaults).

However, I believe Vulkan would be the way to go on the Pi4.
RAZE seems to be built with Vulkan support here, but selecting the Vulkan API over OpenGL I get an "error creating vulkan surface" message on Raze launch.

Is Vulkan supposed to work on Pi4 with current stable MESA(21.1.2)?

**Comment by vanfanel** [comment]
Also, running RAZE on the Pi4 using OpenGL, Duke3d seems to run at the original framerate, but I have set the framerate to "unlimited" and VSYNC is ON, so it should run at 60FPS matching my videomode refresh rate.

One could argue that this could be due to the Pi4's CPU, but only 25% of the CPU seems to be used according to TOP. Any idea on why is the original framerate being used?

**Comment by alexey-lysiuk** [comment]
> selecting the Vulkan API over OpenGL I get an "error creating vulkan surface" message on Raze launch.

Is it [this message](https://github.com/coelckers/Raze/blob/ab4c18a73a7b396506dca17e8305941df44f905a/source/common/rendering/vulkan/system/vk_device.cpp#L268)?

**Comment by Calinou** [comment]
> One could argue that this could be due to the Pi4's CPU, but only 25% of the CPU seems to be used according to TOP. Any idea on why is the original framerate being used?

Is it 25% of *one CPU core* or 25% of *all CPU cores*? Raze is mostly single-threaded.

**Comment by Cacodemon345** [comment]
It's 25% of all CPU cores.

**Comment by vanfanel** [comment]
@Calinou Yes, it's 25% of all CPUs.

@Cacodemon345 Can you reproduce this issue?

**Comment by Cacodemon345** [comment]
I don't have a Pi4, only an Amlogic S912 SoC.

**Comment by alexey-lysiuk** [comment]
Change [this line](https://github.com/coelckers/Raze/blob/6576adb80b91d9bad93a7d1ac27a25685590fdf4/source/common/platform/posix/sdl/sdlglvideo.cpp#L231) to something like this

```
SDL_bool result = SDL_Vulkan_CreateSurface(Priv::window, instance, surface);
if (result == SDL_FALSE) Printf("SDL_Vulkan_CreateSurface failed with error: %s\n", SDL_GetError());
return result == SDL_TRUE;
```

It may output some useful information about the error.

**Comment by vanfanel** [comment]
I have just rebuilt from latest GIT sources and Vulkan support seems to be gone.
I am building like this:
`
cmake .. -DCMAKE_BUILD_TYPE=Release -DHAVE_VULKAN=true
make -j4
`
How should I select the Vulkan renderer? It has been some time since I built Raze and it seems I didn't document the Vulkan related options...

**Comment by alexey-lysiuk** [comment]
> I have just rebuilt from latest GIT sources and Vulkan support seems to be gone.

Have no idea what you meant by that. Please define 'gone'.

As usual, latest/master/head/whatever have no sense.
Post commit hash if you want to specify a version you are trying to build.

> I am building like this:
> `cmake .. -DCMAKE_BUILD_TYPE=Release -DHAVE_VULKAN=true && make -j4`

Vulkan is enabled by default, so explicit `HAVE_VULKAN` definition is redundant.

> How should I select the Vulkan renderer?

Add `+vid_preferbackend 1` to Raze command line options.

**Comment by vanfanel** [comment]
@alexey-lysiuk By "gone" I meant that the engine would not use the Vulkan backend no matter what options I passed.

The `+vid_preferbackend 1` parameter has worked. I am now able to try to launch the engine in Vulkan mode.

I did the changes to https://github.com/coelckers/Raze/blob/6576adb80b91d9bad93a7d1ac27a25685590fdf4/source/common/platform/posix/sdl/sdlglvideo.cpp#L231 that you suggested.
This is what I get with regards to Vulkan:
```
Using video driver KMSDRM
SDL_Vulkan_CreateSurface failed with error: Vulkan couldn't find a predefined mode for that window size and couldn't create a suitable mode.
Initialization of Vulkan failed: Could not create vulkan surface
```

**Comment by alexey-lysiuk** [comment]
Raze should use native resolution by default in fullscreen mode, `+vid_fullscreen 1` command line option.

Check values of `win_x`, `win_y`,  `win_w`, `win_h` in the following code.
https://github.com/coelckers/Raze/blob/4ac1376b9f55f4b738062841432d205364984c99/source/common/platform/posix/sdl/sdlglvideo.cpp#L143-L146

**Comment by vanfanel** [comment]
@alexey-lysiuk How can I print those values on the console? Standard `printf()` seems to be disabled somehow, `Printf()` doesn't seem to be able to accept integers, etc...

**Comment by alexey-lysiuk** [comment]
On the second thought, just hardcode needed screen size for testing purposes. Change those lines to something like this.
```c++
Priv::window = SDL_CreateWindow(caption, 0, 0, 1920, 1080, windowFlags);
```
You can experiment with window flags as well. For example, hardcode it to `SDL_WINDOW_VULKAN` alone.

**Comment by vanfanel** [comment]
@alexey-lysiuk I got it to run on Vulkan(SDL2/KMSDRM) with these:
```
Priv::window = SDL_CreateWindow(caption, 0, 0, 1366, 768, windowFlags);
Priv::window = SDL_CreateWindow(caption, 0, 0, 640, 480, windowFlags);

``` 

Both the 1366x768 and 640x480 are physical modes supported by my monitor.

So, all in all, what happens is that Raze is trying to set a different physical videomode (well, not Raze itself, but the SDL2 Vulkan code when Raze tries to create a window with an unsupported size).

As I said, how can I print the `win_w` and `win_h` values, please?
`printf()` and `Printf()` don't seem to work for simple integer printing to the console.

**Comment by alexey-lysiuk** [comment]
`win_?` variables are not integers but CVAR objects. In order to output them, you need to use a "dereference".
```c++
Printf("win_x = %i", *win_x);
```

**Comment by vanfanel** [comment]
@alexey-lysiuk Thanks for the explanation. I don't know much about the plus-plus in C++, sorry.

Well, this is what I get:
```

=====================================
win_w = 1092
win_h = 614
=====================================
```

So, it's totally expected that this doesn't work using Vulkan on KMSDRM: as I said, it's not possible to create an arbitrary sized SDL_Window on the KMSDRM backend when using Vulkan, only window sizes with matching resolutions will work.
Any idea on where does this strange 1092x614 comes from? I don't see any setting on the .ini with those values.

**Comment by alexey-lysiuk** [comment]
https://github.com/coelckers/Raze/blob/d9a7465c089cecbef35ea25e361264268c471612/source/common/platform/posix/sdl/sdlglvideo.cpp#L135-L136
It's needed to set defaults for windowed mode. Apparently, that code doesn’t make sense if you cannot use arbitrary window sizes. It would be nice if SDL will ignore width and height in this case, and use native resolution regardless of passed values. How can we get actual screen dimensions in such constrained environment?

**Comment by vanfanel** [comment]
@Calinou Can't SDL_GetCurrentDisplayMode() be used to get the videomode in use?
That should work after initializing SDL2 video (no need to create a window, etc).
There's also  `SDL_GetDesktopDisplayMode() `, which is even better suited for this.

**Comment by alexey-lysiuk** [comment]
Honestly, I don’t want to touch this code myself. If you can make a PR with a minimal change that works for you, we can discuss it.

**Comment by vanfanel** [comment]
@Calinou For that, I would need to know the logic behind something: when is `SDL_WINDOW_FULLSCREEN_DESKTOP` passed in `SDL_CreateWindow()` flags?

Maybe some other dev can shed some light on this. All I can see is this:
https://github.com/coelckers/Raze/blob/d9a7465c089cecbef35ea25e361264268c471612/source/common/platform/posix/sdl/sdlglvideo.cpp#L411
It seems that only some flags are passed to priv::CreateWindow() when a Vulkan window is created, right?

**Comment by alexey-lysiuk** [comment]
`vid_fullscreen` CVAR can be used there to pass the corresponding flag.

**Comment by vanfanel** [comment]
@alexey-lysiuk 

I have added it on this PR:
https://github.com/coelckers/Raze/pull/486

**Comment by vanfanel** [comment]
Raze now works with Vulkan on SDL2/KMSDRM.
However, it doesn't work on the Pi4 using this confuguration: I can see the intro animation and tittle screen, but as soon as a I try to start a level the game crashes:

```
Using video driver KMSDRM
Vulkan device: V3D 4.2
Vulkan device type: integrated gpu                                                                                                    
Vulkan version: 1.0.155 (api) 21.1.4 (driver)
Max. texture size: 4096
Max. uniform buffer range: 134217728
Min. uniform buffer offset alignment: 32
Resolution: 1360 x 768
player 1 of 1 (1 nodes)
[ALSOFT] (EE) mmap commit error: Broken pipe
[ALSOFT] (EE) mmap commit error: Broken pipe
[ALSOFT] (EE) mmap commit error: Broken pipe
[ALSOFT] (EE) mmap commit error: Broken pipe
[ALSOFT] (EE) mmap commit error: Broken pipe
[ALSOFT] (EE) mmap commit error: Broken pipe
[ALSOFT] (EE) mmap commit error: Broken pipe
[ALSOFT] (EE) mmap commit error: Broken pipe
[ALSOFT] (EE) mmap commit error: Broken pipe
[ALSOFT] (EE) mmap commit error: Broken pipe
[ALSOFT] (EE) mmap commit error: Broken pipe
[ALSOFT] (EE) mmap commit error: Broken pipe
[ALSOFT] (EE) mmap commit error: Broken pipe
[ALSOFT] (EE) mmap commit error: Broken pipe
[ALSOFT] (EE) mmap commit error: Broken pipe
[ALSOFT] (EE) mmap commit error: Broken pipe
[ALSOFT] (EE) mmap commit error: Broken pipe
[ALSOFT] (EE) mmap commit error: Broken pipe
[ALSOFT] (EE) mmap commit error: Broken pipe
[ALSOFT] (EE) mmap commit error: Broken pipe
[ALSOFT] (EE) mmap commit error: Broken pipe
[ALSOFT] (EE) mmap commit error: Broken pipe
[ALSOFT] (EE) mmap commit error: Broken pipe
[ALSOFT] (EE) mmap commit error: Broken pipe
[ALSOFT] (EE) mmap commit error: Broken pipe
[ALSOFT] (EE) mmap commit error: Broken pipe
[ALSOFT] (EE) mmap commit error: Broken pipe
[ALSOFT] (EE) mmap commit error: Broken pipe
[ALSOFT] (EE) mmap commit error: Broken pipe
[ALSOFT] (EE) mmap commit error: Broken pipe
[ALSOFT] (EE) mmap commit error: Broken pipe
[ALSOFT] (EE) mmap commit error: Broken pipe
[ALSOFT] (EE) mmap commit error: Broken pipe
[ALSOFT] (EE) mmap commit error: Broken pipe
[ALSOFT] (EE) mmap commit error: Broken pipe
[ALSOFT] (EE) mmap commit error: Broken pipe
[ALSOFT] (EE) mmap commit error: Broken pipe
[ALSOFT] (EE) mmap commit error: Broken pipe
[ALSOFT] (EE) mmap commit error: Broken pipe
[ALSOFT] (EE) mmap commit error: Broken pipe
[ALSOFT] (EE) mmap commit error: Broken pipe
[ALSOFT] (EE) mmap commit error: Broken pipe
[ALSOFT] (EE) mmap commit error: Broken pipe
[ALSOFT] (EE) mmap commit error: Broken pipe
[ALSOFT] (EE) mmap commit error: Broken pipe
[ALSOFT] (EE) mmap commit error: Broken pipe
[ALSOFT] (EE) mmap commit error: Broken pipe
[ALSOFT] (EE) mmap commit error: Broken pipe
[ALSOFT] (EE) mmap commit error: Broken pipe
[ALSOFT] (EE) mmap commit error: Broken pipe
[ALSOFT] (EE) mmap commit error: Broken pipe
[ALSOFT] (EE) mmap commit error: Broken pipe
[ALSOFT] (EE) mmap commit error: Broken pipe
[ALSOFT] (EE) mmap commit error: Broken pipe
[ALSOFT] (EE) mmap commit error: Broken pipe
[ALSOFT] (EE) mmap commit error: Broken pipe
[ALSOFT] (EE) mmap commit error: Broken pipe
[ALSOFT] (EE) mmap commit error: Broken pipe
[ALSOFT] (EE) mmap commit error: Broken pipe
[ALSOFT] (EE) mmap commit error: Broken pipe
[ALSOFT] (EE) mmap commit error: Broken pipe
[ALSOFT] (EE) mmap commit error: Broken pipe
[ALSOFT] (EE) mmap commit error: Broken pipe
[ALSOFT] (EE) mmap commit error: Broken pipe
[ALSOFT] (EE) mmap commit error: Broken pipe
[ALSOFT] (EE) mmap commit error: Broken pipe
[ALSOFT] (EE) mmap commit error: Broken pipe
[ALSOFT] (EE) mmap commit error: Broken pipe
[ALSOFT] (EE) mmap commit error: Broken pipe
[ALSOFT] (EE) mmap commit error: Broken pipe
[ALSOFT] (EE) mmap commit error: Broken pipe
[ALSOFT] (EE) mmap commit error: Broken pipe
[ALSOFT] (EE) mmap commit error: Broken pipe
[ALSOFT] (EE) mmap commit error: Broken pipe
[ALSOFT] (EE) mmap commit error: Broken pipe
[ALSOFT] (EE) mmap commit error: Broken pipe
[ALSOFT] (EE) mmap commit error: Broken pipe
[ALSOFT] (EE) mmap commit error: Broken pipe
[ALSOFT] (EE) mmap commit error: Broken pipe
[ALSOFT] (EE) mmap commit error: Broken pipe
[ALSOFT] (EE) mmap commit error: Broken pipe
[ALSOFT] (EE) mmap commit error: Broken pipe
[ALSOFT] (EE) mmap commit error: Broken pipe
Failed to allocate device memory for BO
[ALSOFT] (EE) mmap commit error: Broken pipe
[ALSOFT] (EE) mmap commit error: Broken pipe
[ALSOFT] (EE) mmap commit error: Broken pipe
E1L1: Hollywood Holocaust
                                                                                                                                      
Could not end command buffer recording: out of host memory
```

**Comment by alexey-lysiuk** [comment]
It’s out-of-VRAM case. Do you know the maximum amount of RAM that can used by GPU?

**Comment by vanfanel** [comment]
@Calinou This is what the Pi engineers say about the Pi4 GPU RAM:
```

Setting gpu_mem sets the amount of memory assigned to the VideoCore VPU (Vector Processing Unit). That is responsible for codecs, camera, legacy framebuffer, and the firmware GLES driver on Pi0-3. This region has to be in the bottom 1G of RAM.

On Pi4 the V3D block has an IOMMU, so it can access all of memory, and Linux deals with the allocation out of ARM memory. And when using either DRM/KMS driver (which is default on Pi4), the display buffers come out of the CMA (Contiguous Memory Allocator) heap. Again the CMA heap has to be in the bottom 1G of RAM.

Setting gpu_mem to insane figures gains nothing on a Pi4. Setting the combined value of gpu_mem and CMA to a value greater than 1G (minus a bit) will result in a system that won't boot.

```

So I understand it's 1GB of RAM max for the GPU to use.

**Comment by alexey-lysiuk** [comment]
Is it possible to track RAM and VRAM usage when Raze is running? I would like to be sure that it was out-of-memory indeed.

**Comment by vanfanel** [comment]
@Calinou Seems like it.

This is my idle system:

```
total        used        free      shared  buff/cache   available
Mem:          1.8Gi        56Mi       1.7Gi       0.0Ki        28Mi       1.7Gi
Swap:            0B          0B          0B

```

Then, when I run the engine, just after I am about to start a level, RAM usage becomes HUGE.
This is when the engine crashes:

```
total        used        free      shared  buff/cache   available
Mem:          1.8Gi       248Mi       250Mi       1.3Gi       1.3Gi       274Mi
Swap:            0B          0B          0B

```
As for GPU RAM (it's not VRAM at all), it can go up to 1GB. No more than that. I don't think it can be monitorized, but the GPU RAM is taken from the system RAM on a Pi, which explains where the missing memory is on the second `free -h` output I just pasted.

**Comment by alexey-lysiuk** [comment]
I have no idea how Duke3D E1L1 may exceed 1 GB. If you want to figure out what is consuming so much RAM, you need to debug level loading, and maybe rendering of the first frame.
In theory, `strace` can help to track all memory allocations. Although, it would be really hard to match them with source code.

**Comment by vanfanel** [comment]
@Calinou Is there a way to run the game without a hardware renderer?
I mean: simply use a software renderer, and use SDL2 to scale fullscreen with whatever API SDL2 uses.
That way I could at least rule out Vulkan as the RAM devourer.

**Comment by alexey-lysiuk** [comment]
No, there is no pure software renderer.

You can try to disable precaching by adding `+r_precache 0` to command line. This should reduce memory footprint when level is just loaded.

**Comment by vanfanel** [comment]
@Calinou Using `+r_precache 0` the game runs well into E1L1, and only like 150MB are used.

So it's definitively the precache code, it's taking +1GB!

**Comment by mjr4077au** [comment]
I don't know if the pre-caching code consuming so much memory is necessarily a bug but I wouldn't have expected it to take 1GB with stock assets either.

**Comment by sinisterseed** [comment]
Which is why I think this is a bug or something as well. Such a game, even in Vulkan which consumes more memory than GL, should not be eating a whole gigabyte of VRAM, especially not wkth stock assets.

**Comment by arrowgent** [comment]
i wish i could jump in and help you guys test with my RPI4B 4GB
but i have _avoided compiling the Mesa V3D vulkan_ source.  im still using stock provided by raspbian

some useful info for you, version controlling in mesa
https://mesamatrix.net/

taking note that only vulkan 1.0 is fully supported currently.
so hopefully avoiding using code that is v1.1+ that (potentially) breaks hardware compatibility

note that yes, on a 4 core system, 25% cpu usage means 100% of one core is being used
pay attention to that difference in top/htop.

in my experience on the pi4, it can be preferable to lower your desktop resolution or game resolution to 1280x720 for smoother gameplay at 50/60hz.  most of the games (quake1,q2,dosbox,retroarch,etc) run fine at 1080p.  if youre playing on a low power device its time to take that realization into account and compensate by lowering your resolution
(and my rpi4b is overclocked)

i only set the shared `gpu_mem` to 192mb, which is above stock settings.
ive tested 256mb, and some report 512mb or higher is a waste
i suppose that would depend greatly on what you are trying to run, which games, or gpu intensive processes
and if that causes buffering, which it shouldnt for most of these games.


hopefully in the future, it can be possible to create a "LZraze" style of fork for rapsberry pi
such as this one exists already: https://github.com/drfrag666/gzdoom
but, meanwhile Raze is still a WIP and i for one **thank the efforts being put into its progression**
