### ISSUE TITLE
[Blood] Incorrect handling of Sawed-Off clip count in "true-fullscreen" HUD.

### ISSUE THREAD

**Issue by Shockwave508** [coelckers/Raze#457]
When using the true-fullscreen HUD (one notch down from being HUDless), something strange happens with the Sawed-Off when clip counts are shown.

1) Fire exactly one shell with the primary fire, before leaving the current level. (shows as 1/###)
2) Upon loading the next level, there are two shells in the chamber, yet the clip count still shows as 1/###.
3) This issue doesn't go away, not even after emptying both barrels simultaneously with the alt-fire.

**Comment by mjr4077au** [comment]
I can't replicate this. What version are you running? Could you perhaps test a devbuild for me? https://devbuilds.drdteam.org/raze/

**Comment by mjr4077au** [comment]
@Shockwave508 closing due to non-contact. If you can still replicate this, please re-open the issue and we'll take a further look 😁
