### ISSUE TITLE
[Blood]: Make enabling/disabling CD audio music not require an engine restart, or at the very least advise a restart is required?

### ISSUE THREAD

**Issue by mjr4077au** [coelckers/Raze#458]

**Comment by coelckers** [comment]
You do not need an engine restart. It just doesn't restart the music immediately but only for the next time a song is started.

**Comment by mjr4077au** [comment]
Can it be made to do it upon restarting the sound engine like for when you change the resampler? It just causes a bit of end user confusion, that's all

**Comment by coelckers** [comment]
No. The problem simply is that the sound backend has no means to get the alternative song anymore - the decisions are all being made in the game code, which, depending on this setting, passes a different file name to the backend. And the handlers in the games are quite different so it cannot be generalized.

**Comment by mjr4077au** [comment]
No worries boss, thanks for the insight on this 😁
