### ISSUE TITLE
[Redneck Rampage] Pissin' Contest (Deathmatch) is in single-player episode select.

### ISSUE THREAD

**Issue by Shockwave508** [coelckers/Raze#461]
In Redneck Rampage, the Pissin' Contest deathmatch maps are erroneously-available on the single-player episode select screen.

**Comment by mjr4077au** [comment]
@coelckers any ideas on how best to handle this? There's nothing in the CON scripts that can be picked up to define whether a volume is multiplayer or not to correctly apply a `VF_HIDEFROMSP` flag to it.

I've gone through RR's source for an indication of what it's doing but I literally have zero clue as their flag to do this (`EF_HIDEFROMSP`) isn't being used and I see no other hard-coded workarounds. Whatever they've done though, it's only for RR, NAM and WW2GI both display the multiplayer volumes in the main menu.

**Comment by mjr4077au** [comment]
Only way I can think to do this would be to extend the `FStartupInfo` struct with something to hold the names of each game's multiplayer episodes/volumes, then hide it when parsing the CON file. If the episode/volume is renamed, the slot will then show up in the menu so mods will keep working.

Apparently it was hidden in the original DOS release, but whether that was a hard-coded workaround or not, I'm not sure... https://www.youtube.com/watch?v=MlFP8arceGg&t=50s

**Comment by coelckers** [comment]
That's the problem here. I undid all the other shit regarding level progression as well so that there is no more 7 map limit per episode. Considering that Duke never had to hack in such shit it's a bit weird that RR went out of its way to screw this up - to the point where the game broke (the E1 -> E2 transition was so poorly done that it resulted in E2L2 being skipped by accident.)
The menu stuff is just another side of the same coin.

**Comment by Gaerzi** [comment]
The question is, is it really a problem that the deathmatch episode can be visited from single player?

**Comment by mjr4077au** [comment]
For me, it personally doesn't matter but it could be confusing for new players. This was easy though to fix for Blood, it's just harder here with Duke-based games as there's no declaration that the episode is multilayer or not.
