### ISSUE TITLE
[Powerslave/Exhumed] Option to show clip count is absent.

### ISSUE THREAD

**Issue by Shockwave508** [coelckers/Raze#463]
Unlike other supported games with clip-fed weapons, Powerslave/Exhumed doesn't have the option to show you whatever rounds are left in the current clip.

**Comment by mjr4077au** [comment]
![Exhumed_0002](https://user-images.githubusercontent.com/48643140/125959073-15a1368a-ada9-4819-8cf7-5ce52357d224.png)
