### ISSUE TITLE
[Blood] Problem with custom animated voxels

### ISSUE THREAD

**Issue by Dzierzan** [coelckers/Raze#466]
When using the master branch Blood Voxel Pack, animated voxels in Raze 1.1.2 are not animated. Works fine in NBlood and BloodGDX.

**Comment by coelckers** [comment]
Can you point me to an example and where to test it?

**Comment by Dzierzan** [comment]
E4M1, first tesla coil voxels.

**Comment by mjr4077au** [comment]
Is this with our new renderer or with Polymost? I've observed animated voxels not animating for the new renderer, but Polymost seems fine.

**Comment by Dzierzan** [comment]
I guess the new one. I might have left it turned on.

**Comment by coelckers** [comment]
fixed in beeb89fa267151578445369ebd6c6ed63ae15aaa
