### ISSUE TITLE
[SW]: Render glitch in new renderer.

### ISSUE THREAD

**Issue by mjr4077au** [coelckers/Raze#467]
![ShadowWarrior_0001](https://user-images.githubusercontent.com/48643140/125177644-ca8cfb80-e220-11eb-9724-16e53c972c0d.png)

[save0001.zip (rename to .dsave)](https://github.com/coelckers/Raze/files/6796031/save0001.zip)

**Comment by coelckers** [comment]
fixed in 054d81fc8eb0733c6f82b6f200c9c52d99243b73
