### ISSUE TITLE
[RR]: Crash with new renderer on 1st Pissin' Contest level

### ISSUE THREAD

**Issue by mjr4077au** [coelckers/Raze#470]
Crash doesn't seem to happen on a reloaded save, but save of location is here: [save0000.zip](https://github.com/coelckers/Raze/files/6796877/save0000.zip)

Debugger output:

![image](https://user-images.githubusercontent.com/48643140/125194509-06fa3f00-e295-11eb-9697-78cc048da3c7.png)

Likely something to do with this door nearby?

![Redneck_0001](https://user-images.githubusercontent.com/48643140/125194529-17121e80-e295-11eb-9efa-739c542c17f1.png)
![Redneck_0002](https://user-images.githubusercontent.com/48643140/125194530-1a0d0f00-e295-11eb-9e5a-03b68b2a97e3.png)

**Comment by coelckers** [comment]
It's just another triangulation problem. Build's sectors can be so messed up that both of the triangulators I use are not capable of dealing with the shit getting thrown at them.

**Comment by mjr4077au** [comment]
It's a shame that maps of this quality are in released games... If it was a community map at least there could be push-back 😢

**Comment by coelckers** [comment]
It's not the maps, it's the engine. Build's way of doing swinging doors is disastrously shitty and prone to creating badly formed sectors as a result. Around these places, virtually all maps have some issues with triangulation, some more, some less.

**Comment by coelckers** [comment]
After finding a particularly gross occurence of a similar render issue on Last Warrior's map 2 I found out that some walls have bad nextsector references stored. After validating these upon map load the problems here also went away.
