### ISSUE TITLE
[Duke]: Dodgy sign in E2L1 partially hidden again in new renderer

### ISSUE THREAD

**Issue by mjr4077au** [coelckers/Raze#471]
This sign is notoriously bad and is known to not be placed right, but it does render in the software renderer correct and now in our Polymost code since you applied some depth bias offsetting.

Polymost:
![image](https://user-images.githubusercontent.com/48643140/125271404-0ffb1700-e34e-11eb-9237-8bae86f34dca.png)

New Renderer:
![image](https://user-images.githubusercontent.com/48643140/125271488-299c5e80-e34e-11eb-9bbc-dbef564523fe.png)

**Comment by coelckers** [comment]
I think the only proper fix here would be to add a map hack to move the sign to its proper place. Depth hackery has the unpleasant effect to cause glitches elsewhere.

**Comment by mjr4077au** [comment]
That sounds more than appropriate to me.

**Comment by sinisterseed** [comment]
Same, in fact I was just gonna suggest that this morning myself. Hacking around actual map errors will always come with unintended side-effects, so let's just make a map hack for this and move it in its correct place.

**Comment by sinisterseed** [comment]
As in, where this is?

Here:

![Duke_0000](https://user-images.githubusercontent.com/57503728/125487333-946fd304-0104-4a96-9dee-d38237bdb8eb.png)

**Comment by mjr4077au** [comment]
Fixed in develop branch.
