### ISSUE TITLE
[Platoon Leader]: Skydome is black in map `plt_e3l1`

### ISSUE THREAD

**Issue by mjr4077au** [coelckers/Raze#476]
Polymost:
![WW2GI_0001](https://user-images.githubusercontent.com/48643140/126020891-f12b728f-e87c-4041-8b05-6a68d9c10480.png)

New Renderer:
![WW2GI_0000](https://user-images.githubusercontent.com/48643140/126020892-efc9ac1d-2215-47fc-a796-36b176904b62.png)

**Comment by coelckers** [comment]
This is yet again the sky wraparound effect that our sky renderer cannot really emulate as it is not determinable whether the sky is supposed to wrap around or just to be shifted.

**Comment by coelckers** [comment]
Added some offsetting adjustment for this sky,
