### ISSUE TITLE
[Duke]: Skybox visible through walls upon closing doors.

### ISSUE THREAD

**Issue by mjr4077au** [coelckers/Raze#477]
Probably already known about, we had some dicussions on Discord about how poor the doors are and how they're affecting the new renderer.

https://user-images.githubusercontent.com/48643140/126022959-4d5b808b-9c65-430d-ba0e-9bce1aeaa50f.mp4

**Comment by coelckers** [comment]
This is the exact same thing as the vehicle in SW's first map (#467), there's problems with overlapping map parts causing out-of-order rendering.
