### ISSUE TITLE
[Blood] Pre-Cache doesn't work

### ISSUE THREAD

**Issue by Tasosgemah** [coelckers/Raze#478]
When i play Blood after a restart (no mods, just the main game), i get sudden pauses sometimes when i visit a new room, open a new door, fire with a weapon for the first time. It's not common but when it happens it's very sudden. 

These pauses clear up after playing for a while and all graphics have been cached. But after i restart the PC, they come back.

This is very noticeable with Blood. With other build games i haven't noticed as much of a problem or the pauses are very subtle.

**Comment by coelckers** [comment]
You already reported this with #474
