### ISSUE TITLE
[Duke]: Voxelised security cameras show in viewport in new renderer

### ISSUE THREAD

**Issue by mjr4077au** [coelckers/Raze#479]
Voxel pack: https://github.com/NightFright2k19/duke3d_voxelpack

Polymost:
![Duke_0000](https://user-images.githubusercontent.com/48643140/126026590-d309d3e0-145c-41fc-aec4-f66e0eedc76b.png)

New Renderer:
![Duke_0001](https://user-images.githubusercontent.com/48643140/126026595-61c6d0bc-c15f-46c5-a54d-4f87a7a94824.png)

**Comment by coelckers** [comment]
fixed in 4ac224ba8c329080fe1eead91cd3f004a48855dc
