### ISSUE TITLE
Garbled voxel in E4L1's freezer

### ISSUE THREAD

**Issue by Phredreeke** [coelckers/Raze#481]
Inside the freezer in E4L1 there's a button behind a bloody handprint. Normally this is invisible but with voxels enabled you can see the back of the button albeit garbled (switching renderers to Polymost makes it solid)
![Duke_0050](https://user-images.githubusercontent.com/5611707/126038300-513bdafd-41c4-4466-9bfa-f66e4017cedb.png)

Edit: Looking at the maphack that voxel is disabled with the notmd command, so I assume this is Raze not implementing notmd?

**Comment by coelckers** [comment]
fixed in efc80fa65de70747c29f226c100d8239e08cd803
