### ISSUE TITLE
[Blood]: Need to fix issues loading some mods by drag-and-drop.

### ISSUE THREAD

**Issue by mjr4077au** [coelckers/Raze#483]
If I take [Death Wish](https://www.moddb.com/mods/death-wish-for-blood/downloads) and drag and drop the downloaded ZIP file, it works fine.

If I take [The Way of Ira](https://www.moddb.com/mods/the-way-of-ira/downloads) and try to do the same thing, `dbLoadMap()` fails with `Error opening map file IE1M01.map`.

Both mods have a single folder inside that contains the mod, yet Death Wish works and Ira doesn't. However, if I repack Ira so that all of its contents are in the root of the zip file, then it works. It shouldn't be necessary if Death Wish also has a subfolder but it works.

This issue also affects NoOne's [No Hope in Sight](https://www.moddb.com/mods/no-hope-in-sight-demo) mod as well.

**Comment by coelckers** [comment]
The problem here was that te zip file does not contain a directory record for its root folder. That makes the root folder eliminator fold.

Fixed in c51c6fa524b6de1e55d7a35d506e791e2e69b920

**Comment by mjr4077au** [comment]
There was no way I was going to get this 😅.

The only issue now is before with a mod like Ira, it's intros would load but not the map. Now the maps load but not the intros. The INI for Ira says has the path for the intro as `IRA/ie1.smk` instead of just `ie1.smk`. Can we account for this at all for the sake of released mods?
