### ISSUE TITLE
Sometimes, tiles aren't getting replaced properly.

### ISSUE THREAD

**Issue by mjr4077au** [coelckers/Raze#487]
Original report came from Phredreeke, I can replicate it but haven't been able to resolve it.

Load one of Phredreeke's packs such as his [upscale pack](https://www.moddb.com/addons/duke-nukem-3d-upscale-pack-13) or [ERP](https://www.moddb.com/downloads/duke-nukem-enhanced-resource-pack-for-raze) and for the pigcop, it appears a tile isn't being replaced. Phredreeke has indicated it's tile 2025.

https://user-images.githubusercontent.com/48643140/126858186-c409abef-32ff-4f40-99aa-5f616587877e.mp4

From the video, we can see a frame for the pigcop reverts to standard. I can confirm the tile is being loaded as a replacement in `AddReplacement()` and also that the issue only appears to be on new loads. If you save the game, close out, re-open and reload, it seems to work OK.

**Comment by coelckers** [comment]
fixed in dfb18ef9a9d630f6cb04a2280889d712f248a3cf
