### ISSUE TITLE
[Blood]: `mario` cheat is not working.

### ISSUE THREAD

**Issue by mjr4077au** [coelckers/Raze#489]
Issue here is that the spacebar input is getting eaten before the cheat handler can get to it. `mario1 2` should take you to E1M2, but the only way to get there with the cheat for us is to type `mario102`.

**Comment by sinisterseed** [comment]
Honestly, as long as it works with such a simple workaround, if it even can be considered as such, it good enough IMO.

**Comment by mjr4077au** [comment]
The problem is no one uses it like that because they didn't in the original game, then they either just assume Raze is broken or jank, or have to ask about it unnecesarily. If we can make it work 1:1, we should and I don't think it'd take a tonne of work either.

**Comment by sinisterseed** [comment]
Never said we shouldn't, it just looked too nitpicky at first even for the Master Nitpicker in me :v .

**Comment by coelckers** [comment]
You can enter cheats via the chat editor, but have to prefix them with '#' so they can be filtered out before the chat handler does its work. This should cover most of Blood's needs.

I very rarely use cheats anyway, Everything that is important can be done via direct CCMDs that do not have funny names.

**Comment by sinisterseed** [comment]
Same here.

god, noclip, levelwarp cover 98% of my needs. I input them largely for testing purposes and nothing else.

**Comment by mjr4077au** [comment]
I personally don't use these cheats either and just go through via the console, it's just one that's come up a few times to me from players who still use the original cheats. If it can be entered from the chat in the original format, albeit with a prefix, that should be fine.

**Comment by mjr4077au** [comment]
This will still need some work. Even via the chat box and prefixed with a hash, `#mario102` to get to the 2nd level works but `#mario1 2` doesn't. If we're just going to say it doesn't work, fair enough, but if we can pick up the space like the original game then I think we should.

**Comment by coelckers** [comment]
Fixed in fa586d6d7c1513761f704ec8433e4c1880f2a83f and 3864dcfc17e569a0eb0ab7d85989c69d2d6f0d65
