### ISSUE TITLE
[Duke]: Broken since 3864dcfc17e569a0eb0ab7d85989c69d2d6f0d65

### ISSUE THREAD

**Issue by mjr4077au** [coelckers/Raze#491]
This commit to adapt cheat input handler to treat spaces as '0' when entering parts of numeric fields breaks Duke. As soon as you load the game and try to play, you can't jump anymore. Further to this, pressing spacebar 5 times kills the player.

**Comment by coelckers** [comment]
Fixed in a12dfbe1d8ceff283e3e788f4bcc03970dd4e1f8
