### ISSUE TITLE
[Blood]: Dragging and dropping Ira mod doesn't play intros anymore since c51c6fa524b6de1e55d7a35d506e791e2e69b920.

### ISSUE THREAD

**Issue by mjr4077au** [coelckers/Raze#492]
From #483.

Taking [The Way of Ira](https://www.moddb.com/mods/the-way-of-ira/downloads), it used to play intros but not maps. Since c51c6fa524b6de1e55d7a35d506e791e2e69b920, it now won't play intros but finds the maps OK.

I believe this is because the modder has specified the cutscenes as `CutSceneA = IRA/ie1.smk` instead of simply `CutSceneA = ie1.smk`, but it did work before and if we could accomodate it so mods don't need fixing and just work, it'll be better for us so that we don't look broken or something.

**Comment by coelckers** [comment]
It worked before because the 'ira' folder was not dropped.
Sigh, these old DOS devs really went sloppy with their stuff...
