### ISSUE TITLE
[Duke/RR/possibly others] Ambiguous palette remapping

### ISSUE THREAD

**Issue by Phredreeke** [coelckers/Raze#495]
![Duke_0065](https://user-images.githubusercontent.com/5611707/127722709-cad46c26-f945-4122-ae99-2faf94afa2b9.png)
This is a screenshot of my ERP, running with voxels turned off. The keycard panel has black parts colored yellow.

The issue here comes from the Duke Nukem 3D palette having duplicate colors in it. I've taken the Duke3D palette and draw a red box around the two pairs of colors that are causing the issue. Both ramps have 0,0,0 and 4,4,4 as its darkest colors. On its own this is not a problem, but when palette 23 is applied, the second of these is turned yellow.
![dukepal](https://user-images.githubusercontent.com/5611707/127722844-60de7bc7-702a-450d-86af-36ab84656443.png)

Now I never encountered this problem with EDuke32, presumably its color mapping works differently. I suspect this won't just affect indexed hightiles but also regular tiles defined through tilefromtexture. Raze isn't doing anything wrong as such, it all comes from the game's stupid palette =P For me mapping 0,0,0 and 4,4,4 to the first two indices would be the most convenient solution (because it mirrors what EDuke32 and also Paintshop Pro does) but I'm open to other solutions

**Comment by coelckers** [comment]
This surely can be changed to pick the other color for consistency. 
While it won't help for the other ports, one thing you can do is to use Doom's patch format for such graphics which is unpaletted and will map 1:1 to the game palette. I used this for the international font extensions, for example.

**Comment by coelckers** [comment]
Fixed in a5e3a85c988491ea9ff640a08df572b9ea9251a2
