### ISSUE TITLE
[Duke Expansions] Skip directly to difficulty select upon starting a new game, to avoid vanilla episode conflicts.

### ISSUE THREAD

**Issue by Shockwave508** [coelckers/Raze#496]
When loading Nuclear Winter, Duke Caribbean, or Duke It Out in D.C., is it possible to jump directly to the difficulty select screen upon selecting New Game? This would mean skipping the Select Episode screen entirely in these expansions, since all three erroneously let you select vanilla Duke episodes, and Caribbean's "second" episode is Vacation Dukematch, which would be completely useless to solo players.

**Comment by coelckers** [comment]
This was already implemented for the next release.
