### ISSUE TITLE
[Powerslave/Exhumed, Raze v1.1.3] Status bar code causes VM aborts in certain situations.

### ISSUE THREAD

**Issue by Shockwave508** [coelckers/Raze#498]
Upon dying, or running out of ammo for a weapon, a VM abort occurs, the errors of which point at the statusbar code. The attached screenshot was from throwing the only grenade I had, in the first level in the game.
![Screenshot_2021-07-31-17-56-16-463_com opentouchgaming razetouch](https://user-images.githubusercontent.com/32436386/127754249-82f9f595-b24e-4195-aa0b-7d2be752ada9.jpg)

**Comment by coelckers** [comment]
Already fixed in 20bffbd94d6690e4448d3a0506ab128bc70b763c
