### ISSUE TITLE
new renderer crashes in shadow warrior

### ISSUE THREAD

**Issue by tomatothesaddo** [coelckers/Raze#500]
on the map "bath house" there is an area where the game will sometimes 
[save0000.zip](https://github.com/coelckers/Raze/files/6927617/save0000.zip)
crash when using the new renderer.

**Comment by coelckers** [comment]
No crash for me. What do I have to do to make it?

**Comment by tomatothesaddo** [comment]
I tried to reproduce the issue and couldn’t get it to happen again, sorry for late response I completely forgot about it

**Comment by mjr4077au** [comment]
> I tried to reproduce the issue and couldn’t get it to happen again, sorry for late response I completely forgot about it

That's ok, life gets busy and whatnot. If you can make it occur again, please feel free to re-open the ticket with some more info so we can take a look :)
