### ISSUE TITLE
Supersampling in Raze

### ISSUE THREAD

**Issue by Kappa971** [coelckers/Raze#502]
Hi. I tried to activate the Multisampling present in Raze but, even if set to 32x, I notice little difference, it doesn't seem very effective.
In Ion Fury (with Eduke32) I can force anti-aliasing from Nvidia drivers, setting Antialiasing - Setting 8x and Antialiasing - Transparency 8x supersample but in Raze it doesn't work

**Comment by Kappa971** [comment]
Maybe I should open a new issue regarding the performance in Vulkan ... Those in OpenGL are very good (even if they are about 1/3 of those of Rednukem) but I don't think it is normal that Vulkan works like this.

**Comment by coelckers** [comment]
Don't get hung up on the high frame rate in RedNukem. That comes from Raze not directly rendering to the screen but to an intermediate buffer so it can apply postprocessing. The 0.5 ms that normally costs are enough to drop such insanely high frame rates into seemingly much lower regions.
600 fps are roughly 1.5 ms while 2000 fps are 0.5 ms. This stuff quickly evens out when the workload increases.

About Vulkan, it's rather simple. The engine currently does not use static vertex buffers for anything. Polymost can't and the new renderer is not finished yet. Vulkan is an API that apparently doesn't like it much when the vertex buffer gets constantly updated, 
OpenGL on NVidia is more forgiving.

About supersampling, 2x supersampling can be achieved by setting the scale factor in the video mode menu to 2.0.

Regarding these driver side settings, I am not surprised that these don't do anything. The scene gets rendered to an internal frame buffer and then copied from there to the screen. So whatever the driver receives for potential upscaling is plain and simply unsuitable.
