### ISSUE TITLE
[Blood] - dropping into water while holding active TNT causes it to be stuck in your hands

### ISSUE THREAD

**Issue by Flargee** [coelckers/Raze#503]
The TNT will drop as intended, but the player will be stuck holding the TNT in first-person until it explodes, rather than transitioning to holstered as intended.

This does not occur on DOS.

https://user-images.githubusercontent.com/67973708/129017504-0f6205f0-8693-487d-aaf8-815612af43d2.mp4

**Comment by carnivoroussociety** [comment]
Issue is caused by [this commit in question](https://github.com/nukeykt/NBlood/commit/30088482a85ac1f054aabe222486f8da376c9167)

**Comment by mjr4077au** [comment]
We probably just need to add `pPlayer->isUnderwater` to @CommonLoon102's commit, I imagine.

**Comment by carnivoroussociety** [comment]
IMO the issue is the `if (VanillaMode())` line itself. Putting away an ignited tnt will fail the `if (pPlayer->input.newWeapon == 6)` line because it is not switching to 6. My fix was to just do this
```
if (!VanillaMode() && (pPlayer->input.newWeapon == 7))
{
  pPlayer->weaponState = 2;
  StartQAV(pPlayer, 17, -1, 0);
  WeaponRaise(pPlayer);
  return;
}
StartQAV(pPlayer, 7, -1, 0);
break;
```

**Comment by mjr4077au** [comment]
I was going to suggest changing that `if (VanillaMode())` line to `if (VanillaMode() || pPlayer->isUnderwater)`, but what you've suggested is possibly better.

Feel free to send a PR if you like, I can test and merge it in.

**Comment by carnivoroussociety** [comment]
Thanks, please test and confirm that this fixes it. I should note that the same bug happens with the spray can alt fire (equip spray can, alt fire ignite it, hold down throw and jump into water). As this is an authentic dos bug I've added some vanilla checks to the spray can fix.

https://github.com/coelckers/Raze/issues/503
