### ISSUE TITLE
[Shadow Warrior]: episode name displayed in automap is always one higher than supposed to be

### ISSUE THREAD

**Issue by ninjakitty844** [coelckers/Raze#513]
The episode name displayed in automap is always one higher than it is supposed to be. So if you're in Enter The Wang it displays Code of Honor, if you're in Code of Honor it displays no name at all (since there is no episode after that), etc

**Comment by coelckers** [comment]
fixed in 90b75247069fc058306ac345442cdc5ee1679b98
