### ISSUE TITLE
[Shadow Warrior (maybe other games)]: more menu options than actually exist in episode select with mouseenabled = true

### ISSUE THREAD

**Issue by ninjakitty844** [coelckers/Raze#514]
If mouse enabled in menus is set to true (not touchscreen mode) then there are extra options in the episode select screen that do nothing. (basically all lines of text are options, so the descriptive text under the episode names become options that do nothing)

**Comment by coelckers** [comment]
fixed in 68387cd59e6848660d4153d24d170b0d9bccbd7d
