### ISSUE TITLE
[Blood] Teleport destination angle is broke

### ISSUE THREAD

**Issue by carnivoroussociety** [coelckers/Raze#515]
Raze will not correctly use the destination sprite for a kSectorTeleport trigger. I have tested the behavior in NBlood/BloodGDX and can confirm that Raze is broken in this case.

All three source ports were using the Death Wish level DWE1M3, with Raze using completely default settings on first launch. I have tried changing syncinput, as well as cl_interpolate to no avail.

https://user-images.githubusercontent.com/38839485/130270670-dd4bb994-033b-44d5-b0f2-9bfd26fd3745.mp4

https://user-images.githubusercontent.com/38839485/130270836-e2c68166-44c0-4c1d-9a31-0c08f8b49af6.mp4

https://user-images.githubusercontent.com/38839485/130270881-3dca4b80-cf26-4ce2-9b2a-1c5f8773a3db.mp4

**Comment by mjr4077au** [comment]
Thanks mate, I'll take a look shortly. Would it be possible to please provide a save game right at the spot where the teleporter is?

**Comment by carnivoroussociety** [comment]
Sure, thank you.

[save0000.zip](https://github.com/coelckers/Raze/files/7024493/save0000.zip)

**Comment by carnivoroussociety** [comment]
This has been fixed in commit https://github.com/coelckers/Raze/pull/512/commits/cd53e4c9668a3753c454483c67a4db67d921a519

**Comment by mjr4077au** [comment]
Thanks for that! Been doing family stuff today and wouldn't have had a chance until tonight 😁
