### ISSUE TITLE
Voodoo doll - next / previous weapon delay

### ISSUE THREAD

**Issue by Axldomi** [coelckers/Raze#517]
When walking / running in Blood and switching through the various weapons, there seems to be a delay once you have equiped the voodoo doll and wish to select the next one. 

Only happens when walking / running and simulteanously switching weapons. It appears that the voodoo doll has some kind of animation that prevents the immediate switching to the next / previous weapon.

I also tested this in Nblood and there the switching works just fine.

**Comment by mjr4077au** [comment]
Thanks for the report, I'll take a look in the morning. I thought I'd resolved this one in my work branch before merging the QAV stuff.
