### ISSUE TITLE
[Duke 3D Atomic Edition, Raze 1.13] e2l7 dnshowmap crash

### ISSUE THREAD

**Issue by Oztrus** [coelckers/Raze#519]
[CrashReport.zip](https://github.com/coelckers/Raze/files/7035502/CrashReport.zip)

Whenever I type in dnshowmap on e2l7 and then attempt to view the automap in overlay mode it crashes, the same happens with typing the cheat in overlay mode.
I tired switching from Vulkan to OpenGL, but it gives me the same result.

**Comment by coelckers** [comment]
Looks to be the same as #454
