### ISSUE TITLE
[Feature Request] Select Expansion Pack Episodes from Main Game

### ISSUE THREAD

**Issue by valter12437** [coelckers/Raze#523]
Like in BuildGDX. I don't know if it's possible but it would be really cool to jump between episodes without the need to close the game every time.

**Comment by coelckers** [comment]
This is unfortunately not that easy. These expansions swap out larger parts of the underlying global state so this would need quite a bit of refactoring work to allow swapping out these resources first. 

That's a lot of work only aimed at gaining some minor convenience, right now we do not have the time to do such things.
