### ISSUE TITLE
New QAV Weapon Interpolation (Bug)

### ISSUE THREAD

**Issue by Tiddalick** [coelckers/Raze#527]
Mucking around with the new Weapon Interpolation just to see how it feels.
Great work, certainly a smoother option.

There seems to be a bug with one of the Voodo Doll frames when it is being used in the primary attack mode.
As Caleb does the stab animation I can see a hint of a single frame that appears on the far right hand side of the screen.
This is standard attack frame (not the one where he stabs the crotch for example)

I am using this dev build
raze-x64-1.1.0pre-540-g44e0da121.7z | Aug 28 2021 11:05:52 | 11,080,711

**Comment by mjr4077au** [comment]
Thanks for the report, I must have missed that one! I'll amend the QAV and push something shortly 😁
