### ISSUE TITLE
[SW] Game crashes when attempting to load a save with the Heart as active weapon

### ISSUE THREAD

**Issue by Canama139** [coelckers/Raze#528]
Attached are three save files. The first (a) was made in normal gameplay and is what tipped me off to this glitch.

The second (b) and third (c) are almost exactly the same, and were made in the same play session seconds apart when I was trying to figure out what caused it. The sole difference is that the heart is selected as the active weapon in b, which crashes on load; on c, which loads fine, it's the Uzis.

Also attached is a crash report generated by attempting to load save b.

[ShadowWarrior.ShadowWarrior.zip](https://github.com/coelckers/Raze/files/7072164/ShadowWarrior.ShadowWarrior.zip)
[CrashReport.zip](https://github.com/coelckers/Raze/files/7072165/CrashReport.zip)

**Comment by coelckers** [comment]
fixed in 73da6f0ae5d2f4404990956618cec6ab52ffe279
The old savegames are lost, though, the bug was in the savegame writer, not the reader.
