### ISSUE TITLE
[Duke3D] Episode 4 intro playback is noticeably faster than in DOS

### ISSUE THREAD

**Issue by dibollinger** [coelckers/Raze#530]
The playback speed of the Duke3D animations is noticeably faster in Raze than it was originally in DOS Duke3D. 

This is particularly noticeable in the Episode 4 intro, as the pause between the General's lines is much shorter, making his speech sound more hurried:

[Episode 4 Intro in DOS Duke3D](https://www.youtube.com/watch?v=besJ6uNQXbY)

[Episode 4 Intro in Raze](https://www.youtube.com/watch?v=orrmNi58l9Q)

I'm using dev build 1.1.0pre-543-ga2f17b1de

**Comment by coelckers** [comment]
fixed in 41b31a544cc59b33cc9dba18131c94d422d1301f
