### ISSUE TITLE
[issue feature] add issue form schema to raze & gzdoom on github

### ISSUE THREAD

**Issue by arrowgent** [coelckers/Raze#531]
moving forward with features on github,  "Form Schemas"
previously offered was template when creating issues.

form schemas attempt to ensure the person creating issues inputs useful data:
version
describe behavior
os
gpu/renderer
etc

i saw another github using this (they were using template previously) and found it more intuitive and fluid
**if you want an example:**
https://github.com/obsproject/obs-studio/issues/new?assignees=&labels=&template=bug_report.yaml

GitHub documentation for new feature:

https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms
https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-githubs-form-schema

of course, maybe this interferes with your current backend for handling issues.  maybe you use other bug-tracking internally
either way its something to consider moving forward for any project

thanks

**Comment by coelckers** [comment]
#532
