### ISSUE TITLE
[BUG] Array crash/assert

### ISSUE THREAD

**Issue by Talon1024** [coelckers/Raze#534]
### Raze version

Git

### What Operating System are you using?

Linux x86_64

### Which game are you running with Raze?

Redneck Rampage

### Relevant hardware info

Intel Ivy Bridge CPU, integrated GPU

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

The game asserts out because a certain array doesn't seem to have enough space for an element, or an invalid index is passed to access the array.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Change the extension of the attached saved game to .dsave, and place it in the `Redneck.RidesAgain` folder, and then load it. You'll need to own and set up Redneck Rampage: Rides Again for Raze.
2. Walk out into the storage yard with all the crates, and look over to your left.
3. Assert (see log below)

[save0004.zip](https://github.com/coelckers/Raze/files/7085582/save0004.zip)

### Your configuration

I'm using the new renderer

### Provide a Log

    raze: ../source/common/utility/tarray.h:263: T& TArray<T, TT>::operator[](size_t) const [with T = int; TT = int; size_t = long unsigned int]: Assertion `index <= Count' failed.

**Comment by coelckers** [comment]
It asserts on a bad picnum. On Windows the problem manifests itself a little bit differently. I have no idea what may have broken it, though.

**Comment by coelckers** [comment]
I just retried loading this save and no longer get the assert. So it seems to have gotten fixed since the report was made.
