### ISSUE TITLE
[BUG] Missing triangle in E6M3

### ISSUE THREAD

**Issue by Talon1024** [coelckers/Raze#535]
### Raze version

Git

### What Operating System are you using?

Linux x86_64

### Which game are you running with Raze?

Blood

### Relevant hardware info

Intel Core i5-4690K CPU, NVidia GeForce GTX 970

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

There is a missing triangle on Blood E6M3, when the big wooden door is closed.

![Blood_0014](https://user-images.githubusercontent.com/6550500/131820759-55ce3bc8-a882-42a0-97ec-5bd9083e5f7e.png)

[Saved game (Blood.Blood)](https://github.com/coelckers/Raze/files/7097856/save0000.zip)

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Ensure you're using the new renderer
2. Load the saved game

### Your configuration

```ini
I am using the new renderer
```

**Comment by mjr4077au** [comment]
@Talon1024 where did you source this screenshot from? I've just cross-referenced this with NBlood in its software and hardware renderer and neither show a triangle either. Below screenshot is from NBlood in software:

![blud0004](https://user-images.githubusercontent.com/48643140/146333867-c0e05682-5c2e-41c8-8f92-0d14e792edc5.png)

**Comment by mjr4077au** [comment]
I can't even replicate this in GDX across all three of its renderers. If there's something I'm missing, please re-open the issue.

**Comment by mjr4077au** [comment]
@Talon1024 I'm very sorry, I rushed in on this and didn't read it properly in that you were highlighting "we" had a triangle there whereas no other game does. This has since been resolved in our `develop` branch which is why I was revisiting this.

I'll pay more attention to what I'm doing next time but thank you again for your report, its very much appreciated.
