### ISSUE TITLE
[BUG, Blood] Crash upon loading a saved game

### ISSUE THREAD

**Issue by Talon1024** [coelckers/Raze#538]
### Raze version

Git

### What Operating System are you using?

Linux x86_64

### Which game are you running with Raze?

Blood

### Relevant hardware info

Intel i5-4690K CPU, NVidia GeForce GTX 970 GPU

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

If you are playing Blood, you won't be able to load any previous saved game.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Save your game
2. Quit the game
3. Re-open the game
4. Try to load your saved game from step 1
5. Crash

### Your configuration

```ini
I am using the new renderer, and an ASan-enabled build.
```

### Provide a Log

*** Fatal Error ***
Address not mapped to object (signal 11)
Address: 0x556209b56e80

Generating raze-crash.log and killing process 23874, please wait... 27  ../sysdeps/unix/sysv/linux/wait4.c: No such file or directory.

**Comment by coelckers** [comment]
fixed in 8a48356b3d91fd893d5e1d956884fa6c698d221a
