### ISSUE TITLE
[BUG, newrenderer] Weird wall on Duke Nukem 3D E2L1

### ISSUE THREAD

**Issue by Talon1024** [coelckers/Raze#539]
### Raze version

Git

### What Operating System are you using?

Linux x86_64

### Which game are you running with Raze?

Duke Nukem 3D

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

A weird wall appears in the new renderer when the player tries to leave this tunnel:

https://user-images.githubusercontent.com/6550500/132049245-7ab165dd-d80f-48f1-98b8-6a717d6f2fe8.mp4

However, you'll notice it doesn't appear if the player is using Polymost.

[Saved game (Duke.Duke.15)](https://github.com/coelckers/Raze/files/7107792/save0002.zip)

### Steps to reproduce the behaviour.

Watch the video. It shows the wall appearing in the new renderer, and then the wall not appearing in Polymost.

**Comment by Talon1024** [comment]
This bug still happens with Raze d30c94c70998417422f201b2e5c3b536a075538b, and it happens with all backends: Vulkan, OpenGL, and OpenGL ES.

**Comment by coelckers** [comment]
Fixed in a work branch,
