### ISSUE TITLE
[BUG, Blood] Assertion failure when flipping switch on E1M3

### ISSUE THREAD

**Issue by Talon1024** [coelckers/Raze#540]
### Raze version

Git

### What Operating System are you using?

Linux x86_64

### Which game are you running with Raze?

Blood

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

An assertion fails when I try to flip the switch for the Reflective Shots powerup on E1M3.

[Saved game (Blood.Blood)](https://github.com/coelckers/Raze/files/7109623/save0002.zip)

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Load the saved game
2. Try flipping the switch in front of you, or the switch behind the opposite counter
3. Assertion failure (see log)

### Provide a Log

```raze: ../source/games/blood/src/eventq.cpp:342: bool Blood::evGetSourceState(int, int): Assertion `nXIndex > 0 && nXIndex < kMaxXSprites' failed.```

**Comment by coelckers** [comment]
fixed in 1271596ebb94047772ea36e28367f6c834710e2f
