### ISSUE TITLE
[BUG] Crash when trying to flip switch on Blood E2M2

### ISSUE THREAD

**Issue by Talon1024** [coelckers/Raze#543]
### Raze version

Git 5a68eb78ddad7ffdd07c8b9ebcccae4bdc923bfb

### What Operating System are you using?

Linux x86_64

### Which game are you running with Raze?

Blood

### Relevant hardware info

Intel i5-4690K CPU, NVidia GeForce GTX 970 GPU

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

When attempting to flip the switch in front of the player (see saved game), Raze crashes.

[Saved game (Blood.Blood)](https://github.com/coelckers/Raze/files/7116298/save0002.zip)

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Load the saved game
2. Try to flip the switch
3. Crash

### Your configuration

```ini
testnewrenderer=true
```

### Provide a Log

Address not mapped to object (signal 11)

Unfortunately, I cannot give more details than that. ASan doesn't detect the issue.

**Comment by coelckers** [comment]
I need the precise commit this savegame was made with, or some info where to find that switch. That image doesn't tell me much and due to the recent changes that savegame only works with a limited range of commits.

**Comment by Talon1024** [comment]
I think it was 85bf47574c290a334faa1cf88461697bd509c437 or 85bf47574c290a334faa1cf88461697bd509c437, but I can't remember exactly which commit.

**Comment by coelckers** [comment]
Thanks. I am fairly certain this was a transitional error that has already been fixed. When starting the level fresh and then pressing the switch it will not happen anymore with the latest build.
