### ISSUE TITLE
[BUG] Eviction Notice custom monster doesn't behave properly

### ISSUE THREAD

**Issue by Doruk-Aksoy** [coelckers/Raze#545]
### Raze version

1.1.0

### What Operating System are you using?

Windows 10

### Which game are you running with Raze?

Blood

### Relevant hardware info

AMD 3950X CPU, NVIDIA 2070S GPU

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

The custom monster in Eviction Notice, rolling zombie head, doesn't behave properly. In NBlood it actively rolls towards the player and bites them when near. In Raze, they don't care and roll aimlessly and never attack the player even if you're up close.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Launch Eviction Notice.
2. Go to the laundromat area in first map.
3. Observe the behavior of rolling heads in the bathroom of laundromat. Compare to NBlood.

**Comment by coelckers** [comment]
Fixed in 53fa1844ba581cdef594edeca9916b39cad75ba7
