### ISSUE TITLE
[BUG] Seemingly random crash in Eviction Notice

### ISSUE THREAD

**Issue by Doruk-Aksoy** [coelckers/Raze#546]
### Raze version

1.1.0

### What Operating System are you using?

Windows 10

### Which game are you running with Raze?

Blood

### Relevant hardware info

AMD 3950X CPU, NVIDIA 2070S GPU

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

I have a crash log of the incident posted in build-engine-feedback channel of ZDoom discord: https://cdn.discordapp.com/attachments/826113552120807475/885644739553132554/CrashReport_Raze_EvictionNotice.zip

I'm not sure if the steps will be reproducible 100% of the time because I encountered another issue with my save that prevented me from playing, which I'll also make a bug report of. I also don't have a log of the incident sadly because after the crash I wanted to see if it was 100% reproducible, and encountered this very error...

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Play Eviction Notice as normal.
2. When in the fire key area in map01, there's a room in the upper floor that has a room with an unholy ritual. In that very room there's a door in the middle connecting two rooms. Open it.
3. Once opened and when the rolling zombie head spots you, it crashes.

### Your configuration

testnewrenderer=false

**Comment by coelckers** [comment]
fixed in 6cd9f262c87e5ff3c062b79af9fa9108abfe01bf
