### ISSUE TITLE
[BUG] Loading a save in Eviction Notice seems to kill you

### ISSUE THREAD

**Issue by Doruk-Aksoy** [coelckers/Raze#547]
### Raze version

1.1.0

### What Operating System are you using?

Windows 10

### Which game are you running with Raze?

Blood

### Relevant hardware info

AMD 3950X CPU, NVIDIA 2070S GPU

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

https://media.discordapp.net/attachments/826113552120807475/885644913897766912/unknown.png?width=1202&height=676 -- From Zdoom discord build-engine-feedback channel. I encountered this when I tried to load my save of Eviction Notice. What happened is, I seem to be in state of "death" but my player can throw tnt around. I can't move or look around. I can't switch weapons. Link to the save in question: https://www.dropbox.com/s/6ti25b5le9ia6cr/save0000.dsave?dl=0

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Launch Eviction Notice.
2. Play a bit and save.
3. Load save.

**Comment by coelckers** [comment]
Fixed in b35c23c03e834142764c76b9eaf1820172dd35cf
