### ISSUE TITLE
[BUG, Blood] E2M1 crate broken

### ISSUE THREAD

**Issue by Talon1024** [coelckers/Raze#548]
### Raze version

Git

### What Operating System are you using?

Linux x86_64

### Which game are you running with Raze?

Blood

### If Other OS, please describe

Kubuntu 20.04.1

### Relevant hardware info

Intel i5-4690K CPU, NVidia GeForce GTX 970 GPU

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Once I flip the switch to raise the crate on E2M1, the crate "breaks" and becomes unreachable.

Commit bf32c5ed8d77ab5c140acc87317db62931704748
[Saved game (Blood.Blood)](https://github.com/coelckers/Raze/files/7148047/save0004.zip)

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Load the saved game
2. Flip the switch
3. The crate which you are supposed to jump on in order to reach the top deck of the ship breaks and becomes unreachable

### Your configuration

```ini
testnewrenderer=true
```

**Comment by coelckers** [comment]
fixed in 38b191a9532655786ce15bc5e6a1a482d943fdec
The savegame is broken, though, but with a newly created one it works again.
