### ISSUE TITLE
[BUG] Secrets tied to object pickup don't count towards the secret count

### ISSUE THREAD

**Issue by Doruk-Aksoy** [coelckers/Raze#550]
### Raze version

1.1.0

### What Operating System are you using?

Windows 10

### Which game are you running with Raze?

Blood

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

The very first secret in the Eviction mod here doesn't trigger properly. A video for convenience: https://www.youtube.com/watch?v=jZtCXzO0FC4 -- The secret triggers as soon as the portait is moved. Similarly secret #9 in the video also did not count towards my progress.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Load Eviction mod. https://www.moddb.com/mods/eviction-addon-for-blood
2. Start level 1.
3. Hit use on the green portrait in the starting area, the secret count won't increase.

**Comment by Talon1024** [comment]
Could be the same as, or related to #536

**Comment by coelckers** [comment]
No, it isn't. The secret #9 is related to the refactoring which I just undid and secret #1 works for me in both old and new versions.
