### ISSUE TITLE
[BUG] Crash on trying to restart after dying to burning

### ISSUE THREAD

**Issue by Doruk-Aksoy** [coelckers/Raze#551]
### Raze version

1.1.0

### What Operating System are you using?

Windows 10

### Which game are you running with Raze?

Blood

### Relevant hardware info

AMD 3950X CPU, NVIDIA 2070S GPU

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

I died in Eviction map02 to my own burning damage from flare gun and when I tried to restart the level the game crashed. Crash report here: https://mega.nz/file/ERkU1QRA#yXAUbn0q1IJBiufY6Qa2i5-61BWBjucssw-DNCASvLU

### Steps to reproduce the behaviour.

I'm not sure if this is reproducible.

**Comment by AAS** [comment]
@coelckers I tested it on map01 on 1.2.1. 
Save & load crashes the game with eviction mod, even on clean start without dying.

**Comment by coelckers** [comment]
I cannot reproduce the original problem in the latest development code at all so I assume it's already fixed.
The savegame crash mentioned in the other report is fixed. Savegames for Eviction will load now.
