### ISSUE TITLE
[Feature] Where is bloom?

### ISSUE THREAD

**Issue by Akis-02** [coelckers/Raze#553]
### Raze version

1.1.3

### What Operating System are you using?

Windows 10

### Which game are you running with Raze?

This goes on all games

### Is your feature request related to a problem? Please describe.

in this post in https://www.doomworld.com/forum/topic/111839-source-port-introducing-raze-thats-one-duked-up-space-marine/ says it has stuff like bloom from gzdoom, which i find the gzdoom to be nice and not overdone (i think?) but its not present in the raze port.

### Add any other context or screenshots about the feature request here.

![image](https://user-images.githubusercontent.com/39632375/133845543-65246fbc-4e2c-44cb-9b3a-8f32913dbbb5.png)

**Comment by coelckers** [comment]
Bloom does not work with how Polymost sets up its geometry.  It will be enabled once the new renderer reaches a more stable state.
