### ISSUE TITLE
[BUG] Cannot change hqresize options on macOS / "Texture options" missing on windows

### ISSUE THREAD

**Issue by warrex1979** [coelckers/Raze#555]
### Raze version

1.1.3

### What Operating System are you using?

Mac OS

### Which game are you running with Raze?

Duke Nukem 3D

### Relevant hardware info

Mac Mini 2020

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Under "texture options" the HQ resize mode and multipler cannot be changed and the value given is "unknown".

"Texture options" does not even exist on windows. What's up with that?

### Steps to reproduce the behaviour.

1. Open Raze
2. Go to texture options in the menu.

### Your configuration

```ini
Happens at default settings.
```

**Comment by alexey-lysiuk** [comment]
Windows build of 1.1.3 contains outdated `menudef.txt` file, without texture options menu, despite [its existence](https://github.com/coelckers/Raze/blob/11c38d007cd63af40adca4556848c42acb2256b0/wadsrc/static/menudef.txt#L1026) in the repository.
Version for macOS uses the right file, but [this commit](https://github.com/coelckers/Raze/commit/64a3c5aac862f963e101c0d9c53fbbdeac37a413) wasn't merged into 1.1.x release branch. Part of these changes was made [manually](https://github.com/coelckers/Raze/commit/0f1f429c635f5c7663a7855ae0cd6b1287646cd0).
Master branch has everything in place, so menu is fully functional in the development version

You still can change resize mode and multiplier via the corresponding CVARs, `gl_texture_hqresizemode` and `gl_texture_hqresizemult`.

**Comment by warrex1979** [comment]
> You still can change resize mode and multiplier via the corresponding CVARs, `gl_texture_hqresizemode` and `gl_texture_hqresizemult`.

Does not work for me. Added the following as I do in GZDoom and I cannot see that the filter is in effect:

gl_texture_hqresize_maxinputsize=512
gl_texture_hqresize_mt_height=4
gl_texture_hqresize_mt_width=16
gl_texture_hqresize_multithread=true
gl_texture_hqresize_targets=15
gl_texture_hqresizemode=5
gl_texture_hqresizemult=5
