### ISSUE TITLE
[BUG] [Blood] Swapping from any weapon to Aerosol Can doesn't have correct animations

### ISSUE THREAD

**Issue by Doruk-Aksoy** [coelckers/Raze#564]
### Raze version

Raze 1.2.1

### Which game are you running with Raze?

Blood

### What Operating System are you using?

Windows 10

### Relevant hardware info

AMD 3950X CPU, NVIDIA 2070S GPU

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

You can swap from any weapon to aerosol can and the zippo teleports to screen out of nowhere. Ex: Prev weapon from Tesla Cannon.

I've identified that the problem isn't relevant of weapon interpolation, as this happens in NBlood too. BuildGDX correctly shows the zippo animation.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Give all.
2. Swap to Tesla Cannon.
3. Prev weapon to Aerosol Can, the zippo instantly teleports.

**Comment by carnivoroussociety** [comment]
This is fixed by clearing weapon state [at the bottom of WeaponLower()](https://gitlab.com/m210/BloodGDX/-/blob/master/core/src/ru/m210projects/Blood/Weapon.java#L1523).
