### ISSUE TITLE
[BUG] Weird wall sprite issue in SW's $seppuku.map with GLES and newrenderer.

### ISSUE THREAD

**Issue by mjr4077au** [coelckers/Raze#565]
### Raze version

1.2pre-215-gfc73c67bb

### If Other OS, please describe

Windows

### Relevant hardware info

NVIDIA GeForce GTX 970

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

<del>Some strange portal portal issues on Duke E1L1 when going in through the window from the street.</del>

<details>![Duke_0002](https://user-images.githubusercontent.com/48643140/138065496-9f26a5b1-b9de-4035-b78f-3e60a626d6f9.png)</details>

Also get this in Shadow Warrior in $seppuku, but can't reproduce it from a save, only a new game. Its the room where you move the car with the key to the collection area.

![ShadowWarrior_0000](https://user-images.githubusercontent.com/48643140/138065663-4b7abc60-e4bd-4002-a444-cd8f60eef290.png)

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Open Raze with GLES renderer.
2. Go to affected areas.
3. See the issues.

**Comment by emileb** [comment]
Fixed in https://github.com/coelckers/Raze/pull/592
The fix I put was to just ignore mBias.mChanged for now and always update for now.

**Comment by mjr4077au** [comment]
Fixed in #597 😎
