### ISSUE TITLE
[Feature] make raze search to the ZOOM PLATFORM for duke nukem atomic edition

### ISSUE THREAD

**Issue by Akis-02** [coelckers/Raze#567]
### Raze version

1.2.1

### Is your feature request related to a problem? Please describe.

Raze does not search for the zoom platform version of atomic edition, which i think is the only way to get that version now?

### Describe the solution you'd like

C:\ZOOM PLATFORM\Gearbox Software\Duke Nukem 3D - Atomic Edition is the folder for the game path
C:\ZOOM PLATFORM\Gearbox Software\Duke Nukem 3D - Atomic Edition\AddOns for expansions

**Comment by mjr4077au** [comment]
@Akis-02 I have Discord, I'm `mjr4077au#1027`. Feel free to give me a message there, perhaps we can look at how to get the data together :)
