### ISSUE TITLE
[BUG] SW camera screen projection is off in new renderer.

### ISSUE THREAD

**Issue by mjr4077au** [coelckers/Raze#574]
### Raze version

1.2.1

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Polymost (correct)
![ShadowWarrior_0004](https://user-images.githubusercontent.com/48643140/139561665-5e3cd0ef-c3e2-4ecd-9b23-41160214b362.png)

New renderer
![ShadowWarrior_0003](https://user-images.githubusercontent.com/48643140/139561667-2b5c98d8-1ddb-4d10-9494-f09dd484c0eb.png)

**Comment by coelckers** [comment]
In this screenshot is isn't really that obvious, you can see this a lot more clearly in Duke where the camera points directly at the monitor - but Polymost apparently does not get the aspect ratio right on camera views. They are all visibly squashed.
The new renderer does produce a proper 1:1 aspect ratio image. The rest here is just the projection, using proper math just seems to exaggerate the camera tilt a bit more than Polymost does - but that's a consistent property of the renderer.

With Build's original low res software rendered images this was a lot less obvious but we are actually using 4x higher resolution than the nominal texture sizes where you can clearly see these things.

**Comment by mjr4077au** [comment]
All good, I'll keep note of this so we can lower the camera's position in the game code once Polymost is gone. There's a lot lost down the bottom and it can cause you to lose track of the RC car.
