### ISSUE TITLE
[BUG] Exhumed's title plasma/smoke has weird timing issues until the menu options appear on screen.

### ISSUE THREAD

**Issue by mjr4077au** [coelckers/Raze#578]
### Raze version

1.2.1

### Which game are you running with Raze?

Exhumed/Powerslave

### What Operating System are you using?

Windows 10

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

After the screenjobs finish and the laughing pharaoh appears, the plasma/smoke around the Exhumed/Powerslave name appears stuttery and not smooth, as if the timer is off somehow. When the menu options appear though, the timing issue is no longer apparent. 

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Just open the game and observe.

It's really subtle and hard to notice, but fortunately when I captured video which dropped frames as its only a 30fps capture, it really highlighted the issue. https://youtu.be/UW1znNat4gs

You'll observe hitching before the menu appears but once it does, the title smoke is smooth like it should be.

**Comment by coelckers** [comment]
Made it a little better but the timing of this thing doesn't allow much. It's as good as it can be right now.
