### ISSUE TITLE
[Feature] Port `gl_seamless` into new renderer.

### ISSUE THREAD

**Issue by mjr4077au** [coelckers/Raze#579]
### Raze version

1.2.1

### Is your feature request related to a problem? Please describe.

Currently in the new renderer, it's possible to see the dots between some of the polys, especially in games with a black sky like SW's first level.

The CVAR `gl_seamless` in is Raze by way of common code from GZDoom, but is not hooked to any of Raze's core render code.

### Describe the solution you'd like

Get the CVAR hooked up once some of the more important aspects like the clipper have been resolved.

### Describe alternatives you've considered

Not doing it and just dealing with it, but it would be nice to have.

### Add any other context or screenshots about the feature request here.

Here's a screenshot showing a large-ish red line down the stairwell, along with a few dots. It's hard to lock the mouse on but if you're in this spot and are aiming around, the dots are quite distracting.

![ShadowWarrior_0006](https://user-images.githubusercontent.com/48643140/140583706-b7194b01-2c65-4540-8522-50d133fea878.png)

**Comment by sinisterseed** [comment]
And, freshly added to the work branch 😉.
