### ISSUE TITLE
[BUG] Can't reload Exhumed due to nullptr in rat's pTarget.

### ISSUE THREAD

**Issue by mjr4077au** [coelckers/Raze#581]
### Raze version

e88627b72a4f07d17b75c1d9a1220e729707b005

### Which game are you running with Raze?

Exhumed/Powerslave

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

As per the title. Backtraced to e88627b72a4f07d17b75c1d9a1220e729707b005.

Stack trace with MSVC:

![image](https://user-images.githubusercontent.com/48643140/140607457-58d2af7b-1b8b-434b-8069-1e02705a7a88.png)

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Open game, start new level and save.
2. Close game.
3. Open game, load save and experience crash.

**Comment by coelckers** [comment]
fixed in 60faceaf59ef850fd806b43a9d9fc0bea21145c3
