### ISSUE TITLE
[SW] Difficulty resets when transitioning maps from a save

### ISSUE THREAD

**Issue by srludicolo** [coelckers/Raze#582]
### Raze version

Raze 1.2.1

### Which game are you running with Raze?

Shadow Warrior

### What Operating System are you using?

Windows 10

### Relevant hardware info

Ryzen 5 2600. Radeon 5500 XT 8GB 

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

I was playing on No Pain No Gain difficulty, and the game will spontaneously switch to a lower difficulty when you enter a new level. This doesn't seem to happen when using the console to warp to a new level.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Just play the game on No Pain No Gain long enough and you'll notice it without fail eventually.

### Provide a Log

[raze.ini.zip](https://github.com/coelckers/Raze/files/7492811/raze.ini.zip)

**Comment by Talon1024** [comment]
Does it happen during one long, continuous playthrough without quitting the game?

I was able to reproduce this issue, but only after quitting the game and loading my saved game.

**Comment by srludicolo** [comment]
It definitely happens when quitting and loading, but I don't remember it happening during continuous play.

**Comment by arrowgent** [comment]
sounds like what BLOOD used to do in dosbox, only instead of lower difficulty it was raising the difficulty

https://www.gog.com/forum/blood_series/difficulty_setting_changes_when_loading_save_files/?search=difficulty

possibly related to that "fix" ?

**Comment by srludicolo** [comment]
Indeed. It's incredibly frustrating because I'm trying to beat the game on No Pain No Gain and it keeps pulling the rug out from me. I don't want to just fight regular zombie ninjas!

**Comment by sinisterseed** [comment]
> sounds like what BLOOD used to do in dosbox, only instead of lower difficulty it was raising the difficulty
> 
> https://www.gog.com/forum/blood_series/difficulty_setting_changes_when_loading_save_files/?search=difficulty
> 
> possibly related to that "fix" ?

Wholly unrelated since these games ticks very differently from each other.

I can confirm this bug as well. Difficulties reset between level transitions but only from a save. Saved before finishing the first map, then proceeded. Had 70+ enemies at the start.

Then ended the game, started Code of Honor, ended the game again, and reloaded the save. After transitioning to Zilla Construction again, it only had 16 enemies at the beginning this time around, lol.

**Comment by Gaerzi** [comment]
So it seems like the save load code doesn't init the difficulty setting.
