### ISSUE TITLE
[Feature] Ambient Occlusion

### ISSUE THREAD

**Issue by NineKain** [coelckers/Raze#583]
### Raze version

Raze 1.2.1

### What Operating System are you using?

Windows 10

### Is your feature request related to a problem? Please describe.

No

### Describe the solution you'd like

Port Ambient Occlusion from GZDoom, It can look great in my opinion and shouldn't be too hard.

### Describe alternatives you've considered

Can't force with with NVidia Control Panel

**Comment by mjr4077au** [comment]
It's already there for the new renderer which is undergoing review, refactoring and optimisation. It'll be exposed in the menus when it's ready.

![Duke_0004](https://user-images.githubusercontent.com/48643140/140843030-84060a41-3bed-4fa3-8411-d4df7a0bf4b3.png)
![Duke_0005](https://user-images.githubusercontent.com/48643140/140843037-d4d572fc-e6cd-4acd-87ce-87cb988e3660.png)

**Comment by NineKain** [comment]
can you enable in the dev builds yet? i wanna try it even if its buggy

**Comment by Gaerzi** [comment]
Yes, you can use the console. All the menus do is give a nicer interface to set some console variables to relevant values; in this case the cvar in question is called gl_ssao and by default it's 0 (disabled) but you can set it to 1 to enable it.
