### ISSUE TITLE
[BUG] Can't run Death Wish

### ISSUE THREAD

**Issue by NineKain** [coelckers/Raze#586]
### Raze version

Raze 1.2.1

### Which game are you running with Raze?

Blood

### What Operating System are you using?

Windows 10

### Relevant hardware info

R5 5600x, 3060ti, 16gb RAM

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

![raze exe Screenshot 2021 11 12 - 03 13 10 86](https://user-images.githubusercontent.com/72826232/141397185-28ce3f02-8066-48a4-b57c-0fdbc9125f50.png)

I opened the dw.ini using autoload, and this error pops up when starting a new game

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Put the folder on the autoload folder
2. Edit raze.ini to point it to dw.ini
3. Start a new level

**Comment by mjr4077au** [comment]
Don't do it like that. Mods are designed to be loaded as they come from the author, zipped and never unpacked.

Either drag and drop the ZIP file onto raze.exe to autoload it, or point your `[Blood.Autoload]` setup to the ZIP file without unpacking it.

Confirming Death Wish works when loaded properly:

![image](https://user-images.githubusercontent.com/48643140/141398643-34e81ce0-583a-44f8-9914-5f0a810125f2.png)

**Comment by NineKain** [comment]
oh sorry, my bad, thanks
