### ISSUE TITLE
[BUG] Mirrors in SW aren't breaking in new renderer

### ISSUE THREAD

**Issue by mjr4077au** [coelckers/Raze#587]
### Raze version

develop

### Which game are you running with Raze?

Shadow Warrior

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

https://user-images.githubusercontent.com/48643140/141610658-7c6c7007-fe2c-4e8f-8823-84b2db9d4930.mp4

**Comment by coelckers** [comment]
fixed.
