### ISSUE TITLE
[BUG] [SW] Game crashes on exit

### ISSUE THREAD

**Issue by NineKain** [coelckers/Raze#588]
### Raze version

raze-x64-1.2pre-543-gdc1d97b6b

### Which game are you running with Raze?

Shadow Warrior

### What Operating System are you using?

Windows 10

### Relevant hardware info

R5 5600x, 3060ti, 16gb RAM

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

When exiting the game, the game crashes

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Exit the game
2.
3.

### Your configuration

```ini
testnewrenderer = true
gl_ssao = 1
```

### Provide a Log

[CrashReport.zip](https://github.com/coelckers/Raze/files/7539385/CrashReport.zip)

**Comment by mjr4077au** [comment]
@NineKain does it crash with SSAO off? As discussed on the other report, its completely unsupported at present.

**Comment by NineKain** [comment]
Sometimes it crashes, sometimes it doesn't, it's hard to reproduce, and it doesn't matter much since it's when exiting to desktop anyways, reopen if you guys see fit.
