### ISSUE TITLE
High quality Resize no longer works on any game.

### ISSUE THREAD

**Issue by LethalManBoob** [coelckers/Raze#589]
### Raze version

Raze 1.2.1

### Which game are you running with Raze?

Other

### What Operating System are you using?

Linux x86_64

### Relevant hardware info

NVIDIA, INTEL i7 6700K

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

The only textures that are affected by high quality resize are the ViewModel and hud textures, regardless of the settings.

### Steps to reproduce the behaviour.

Enable hq resize... .-.

**Comment by coelckers** [comment]
fixed in c1227d6a7302275dabd56ff799b039716eaed8cd , the bug was only present in Polymost.
