### ISSUE TITLE
In #NAM# Game not visible episode 3 and 4

### ISSUE THREAD

**Issue by AntonZab** [coelckers/Raze#590]
### Raze version

1.2

### Which game are you running with Raze?

NAM

### What Operating System are you using?

Windows 7

### Have you checked that no other similar issue already exists?

- [x] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Episodes 3 and 4 are missing when selecting episodes in NAM

### Steps to reproduce the behaviour.

Explain how to reproduce
1. 
2.
3.

**Comment by mjr4077au** [comment]
Episodes 3 and 4 are the multiplayer levels though, right? Multiplayer episodes are hidden from the menus.

**Comment by coelckers** [comment]
Yes, they are indeed.
