### ISSUE TITLE
[BUG] [Duke3D] Wrong sky color in Polymost while underwater

### ISSUE THREAD

**Issue by NY00123** [coelckers/Raze#591]
### Raze version

1.2pre-547-g1228cb604

### Which game are you running with Raze?

Duke Nukem 3D

### What Operating System are you using?

Linux x86_64

### Relevant hardware info

GeForce GTX 1070 Ti

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

The sky color should appear to be bluer while staying in the pool's underwater sector.
In practice, it remains gray with the Polymost renderer if palette emulation is toggled on.

![Duke_0009](https://user-images.githubusercontent.com/6780140/142630810-bd6b15af-5750-40f8-9bfd-cb0f2f68ed87.png)
![Duke_0010](https://user-images.githubusercontent.com/6780140/142630813-a184af6f-c235-4aee-a42b-7f850aa1935a.png)

### Steps to reproduce the behaviour.

Load NEWWORLD.MAP as present in the zip file, enter into the water within then nearby pool and then look at the sky.
Make sure the Polymost renderer is used with palette emulation.

[newworld.zip](https://github.com/coelckers/Raze/files/7570523/newworld.zip)

### Your configuration

```ini
hw_useindexedcolortextures=true
testnewrenderer=false
```

**Comment by coelckers** [comment]
Should be fixed.
