### ISSUE TITLE
[BUG] Duke: Smooth out pig cop recon patrol vehicles

### ISSUE THREAD

**Issue by mjr4077au** [coelckers/Raze#593]
These are a lot smoother in EDuke32. Its been like this for a long time now, should be investigated in due course.

https://user-images.githubusercontent.com/48643140/145359211-b9892c38-446b-4970-afc9-73eafae0cff9.mp4

**Comment by coelckers** [comment]
How are they in DukeGDX?

**Comment by mjr4077au** [comment]
> How are they in DukeGDX?

Same as us.

**Comment by mjr4077au** [comment]
Fixed via ca412ba6b3d0f9d0567b1f9a5d40df5a3a0650b2.
