### ISSUE TITLE
[BUG] doors do not close automatically

### ISSUE THREAD

**Issue by shaggi72** [coelckers/Raze#594]
### Raze version

Raze 1.3.0

### Which game are you running with Raze?

Duke Nukem 3D

### What Operating System are you using?

Windows 10

### Relevant hardware info

Core i7 3770, Intel HD4000

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

in the first episode L.A. Meltdown, some doors close automatically after a few seconds, in Raze 1.3.0 it is not happening

![Duke_0004](https://user-images.githubusercontent.com/10621426/145490283-3081154e-6f19-4776-b671-087f0604a06a.png)

### Steps to reproduce the behaviour.

Explain how to reproduce
1. 
2.
3.

**Comment by mjr4077au** [comment]
@shaggi72 thank you for the report! Fixed in master, will make it into a 1.3.1 release at some point.
