### ISSUE TITLE
[BUG] Considerable frame drops in certain places on a map

### ISSUE THREAD

**Issue by LittleAmpton** [coelckers/Raze#595]
### Raze version

Raze 1.4pre-2-g853aab551

### Which game are you running with Raze?

Duke Nukem 3D

### What Operating System are you using?

Windows 10

### Relevant hardware info

CPU: AMD Ryzen 5 2400G, GPU: GeForce RTX 2060

### Have you checked that no other similar issue already exists?

- [x] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

In the shop on the first level of Nuclear Winter, there are considerable visual "hiccups", whose frequency varies from "annoying" to "unplayable". [Here's a video picturing the issue.](https://youtu.be/Df3kUSZlX6Y?t=27)

The issue happens regardless of the rendering API used.
The issue happens both on my PC and a laptop which has never had Raze installed before. It doesn't happen on "official" EDuke32 included with Steam version of the game.

### Steps to reproduce the behaviour.

1. Start the first level of Nuclear Winter
2. Go to the shop as in the video.

**Comment by coelckers** [comment]
fixed in 10c6fde8d681682a740d7b84f6da626637f7c8fd
