### ISSUE TITLE
[BUG] Player falls through bridges over room (video link in description)

### ISSUE THREAD

**Issue by Cadaver747** [coelckers/Raze#601]
### Raze version

Raze 1.3.0 (latest at the time of writing)

### Which game are you running with Raze?

Exhumed/Powerslave

### What Operating System are you using?

Windows 7

### Relevant hardware info

i5-3570K 3.40GHz, nVidia 1060 6Gb, ASUS P8Z77 V-LX2, 16Gb RAM

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Source link:
https://www.youtube.com/watch?v=NYMDzPEUjRg

Raze engine is pretty good, Powerslave/Exhumed (DOS) game runs smoothly but it becomes nearly unplayable starting from levels 4-5, for some reason Raze engine can't handle bridges over room, player is always fell through it, the only workaround is a running strafing jump. >> Tested on Levels 2, 4 and 5, all bridges are faulty.
Additionally some enemies are frozen (you can kill them, but the animation will not change), the small audio briefing after Level 4 is on constant loop, some explosive barrels do not explode (Level 4), some saves were corrupted and can't be loaded ever again.
I was not able to finish the Training section properly, it just stuck there and restart again.

(I was not able to drag and drop my raze-Cadaver747.ini file into Your configuration section, it does not react to it)

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Start the Powerslave/Exhumed game under Raze 1.3.0 (latest)
2. Load Level 2
3. Check the faulty bridge

### Provide a Log

[raze.log](https://github.com/coelckers/Raze/files/7701126/raze.log)

**Comment by Cadaver747** [comment]
[raze-Cadaver747.ini.zip](https://github.com/coelckers/Raze/files/7701191/raze-Cadaver747.ini.zip)

**Comment by mjr4077au** [comment]
Thanks for the report, I've confirmed I also experience this on that bridge on Level 2. We'll take a look and get it fixed up for the 1.3.1 release.

Exhumed has been pretty stable but we've done a tonne of refactoring to its actors and other things so its not unlikely that some bugs slipped in through the back door.

**Comment by coelckers** [comment]
fixed in e104316e7532484af911ec09163fe836c6c6b460
