### ISSUE TITLE
[BUG] Transparency issues with indexed hightiles on new renderer while Palette Emulation is enabled (any backend)

### ISSUE THREAD

**Issue by mjr4077au** [coelckers/Raze#602]
### Raze version

1.3.0

### Relevant hardware info

NVIDIA GeForce GTX 970

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Palette Emulation enabled:
![Duke_0040](https://user-images.githubusercontent.com/48643140/145757275-6d377fe6-9a98-4981-9e92-8c662e5a4958.png)

Palette Emulation disabled:
![Duke_0041](https://user-images.githubusercontent.com/48643140/145757283-d41e6e63-f210-4d52-80ab-50ccd809526e.png)

Can confirm this does not happen with the original assets, only indexed hightiles.

Duke ERP for Raze: https://www.moddb.com/downloads/duke-nukem-enhanced-resource-pack-for-raze

Save game on the spot (needs `develop` branch).
[save0011.zip](https://github.com/coelckers/Raze/files/7701205/save0011.zip)

### Steps to reproduce the behaviour.

1. Load the game with the ERP.
2. Ensure Palette Emulation is enabled.
3. Load the attached save.
4. Press use on the arcade machine to trigger the secret where the holoduke is.

**Comment by coelckers** [comment]
fixed in a899055f50da6671016e379c7fdd256c968ecbf8
