### ISSUE TITLE
[BUG] New renderer glitch in Blood Cryptic Passage CP06

### ISSUE THREAD

**Issue by mjr4077au** [coelckers/Raze#603]
### Raze version

1.4pre

### Which game are you running with Raze?

Blood

### Relevant hardware info

NVIDIA GeForce GTX 970

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

New renderer:
![Blood_0029](https://user-images.githubusercontent.com/48643140/145759814-0d05ee69-c2e9-4d6f-8f16-7c0fbe3fd9d8.png)

Polymost:
![Blood_0030](https://user-images.githubusercontent.com/48643140/145759827-20315640-1fa8-4aa2-8ac4-10334753d2c3.png)

Save game of spot:
[save0000.zip](https://github.com/coelckers/Raze/files/7701303/save0000.zip)

Happens on any backend irrespective of things like Palette Emulation, etc.

**Comment by coelckers** [comment]
fixed in 498abf25f3ad168a255eaa56f234303c6ccdc21a
