### ISSUE TITLE
Duke 3D: Atomic edition and Shadow Warrior sensitivity problem.

### ISSUE THREAD

**Issue by Matty4818** [coelckers/Raze#604]
I am using an Xinput Xbox controller to play The Atomic Edition of Duke 3D, along with Shadow Warrior. The issue I’m experiencing is not being able to adjust the “Strafing” and “Moving Forward” sensitivity in the controller menu. With Duke, I am able to adjust the “Turning”, along with the “looking up/down” sensitivity but when I try to adjust the strafing or moving forward, neither of them change? Does Duke3D have a hardcoded speed for those 2 options? Regarding Shadow Warrior, it’s the same issue but if I turn the sensitivity all the way down then it reacts to it and moves slow but if I turn it up, they don’t go any faster? Hopefully, you would be able to give me some info on this problem. I’m new to this source port and I love it so far. I was just wondering why I can’t adjust those settings. Thank you! -Matt

**Comment by mjr4077au** [comment]
This seems to be working fine here from my own XInput Xbox 360 controller. I'd possibly try deleting your config file and starting again.

Please note that a speed of 1.0 is technically half the player's speed as well. We decided not to make 1.0 full speed to allow a bit more control to the end user. A sensitivity of 2.0 is top speed and anything faster make you reach top speed with less input to the analogue stick.

![image](https://user-images.githubusercontent.com/48643140/145942289-72c658c2-86e4-4229-8b44-9bada502625d.png)

https://user-images.githubusercontent.com/48643140/145942371-c1b453f2-4d08-4462-9745-f1d7c3c8f2bf.mp4

https://user-images.githubusercontent.com/48643140/145942387-0e1355d7-71a9-4368-8d6a-6cf92a46dc27.mp4

**Comment by Matty4818** [comment]
Okay, so I’m able to decrease the sensitivity on them both but I can’t go past 2.000 on either of them because that’s the top speed?

**Comment by mjr4077au** [comment]
You can go past 2.000, that's fine, but 2.000 is full speed. What I mean by that is, if you set it to 2.000, it'll take the full amount of articulation on analogue stick to use full speed. If you set it to 4.000, pushing the stick half way would give you top speed, but pushing it further won't do anything further at that point. Basically, you can't just set it to some infinite number and run around faster than the game would let you otherwise.

**Comment by Matty4818** [comment]
Are you referring to leaving the very first overall sensitivity to 1.000(the one on top of the page) or the overall sensitivity to 1.000 on strafing and moving forward?

**Comment by mjr4077au** [comment]
I'm suggesting leaving the overall sensitivity at 1.000 and adjusting each axis how you'd like them to be. Hopefully the out of box defaults aren't too far off how most players would like, the person I was testing this with said it all felt pretty good.

With a overall sensitivity of 1.000 and moving forward/strafing at 2.000, that'd give you full speed at 100% articulation of your analog stick. If you'd like it more sensitive, by all means keep going but its impossible to make the input faster than you could achieve with a keyboard.

Please let me know if you have any further issues with the sensitivity. Our input code is unified so there's no reason why it would be different for Duke vs. SW. All my testing before across all the games went well.

**Comment by coelckers** [comment]
Things like this really only can get some reasonable default for average hardware. The deviations are so high that it is unavoidable to properly calibrate and adjust a controller before using it. The same goes for mice. Some are too slow, others too fast, there's just no way to provide a one-size-fits all setting.
