### ISSUE TITLE
[BUG] Possibly misinterpreted voxel flag in new renderer.

### ISSUE THREAD

**Issue by mjr4077au** [coelckers/Raze#605]
### Raze version

1.4pre

### Relevant hardware info

NVIDIA GeForce GTX 970

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Some voxel replacements don't render correctly in the new renderer, and I can only put it down to a possibly misused flag when processing the voxel.

New renderer:
![Duke_0050](https://user-images.githubusercontent.com/48643140/145950660-900688cb-646b-4df7-8c17-34095392636a.png)

Polymost:
![Duke_0051](https://user-images.githubusercontent.com/48643140/145950667-357e59ce-b219-473d-891e-3969d325858a.png)

New renderer:
![Duke_0052](https://user-images.githubusercontent.com/48643140/145950675-9a03d683-7dbf-467e-9f3c-ea60b743c3a2.png)

Polymost:
![Duke_0053](https://user-images.githubusercontent.com/48643140/145950683-fe0388d8-0f65-4310-82bd-5eefce73799e.png)

The only thing that seems different on these is that one sprite is flipped:

![Duke_0049](https://user-images.githubusercontent.com/48643140/145950809-e5f0dc4b-f4be-46e4-8527-d77412f015a7.png)

**Comment by coelckers** [comment]
The cull mode didn't take sprite flipping into account.
Fixed in 8cb871e5ff1a03d1d43fdc6beede905a38e168e4

**Comment by coelckers** [comment]
Fixed for real in eeabe0fe6dc072a0175ca71ca8e95c105d155d73
