### ISSUE TITLE
[BUG] [macOS] Folders not recognised in ~/Library/Application Support/Raze (Duplicate of #434, but fix below)

### ISSUE THREAD

**Issue by shinra-electric** [coelckers/Raze#606]
### Raze version

1.3.0

### Which game are you running with Raze?

Shadow Warrior

### What Operating System are you using?

Mac OS

### Relevant hardware info

M1

### Have you checked that no other similar issue already exists?

- [ ] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

This is the same issue as #434 but I have found a fix for it. 

The issue: Raze is looking for the game files in ~/Library/Application Support/Raze. This is the correct behaviour. However, it currently does not recognise any data folders there. 

The fix: 
In ~/Library/Preferences/raze.ini there are the [GameSearch.Directories] at the top. 
Adding `Path=/Users/[Your user name]/Library/Application Support/Raze/*` with a wild star will allow Raze to locate the data files. 

This ini file seems to be auto-generated, I'm not sure where in the codebase this should be added. 

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Put data folders in ~/Library/Application Support/Raze
2. Try to open Raze

**Comment by coelckers** [comment]
Added in 910c0e61cabe4780e86b5f64d5f7f92f268f8dc7
