### ISSUE TITLE
[BUG] Life's A Beach, Coolbox and Radio voxels are levitating in midair.

### ISSUE THREAD

**Issue by De-Seppe** [coelckers/Raze#610]
### Raze version

Raze 1.3.1, Raze 1.4pre-35-ga94f29860

### Which game are you running with Raze?

Duke Nukem 3D

### What Operating System are you using?

Windows 10

### Relevant hardware info

i7-10750H@2.60GHz, GeForce GTX 1650 Ti

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

In Duke Caribbean, the voxel objects 
3791_coolbox.kvx
3792_radio.kvx
are hovering in midair, likely due to incorrect Y-axis offsets.

https://github.com/NightFright2k19/duke3d_voxelpack, commit 8ed4e53

Issue also described at https://github.com/NightFright2k19/duke3d_voxelpack/issues/76 where it is described as a Raze bug.

![127737764-471a6d88-6f1d-48d3-a20f-6108a44c0725](https://user-images.githubusercontent.com/71447857/146743018-38f882a1-b3f9-466a-a3e9-72f3e0ae7ba2.jpg)
![127737760-d3f73579-ef04-4cf8-b595-b0a2faa19531](https://user-images.githubusercontent.com/71447857/146743026-9976726f-768a-493e-9514-51b730adb259.jpg)

### Steps to reproduce the behaviour.

Start raze with -file "duke3d_voxelpack-master.zip"
Select Duke Caribbean: Life's a Beach (vacation) & Vulcan renderer
Start the game, run to the beach check coolbox and radio voxel.

### Your configuration

```ini
default configuration
```

### Provide a Log

not relevant

**Comment by Dzierzan** [comment]
That's not Raze's issue. It also happens in eduke32. I've been trying to do something about that, but it was no use.

**Comment by coelckers** [comment]
These sprites appear to have a very bad y-offset. That radio, for example, has -31, and to compensate it is placed quite a bit off the ground. Scaled by the yrepeat this amounts to roughly 13 texel units - the sprite has been placed 12 texel units (3072 z-map units) above ground which nearly perfectly evens out that discrepancy.

The voxels appear to have their pivots at the bottom, which with these weird sprites simply does not match.
Definitely not an engine bug, both renderers reproduce this identically. The voxels need to have pivots that correspond to the origin point of the sprites they are supposed to replace.
