### ISSUE TITLE
[BUG] Usermap's music is not played

### ISSUE THREAD

**Issue by Dzierzan** [coelckers/Raze#612]
### Raze version

Raze 1.3.1

### Which game are you running with Raze?

Duke Nukem 3D

### What Operating System are you using?

Windows 10

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

When a custom map is loaded via console and it has custom music which is named exactly the same as map's name, the music will not be loaded.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. 
2.
3.

**Comment by coelckers** [comment]
fixed in our work branch
