### ISSUE TITLE
[Feature] Blood: Smoother sprite interpolation on sector objects.

### ISSUE THREAD

**Issue by mjr4077au** [coelckers/Raze#613]
### Raze version

1.4pre

### Which game are you running with Raze?

Blood

### Is your feature request related to a problem? Please describe.

Hard to see how rough this key is from the 30 fps video here from E1M4, but it could be better. Its not a break, NBlood is the same here.

https://user-images.githubusercontent.com/48643140/147872324-0bc11152-3470-4294-85ba-584d3dff0921.mp4

**Comment by coelckers** [comment]
A savegame would have been more useful than a video... :(

**Comment by coelckers** [comment]
Lol, what a stupid bug. Fixed in 3b833029b0c9f953f74c381f3b6a448d2d72e300
