### ISSUE TITLE
[Feature] Blood: Interpolate waterfall in E1M8 (secret level)

### ISSUE THREAD

**Issue by mjr4077au** [coelckers/Raze#614]
### Raze version

1.4pre

### Which game are you running with Raze?

Blood

### Is your feature request related to a problem? Please describe.

[save0014.zip](https://github.com/coelckers/Raze/files/7798886/save0014.zip)

Please note I slowed down time to exasperate the issue.

https://user-images.githubusercontent.com/48643140/147872781-1c3e5cdd-d63d-41bf-885c-1f81e4e4a1e0.mp4

**Comment by coelckers** [comment]
fixed in 00ffc8b6a2227b2e8d94e8ec813f60f7ebd116d5
Just a typo...
