### ISSUE TITLE
[BUG] Blood: Make `mario` cheat work with original syntax.

### ISSUE THREAD

**Issue by mjr4077au** [coelckers/Raze#615]
### Raze version

1.4pre

### Which game are you running with Raze?

Blood

### A clear and concise description of what the bug is.

The `mario` cheat only works in our chat box if there's no space between the cheat name and the episode (`mario1 2`). The original syntax was `mario 1 2` and this does not work, leading to confusion among players.

**Comment by coelckers** [comment]
fixed in 7915fb7ef107a322599fd30d2314954fe9359e4f
