### ISSUE TITLE
[BUG] Performance issues in big user maps

### ISSUE THREAD

**Issue by Axldomi** [coelckers/Raze#619]
### Raze version

Latest devbuild 13/1/2022

### Which game are you running with Raze?

Duke Nukem 3D

### What Operating System are you using?

Windows 10

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

I decided to play some big user maps in Raze. I tried the following user map in Raze :

https://msdn.duke4.net/hotwoudrichem.php

Right in the beginning I get severe stuttering/performance issues in both the Polymost and Raze3D renderer. 

However when I decided to play the same map in EDuke32, performance was buttersmooth.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Download the user map : https://msdn.duke4.net/hotwoudrichem.ph
2. Play the map in Raze.

**Comment by coelckers** [comment]
It's just as slow for me with EDuke32 - I get 30 fps in Raze with the new renderer, 44 fps with Raze/Polymost and 35-40 fps in EDuke32.
This map is the absolute worst case scenario imaginable - it is huge and has absolutely nothing in sight that may obstruct what lies behind and save processing time

**Comment by Axldomi** [comment]
Thank you for looking into the iussue, but still latest version of EDuke32 is giving me here 130 fps (see screenshot) while Raze is indeed only giving me 30-40 fps (dependend on which renderer I use). And it's not that I'm using a beast of a PC.

![duke0000](https://user-images.githubusercontent.com/71838912/149391587-d9869530-6a3e-497b-a987-8f98fa423f7d.png)

I agree it's a huge open map, but still EDuke32 manages to give a far smoother experience here (on my end).

**Comment by coelckers** [comment]
What kind of graphics card do you have? NVidia or AMD?

**Comment by Axldomi** [comment]
Nvidia Geforce 1060.

**Comment by coelckers** [comment]
We did some investigations and found the bottlenecks for both renderers.
Polymost had a recent optimization in EDuke32 which we never pulled, but that makes a massive difference on this map - and for the new renderer there was a sorting issue which created a lot of unnecessary render objects that dragged down performance.

**Comment by Axldomi** [comment]
This is excellent news! I'll be sure to test this out later. Many thanks for the quick response.

**Comment by Axldomi** [comment]
Using the latest Raze dev version (15/1), there seems to be an improvement, but still nowhere near the performance EDuke32 manges to produce in this user map... weird

**Comment by mjr4077au** [comment]
Are you able to try with a fresh config? Things like antialiasing, multisampling etc will have an adverse performance. Also try Vulkan as the may be a minor stall in the OGL code that won't help here.

**Comment by Axldomi** [comment]
Using Vulkan did the trick. Performance is much smoother now. Thx !
