### ISSUE TITLE
[BUG] "Bath House" level causes assert failure when going upstairs

### ISSUE THREAD

**Issue by Talon1024** [coelckers/Raze#621]
### Raze version

Raze 1.4pre-1291-g7b1d99373

### Which game are you running with Raze?

Shadow Warrior

### What Operating System are you using?

Linux x86_64

### Relevant hardware info

Intel Core i3-3110M CPU, Intel HD Graphics 4000 GPU

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

When I try to go to the second floor of the "Bath House" level, Raze quits because of this assertion failure:

    raze: ../source/common/utility/tarray.h:301: T& TArray<T, TT>::operator[](size_t) const [with T = walltype; TT = walltype; size_t = long unsigned int]: Assertion `index <= Count' failed.

[Here's a saved game](https://github.com/coelckers/Raze/files/7873086/save0005.zip)

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Load the saved game
2. Try to go to the second floor
3. The game will quit with an assertion failure if you are running a debug build

### Your configuration

```ini
vid_renderer=true
```

**Comment by coelckers** [comment]
fixed in e2061dbcc6e556a793a200b447f06c6e1234389f
