### ISSUE TITLE
[BUG] Guardian's fireballs misaligned

### ISSUE THREAD

**Issue by Talon1024** [coelckers/Raze#622]
### Raze version

Raze 1.4pre-1291-g7b1d99373

### Which game are you running with Raze?

Shadow Warrior

### What Operating System are you using?

Linux x86_64

### Relevant hardware info

Intel Core i3-3110M CPU, Intel HD Graphics 4000

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

The guardian (green enemy)'s fireballs are misaligned. See the screenshots.
![ShadowWarrior_0002](https://user-images.githubusercontent.com/6550500/149597941-58ccf0df-4d7d-46cc-8df9-4bddeb701827.png)
![ShadowWarrior_0001](https://user-images.githubusercontent.com/6550500/149597946-1bc04624-7795-4e76-aafd-3f0847c596f7.png)

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Start a new game on the Code of Honor episode
2. The guardian (green enemy) will shoot one of his fireballs without aiming vertically, but the other one will be aimed vertically

### Your configuration

```ini
vid_renderer=true
```

**Comment by coelckers** [comment]
Fixed in c5b382907de81b398b63c9b3a630006e003b12a2
