### ISSUE TITLE
[Feature] Blood tome picking text colour and some extras

### ISSUE THREAD

**Issue by Akis-02** [coelckers/Raze#625]
### Raze version

1.3.1

### Which game are you running with Raze?

Blood

### What Operating System are you using?

Windows 10

### Is your feature request related to a problem? Please describe.

Picking up books in raze's blood doesnt change the colour of the text to be different from the other pickup messeges

### Describe the solution you'd like

Change the colour to what it is supposed to be, maybe implement an option to make that text appear reverently in a different place through the use of option customizations and maybe the same but with colour

### Add any other context or screenshots about the feature request here.

Picking up a book in nblood
![Screenshot (370)](https://user-images.githubusercontent.com/39632375/149660190-e707e638-e549-4e6d-ba4b-f9bacbbfda78.png)

VS

Picking up a book in raze
![Screenshot (371)](https://user-images.githubusercontent.com/39632375/149660264-3d6e951c-f91a-49df-afdf-04299ff778af.png)

**Comment by coelckers** [comment]
Added, but not using exactly the same color.
