### ISSUE TITLE
[BUG] Exhumed: Projectiles getting stuck on the floor

### ISSUE THREAD

**Issue by Dude27th** [coelckers/Raze#627]
### Raze version

1.4pre-1307

### Which game are you running with Raze?

Exhumed/Powerslave

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Footage from the bug in question: https://www.youtube.com/watch?v=XEFssgDoWeM

Seems like at a certain pitch projectiles don't check for colission with floors.
I've seen it happened with some projectiles of the mummies as well,  but I got it more consistenly on level 17 "Saqqara"

Here's the save on that level: https://mega.nz/file/DA9TSQQI#XAXJmF0ssg_kYVsfcYkELiyh5yrbGbKD-Viu7REtwMQ

### Steps to reproduce the behaviour.

Explain how to reproduce
1.  Grab the Earth Key
2. Having the Earth Key those traps will be activated and the bug can be appreciated at the section on the video
3.

**Comment by coelckers** [comment]
There doesn't seem to be an Earth Key placed on this map so I have no idea where to look in the level. I only played the game once and never get this far because when I did the engine was still too buggy.. The savegame from the start of the level doesn't really help.

**Comment by mjr4077au** [comment]
[save0016.zip](https://github.com/coelckers/Raze/files/7932882/save0016.zip)

Perhaps this save will help? Just walk forward towards the presses and the fireballs will spawn and get pressed into the ground.

**Comment by coelckers** [comment]
fixed in 0e89bffabd47ffac7637b0059de4e82a38880cee
