### ISSUE TITLE
[BUG] Choking hands are invisible

### ISSUE THREAD

**Issue by Talon1024** [coelckers/Raze#629]
### Raze version

Raze 1.4pre-1309-g19d8d65fd

### Which game are you running with Raze?

Blood

### What Operating System are you using?

Linux x86_64

### Relevant hardware info

Intel Core i3-3110M CPU, Intel HD Graphics 4000 GPU

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Once a hand starts choking you, you won't see the hand on your HUD like you should.

[Here's a saved game](https://github.com/coelckers/Raze/files/7910878/save0015.zip).

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Load the saved game
2. Let the hand start choking you to death
3. The hand won't appear on your screen like it should

### Your configuration

```ini
vid_renderer=true
```

**Comment by Talon1024** [comment]
For me, it works in Polymost, but not in Raze3D for some reason.

**Comment by Talon1024** [comment]
So I did a `git bisect`, and it said 70087ebc120239ae1b86f3478a0b80a7f97517bc is the commit which caused this bug.

**Comment by coelckers** [comment]
Thanks, I had Polymost on when checking it, so obviously it did not show. It was a simple ordering issue - it now got processed too late.
