### ISSUE TITLE
[BUG] Softlock in Duke3D E2L3

### ISSUE THREAD

**Issue by Talon1024** [coelckers/Raze#630]
### Raze version

Raze 1.4pre-1309-g19d8d65fd

### Which game are you running with Raze?

Duke Nukem 3D

### What Operating System are you using?

Linux x86_64

### Relevant hardware info

Intel Core i3-3110M CPU, Intel HD Graphics 4000 GPU

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

The thing that takes you between the two "sides" of E2M3 only moves once.

[Here's a saved game](https://github.com/coelckers/Raze/files/7910911/save0001.zip)

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Load the saved game
2. Press the switch to call the "thing"
3. Try to press the switch again, or any of the other switches inside it
4. None of them work

### Your configuration

```ini
vid_renderer=true
```

**Comment by Talon1024** [comment]
It looks like an issue with the saved game. I just tried to reproduce this from warping to E2L3, and I could not.

**Comment by mjr4077au** [comment]
Is the save game from an earlier build? It'd still be good to diagnose what went wrong here.

**Comment by coelckers** [comment]
I think it's related to this change: 24a67e194d65e2af38560b7db5f5825d7f337e63
That one could render savegames incompatible and it looks like that's what happened here.
Right now there's nothing I could do. That sector effector is missing some vital information and cannot operate as a result.
