### ISSUE TITLE
[BUG] Crash on first map Platoon Leader

### ISSUE THREAD

**Issue by Assassin877** [coelckers/Raze#633]
### Raze version

Raze 1.4.0

### Which game are you running with Raze?

WW2 GI

### What Operating System are you using?

Windows 10

### Relevant hardware info

Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz   2.59 GHz, 16.0 GB RAM, NVIDIA GeForce RTX 2060

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

While playing the first map of the first episode (Hill 41) of Platoon Leader, the game crashes at some point up the first hill. Have tried to recreate the bug, and it seems to happen every time. 

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Open the first map of episode 1 of Platoon Leader (Hill 41)
2. Run forward until the game crashes

### Your configuration

```ini
https://www.mediafire.com/file/w2aqh2r2q9ljz68/raze.ini/file
```

### Provide a Log

[CrashReport.zip](https://github.com/coelckers/Raze/files/7927847/CrashReport.zip)

**Comment by coelckers** [comment]
fixed in 58f535d3a41efa7988d44ae565d71c84c7dbec32
