### ISSUE TITLE
[BUG] Exhumed: Wasps seemingly all activate at level start and the noise is overbearing.

### ISSUE THREAD

**Issue by mjr4077au** [coelckers/Raze#635]
### Raze version

1.4.0

### Which game are you running with Raze?

Exhumed/Powerslave

### A clear and concise description of what the bug is.

[save0001.zip](https://github.com/coelckers/Raze/files/7937625/save0001.zip)

This is from LEV16.

https://user-images.githubusercontent.com/48643140/151070144-205f8b21-4b92-40c3-8d76-88d47d60d676.mp4

**Comment by coelckers** [comment]
Works like intended. Sad but true... :(
