### ISSUE TITLE
[Feature] Replication -load functionality

### ISSUE THREAD

**Issue by Tiddalick** [coelckers/Raze#636]
### Raze version

Raze 1.4.0

### Which game are you running with Raze?

Blood

### What Operating System are you using?

Windows 11

### Is your feature request related to a problem? Please describe.

The new map loading function in menu is **excellent!**
However, it seems that this does not accommodate more complex map packages such as Eviction (https://www.moddb.com/mods/eviction-addon-for-blood).

This can be easily run in raze using the **-load** command line argument to point to the top of the directory.

### Describe the solution you'd like

It would be excellent if this -load behavior was replicated in the new menu system by allowing the user to select a map directory, rather then always needing to specify an individual map.

**Comment by mjr4077au** [comment]
What you'd typically do with a pack like Eviction is drag and drop the zip file onto Raze.exe, then the maps in the zip file will appear in the user map window.

**Comment by Tiddalick** [comment]
Yes I am aware that is possible as well, but personally I dislike this approach to opening a file and much prefer the command line approach (or alternative change to the map loading functionality), hence my suggestion for an enhancement. :)

**Comment by coelckers** [comment]
These are totally distinct features.. The user map browser is not there to load episodes but to provide a list of all maps that are currently visible to the game in the loaded data and to provide an interface for starting them.

The main issue with in-game mod loading is that a lot of static resources - primarily the file system and the texture data - needs to be taken down and reconstructed. That's not something the underlying engine was designed for.
