### ISSUE TITLE
[BUG] Weird physics

### ISSUE THREAD

**Issue by Axldomi** [coelckers/Raze#639]
### Raze version

Raze 1.4

### Which game are you running with Raze?

Duke Nukem 3D

### What Operating System are you using?

Windows 10

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

In the flooded room in Flood Zone, I get some weird elements:

1. I can't jump up from the water
2. the clock in the same room can't be destroyed

![Duke_0004](https://user-images.githubusercontent.com/71838912/151567747-254c051a-8f0d-4bbd-a020-75ddd62ebcc0.png)

[save0000.zip](https://github.com/coelckers/Raze/files/7959559/save0000.zip)

Note: this was tested with Duke Nukem 3D 1.3d (non atomic).

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Load DN3D in Raze 1.4
2. Load the savegame
3. Try to jump and try to destroy the clock

**Comment by coelckers** [comment]
The clock seems to be an 1.3 thing. In 1.5 it can be shot but in 1.3 it can't. That goes for this sprite in general so it looks like in 1.3 it was never set up to be breakable.

For not being able to jump, DukeGDX behaves the same, so this looks like it's intended.

**Comment by Axldomi** [comment]
Thx. You're right.

About the jumping thing, behaviour is indeed the same as in RedNukem. You can't jump here either. 

I assume EDuke32 made a change because without "jumping" here, you can only access the area with the medkit above water once. When you try to access it after, you can't reach it unless you dive again and try it again.

Anyway, thx for looking into this!
