### ISSUE TITLE
[BUG] Glitch in new renderer Raze 3D - DN3D LA Rumble

### ISSUE THREAD

**Issue by Axldomi** [coelckers/Raze#640]
### Raze version

Raze 1.4

### Which game are you running with Raze?

Duke Nukem 3D

### What Operating System are you using?

Windows 10

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

In the level LA Rumble (E3M4), open the blue door. Depending on the angle, you will see glitches. See screenshot below. This glitch is not there in Poltymost, only in Raze3D.

![Duke_0000](https://user-images.githubusercontent.com/71838912/151571680-72f289d5-7a96-49b4-981f-7de84eb873ca.png)

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Load DN3D in Raze
2. Levelwarp to E3M
3. Open the blue near the beginning of the level

**Comment by coelckers** [comment]
I wonder when this broke, This place was working not too long ago...

**Comment by coelckers** [comment]
fixed in 686a648aa10a2cafa8867b53715f31892ad83bf7
