### ISSUE TITLE
[BUG] Laser tripbombs cause AOOB assert

### ISSUE THREAD

**Issue by Talon1024** [coelckers/Raze#641]
### Raze version

Raze 1.5pre-39-g8487d693f

### Which game are you running with Raze?

Duke Nukem 3D

### What Operating System are you using?

Linux x86_64

### If Other OS, please describe

Kubuntu 20.04

### Relevant hardware info

Intel Core i5-4690K CPU, GeForce GTX 970 GPU

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Laser tripbombs in Duke Nukem 3D cause an assertion failure after they are placed.

### Steps to reproduce the behaviour.

1. Go to a map where you can pick up a laser tripbomb, or where there is a laser tripbomb on the wall, such as E1L3 or E1L8.
2. Place a tripbomb on the wall
3. Wait for the laser to appear
4. Assertion failure (see log below)

### Your configuration

```ini
vid_renderer=Raze3D
```

### Provide a Log

```raze: ../source/common/utility/tarray.h:307: T& TArray<T, TT>::operator[](size_t) const [with T = int; TT = int; size_t = long unsigned int]: Assertion `index <= Count' failed.```

**Comment by coelckers** [comment]
fixed in a015958f66f6a387e60d5e6fa2addf3cc103eca1
