### ISSUE TITLE
[BUG] Blood HUD flame effect not drawing

### ISSUE THREAD

**Issue by carnivoroussociety** [coelckers/Raze#643]
### Raze version

Raze 1.4.0

### Which game are you running with Raze?

Blood

### What Operating System are you using?

Linux x86_64

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

For NBlood, when the player has been ignited (`gView->pXSprite->burnTime > 60`) viewBurnTime() will be called. This behavior has not been ported over to Raze

https://user-images.githubusercontent.com/38839485/151652525-ffe238f8-5d00-4f33-9740-018d573834c8.mp4

https://user-images.githubusercontent.com/38839485/151652556-afddd9ab-d502-4832-988f-330ce757d16e.mp4

### Steps to reproduce the behaviour.

1. Load any level in Blood
2. Equip spray can
3. Throw spray right below player

**Comment by coelckers** [comment]
The code for this is definitely present. Check hudsprites.cpp line 154

**Comment by coelckers** [comment]
This was using incorrect alignment flags. Fixed in b82198b351aa075861972702ad64ffd0d772e54f

**Comment by carnivoroussociety** [comment]
Thank you!
