### ISSUE TITLE
[BUG] Duke - E4M1 - can't shoot vent

### ISSUE THREAD

**Issue by Axldomi** [coelckers/Raze#644]
### Raze version

raze-x64-1.5pre-48-gdab1f7fce.7z

### Which game are you running with Raze?

Duke Nukem 3D

### What Operating System are you using?

Windows 10

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

In the cooling room of E4M1 "It's Impossible", you can't shoot the ventilator anymore. See screenshot below and savegame.

This works fine in EDuke32 and RedNukem.

![Duke_0006](https://user-images.githubusercontent.com/71838912/151701396-ff8880b2-b292-4bcc-95ee-a5d4340273fd.png)

[save0000.zip](https://github.com/coelckers/Raze/files/7965968/save0000.zip)

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Start Duke Atomic in Raze
2. Load the savegame
3. Try to shoot the ventilator

**Comment by coelckers** [comment]
fixed in fd6d09273ffd0c873429ac5a9c38b5b8ae4084e6
