### ISSUE TITLE
[BUG] Broken "spin cycle" on Faces of Death

### ISSUE THREAD

**Issue by madame-rachelle** [coelckers/Raze#646]
### Raze version

1.5pre-51-gb7cb878ad

### Which game are you running with Raze?

Duke Nukem 3D

### What Operating System are you using?

Windows 11

### Relevant hardware info

NVidia GTX 1650 - AMD Ryzen 7 3800X 8-Core Processor

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

There's a little spin-cycle thingy in the middle of the level on faces of death that's supposed to actually ... well, spin. It does it in kind of a crazy way. It interpolates as if it is spinning however it does not actually do it.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Load attached save
[broken-spin-e1l7.zip](https://github.com/coelckers/Raze/files/8007158/broken-spin-e1l7.zip)

### Your configuration

```ini
https://cdn.discordapp.com/attachments/384932761984696321/939027945601790012/raze-config.zip
```

**Comment by coelckers** [comment]
fixed in 951b93123af79ec0027d54b3765dba803c0ced90
