### ISSUE TITLE
[BUG] Natural sector light mode is too bright on a specific map

### ISSUE THREAD

**Issue by markanini** [coelckers/Raze#650]
### Raze version

v1.4.1

### Which game are you running with Raze?

Blood

### What Operating System are you using?

Windows 11

### Relevant hardware info

Nvidia 1050Ti

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

In Blood CP05:Steamboat natural sector light mode is significantly brighter than original.

I've played through most of the main campaign without noticing anything, so hopefully it's only a specific issue with this map
![Blood_0021](https://user-images.githubusercontent.com/15148553/153675638-44a8be5d-eed6-4c39-ad00-f7190e0654f4.png)
![Blood_0022](https://user-images.githubusercontent.com/15148553/153675644-d9e11f9e-fcc4-4fee-8eab-1aa6edcddfe7.png)
.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Run raze with default settings with sector light mode changed from default original to natural
2. type map cp05
3. switch back to original
![Blood_0021](https://user-images.githubusercontent.com/15148553/153675527-eb5f4472-02b1-41ce-a638-13c1903a67dd.png)
![Blood_0022](https://user-images.githubusercontent.com/15148553/153675534-75e8edfd-11d9-4f3f-9647-39a874bb9226.png)

**Comment by sinisterseed** [comment]
I personally can't say I would consider this a bug.

Of course, the new sector modes will still see further tweaks and improvements, but they were designed specifically to avoid some shortcomings of the vanilla sector light mode and its very aggressive depth fading in some cases. 

"Natural" in particular was meant to circumvent that issue, while High Contrast does, well, exactly what the same says, and provides a darker look to the maps.

**Comment by markanini** [comment]
> I personally can't say I would consider this a bug.
> 
> Of course, the new sector modes will still see further tweaks and improvements, but they were designed specifically to avoid some shortcomings of the vanilla sector light mode and its very aggressive depth fading in some cases.
> 
> "Natural" in particular was meant to circumvent that issue, while High Contrast does, well, exactly what the same says, and provides a darker look to the maps.

Good point. I should have said this report is making the assumption on that the new sector light mode aims to have brightness parity with the original one under all conditions. That may not be true for all I know.

**Comment by coelckers** [comment]
fixed in f1859c69f0b9223ab0e9ccfd5e619ea66bec53a4
