### ISSUE TITLE
[BUG] Blood: Trauma Therapy path sectors not moving

### ISSUE THREAD

**Issue by Bloody-Tom** [coelckers/Raze#652]
### Raze version

1.4.1

### Which game are you running with Raze?

Blood

### What Operating System are you using?

Windows 10

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

I have a problem with the new episode of the mod "Trauma Therapy".

In maps the make heavy use of path sectors these will not move. If a map has some path sectors, they move without problem.

The episode can be found here: 

https://www.moddb.com/mods/blood-trauma-therapy/downloads/trauma-therapy-episode-ii

For example take a look at:

1. tt18.map 

The boat is supposed to move out of the sector and return when the lighthouse is activated.

2. tt19.map 

The boat is supposed to move to the harbour.

3. tt20.map

A group of path sectors (the train) is supposed to move you to the beginning of the level.

Two playtesters already reported the same issues to me. So the problem is not on my end.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Play TT18.map, TT19.map, TT20.map
2. 
3.

**Comment by coelckers** [comment]
fixed in 2f55d2a1c74ae053c394655166cc02564e5ba84e
