### ISSUE TITLE
[BUG] Random custom voxel switching 

### ISSUE THREAD

**Issue by Bloody-Tom** [coelckers/Raze#653]
### Raze version

1.4.1

### Which game are you running with Raze?

Blood

### What Operating System are you using?

Windows 10

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Custom voxels in the mod "Trauma Therapy: Episode 2" seem to swap in a consistent interval. This is not intended.

Looks like Raze tries to apply an oscillating animation to the voxels stored in voxel.dat. The custom voxels seen here have subsequent voxel ids (186,187,188).

https://user-images.githubusercontent.com/99460972/154815271-3271ed5f-becf-4c23-af23-e6ca2e0ef5c6.mp4

The mod can be found here:
https://www.moddb.com/mods/blood-trauma-therapy/downloads/trauma-therapy-episode-ii

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Bug can be found in tt19.map
2. At the beginning, look right
3.

**Comment by coelckers** [comment]
fixed in cc6629a95f5ff108e141107c4effd09c3f041a37
