### ISSUE TITLE
[BUG] When dead by crusher in Exhumed, crusher can expose skydome in new renderer.

### ISSUE THREAD

**Issue by mjr4077au** [coelckers/Raze#654]
### Raze version

1.5pre

### Which game are you running with Raze?

Exhumed/Powerslave

### A clear and concise description of what the bug is.

Easiest setup is to just get to the crushers on the training map.

https://youtu.be/qsPa6TWxwMY

**Comment by mjr4077au** [comment]
https://user-images.githubusercontent.com/48643140/154836523-655963b0-dbd1-4653-8093-8a6702f25d32.mp4

Try this instead, framerate should be higher.

**Comment by coelckers** [comment]
This one's pretty much unavoidable. If the crusher fully closes there is no space left for the view - the result is that at least one of the sector's planes cannot be rendered anymore.
