### ISSUE TITLE
[BUG] Parallaxing skies don't have the proper shades with the new renderer

### ISSUE THREAD

**Issue by NY00123** [coelckers/Raze#658]
### Raze version

1.5pre-103-gb6eadbccb

### Which game are you running with Raze?

Duke Nukem 3D

### What Operating System are you using?

Linux x86_64

### Relevant hardware info

GeForce GTX 1070 Ti

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Parallaxing skies are rendered with the wrong shades while the new renderer is used. This was originally found in a secret area within a few revisions of my map, NYSRace.map. A smaller test-case is attached.

[pshdtest.zip](https://github.com/coelckers/Raze/files/8185889/pshdtest.zip)

Polymost:
![Duke_0011](https://user-images.githubusercontent.com/6780140/156764607-33c7aa6c-39d9-4036-8861-65e256d2d591.png)

Raze3D:
![Duke_0012](https://user-images.githubusercontent.com/6780140/156764644-f5d0df25-5897-4dcf-8113-cf5913d4ec49.png)

### Steps to reproduce the behaviour.

Load the map.

**Comment by coelckers** [comment]
added in 380864d6fb7121b49f235e08ce43aa9d6920b2ce
