### ISSUE TITLE
[BUG] The overhead map's palette isn't refreshed when it should be

### ISSUE THREAD

**Issue by NY00123** [coelckers/Raze#659]
### Raze version

1.5pre-103-gb6eadbccb

### Which game are you running with Raze?

Duke Nukem 3D

### What Operating System are you using?

Linux x86_64

### Relevant hardware info

GeForce GTX 1070 Ti

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

When the palette in a session of duke3d should be changed, this doesn't immediately occur while the overhead map is used exclusively (without 3D rendering).

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Start E1L4, show the overhead map in textured mode (no 3D view) and then submerge into the water.
2. This can also be reproduced by showing the map and then toggling the night vision goggles on/off.

**Comment by coelckers** [comment]
fixed in a071479339bea27aa886956ac40d608953201c2b

**Comment by NY00123** [comment]
Confirming as fixed, thanks!
