### ISSUE TITLE
Moved Files From Previous Version Of Raze and now i cant get blood to launch 

### ISSUE THREAD

**Issue by travistouchdown69** [coelckers/Raze#666]
### Raze version

1.4.1

### Which game are you running with Raze?

Blood

### What Operating System are you using?

Windows 10

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

whenever i try to start blood it gives me this error message that says "BLOOD.ini" is missing 
it worked before in 1.3.1 without this file 

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Startup Raze
2. Choose Blood (base game or expansions)

**Comment by coelckers** [comment]
Blood.ini is essential. Without it you have no episode definitions. Apparently you made an incomplete copy of the game or left blood.rff without the remaining game data in a place where Raze can find it.
