### ISSUE TITLE
[BUG] [Powerslave/Exhumed] Flickering Lamp

### ISSUE THREAD

**Issue by orderorder** [coelckers/Raze#675]
### Raze version

Raze 1.5pre-115-g16c81f0b1-m

### Which game are you running with Raze?

Exhumed/Powerslave

### What Operating System are you using?

Linux x86_64

### If Other OS, please describe

Manjaro x86_64 / Windows 10

### Relevant hardware info

AMD A10-7850K Radeon R7 / RTX 3070m

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

![Lamp_Bug](https://user-images.githubusercontent.com/7293829/163251929-988cc922-6d91-4381-812f-056e3e3f1d75.gif)

### Steps to reproduce the behaviour.

Savegame

[save0013.dsave.zip](https://github.com/coelckers/Raze/files/8484024/save0013.dsave.zip)

**Comment by coelckers** [comment]
fixed in f245a708830e21f5a52366a7d4966dd3d7600bc2
