### ISSUE TITLE
[BUG] [Powerslave / Exhumed ] Disappearing Block

### ISSUE THREAD

**Issue by orderorder** [coelckers/Raze#676]
### Raze version

Raze 1.5pre-115-g16c81f0b1-m

### Which game are you running with Raze?

Exhumed/Powerslave

### What Operating System are you using?

Linux x86_64

### If Other OS, please describe

Manjaro x86_64 / Windows 10

### Relevant hardware info

AMD A10-7850K Radeon R7 / RTX 3070m

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

![Block_Bug](https://user-images.githubusercontent.com/7293829/163253118-c37e67d7-c451-4e1c-a1ae-2a849d4625f6.gif)

When we push this block to a certain position it disappears according to our position

Savegame

[save0017.dsave.zip](https://github.com/coelckers/Raze/files/8484083/save0017.dsave.zip)

**Comment by Dude27th** [comment]
which renderer where you using ?

**Comment by orderorder** [comment]
This happens with both renderers. After you move that block to that position

**Comment by coelckers** [comment]
What can be seen here is a movable element being pushed out of its origin sector. If the map allows this it is a mapping error.
As long as the origin sector is vislble, the box is, too. But once it goes out of view there's nothing that may cause the box to be picked up by the renderer.

Sorry, can't fix.

**Comment by Gaerzi** [comment]
Can't the origin sector be updated as the object moves?

**Comment by coelckers** [comment]
No, this is a set of walls, not a sprite. There's no facilities in the engine to handle this, it'd also require making the geometry creator aware of walls that can change sectors.
