### ISSUE TITLE
[BUG] Duke E3L1 level complete plays Ep 3 end cutcene and returns to main menu after, cannot get to E3L2

### ISSUE THREAD

**Issue by carn1x** [coelckers/Raze#677]
### Raze version

1.1.3

### Which game are you running with Raze?

Duke Nukem 3D

### What Operating System are you using?

Windows 10

### Relevant hardware info

5600X CPU, 6700XT GPU

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Playing E3L1 and I hit the level exit button. Immediately after the cutscene shows the football field of the Ep 3 boss dead and the cutscene plays out. After this the game returns to the main menu with splash animations.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Play E3M1 from Atomic edition from GOG
2. Finish the level

**Comment by coelckers** [comment]
Works correctly in 1.4.1. Please update your version.
