### ISSUE TITLE
[BUG] Wanton Destruction, level 9, unable to get into fifth secret

### ISSUE THREAD

**Issue by Froyd1** [coelckers/Raze#680]
### Raze version

Raze 1.4.1

### Which game are you running with Raze?

Shadow Warrior

### What Operating System are you using?

Windows 8

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

In the level Military Base, I'm unable to get inside the small corridor where it triggers the fifth secret. Only way is to noclip, in order to trigger it. Is there any way to fix this bug, without nocliping?
![ShadowWarrior_0004](https://user-images.githubusercontent.com/80136749/169179844-617a912c-e2c8-4457-8f66-6f65a29dae07.png)

### Steps to reproduce the behaviour.

Explain how to reproduce
1. 
2.
3.

**Comment by coelckers** [comment]
Does this work in other ports?
Keep in mind that Wanton Destruction is known to have a few issues from incomplete testing as this was never officially released as the planned commercial extension it was planned to be.

**Comment by Froyd1** [comment]
I just played Shadow Warrior Classic Redux without a port, and the secret triggered right away when I opened the secret door. So it must be Raze?

**Comment by coelckers** [comment]
This is a known map bug, apparently some ports have added workarounds for the secret. Normally they only trigger if you are inside the sector.

From the walkthrough:

    Note: the area beyond is too tight to walk inside, but unless you walk
    inside, you won't trigger the secret! You can still get the fortune cookie
    it contains, but you need to use the noclip cheat to actually get this
    secret to be counted.

**Comment by coelckers** [comment]
GDX indeed adds a workaround for this, looks like it was directly taken from the Redux port. The main problem here is that it is a very, very dirty thing to do...

**Comment by Gaerzi** [comment]
In GZDoom this could be fixed by removing the secret flag from the sector and adding its equivalent to the fortune cookie it contains...
