### ISSUE TITLE
[BUG] Duke Penthouse Paradise, unable to get out from under ocean in most places

### ISSUE THREAD

**Issue by zanesix** [coelckers/Raze#683]
### Raze version

raze-x64-1.5pre-171-gf245a7088

### Which game are you running with Raze?

Duke Nukem 3D

### What Operating System are you using?

Windows 10

### Please describe your specific OS version

Windows 10 Home 21H1

### Relevant hardware info

Intel i5 4440, Nvidia GTX 1070

### Have you checked that no other similar issue already exists?

- [x] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

At the very beginning of the Penthouse Paradise map (officially supported by Raze as of 1.3), diving underneath the ocean and trying to resurface results in the player just getting teleported back under the ocean; would probably be inescapable if it wasn't for the waterfall area by the shore. Works as intended on Eduke32.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Start up the Penthouse Paradise map
2. Dive into the body of water directly in front of you
3. Try to resurface

### Your configuration

```ini
https://drive.google.com/file/d/1jrnb2eSrHr8vtC6eOcG96Xz7U9-iLw29/view?usp=sharing
```

### Provide a Log

https://drive.google.com/file/d/1_PR7WpXnpzuYYvRgdxMSKI4Up0Qvhspt/view?usp=sharing

**Comment by mjr4077au** [comment]
Video from EDuke32, current release:

https://user-images.githubusercontent.com/48643140/171311741-feff6a83-d360-4eb3-a23f-7e8afcf0e558.mp4

Video from JFDuke3D, current release:

https://user-images.githubusercontent.com/48643140/171312777-04ac3e9b-ab41-49fb-b587-f03f04a374e8.mp4

As far as I'm concerned, this map is just stuffed. JFDuke3D did work better if you were in the right spots, but there's still plenty of places where you cannot resurface.

I can't be bothered trying to set this up on DOSBox to test there, but if you can, and you can show it working faultlessly under DOS, that would give good reason to work on this.

**Comment by zanesix** [comment]
Wow, you're right. That's really strange. I was using an old build of Eduke from september to test it and it worked fine there, but using a clean build with the newest version breaks it again.

My bad... I guess
