### ISSUE TITLE
Duke Nukem crash when loading E3L9 Stadium

### ISSUE THREAD

**Issue by Q3BFG10K** [coelckers/Raze#685]
Win10-64. Raze 1.4.1. Duke Nukem Atomic edition (duke3d.grp file only) from Steam.

Select new game -> user map -> E3L9 -> "let's rock". Mostly crashes or occasionally loads an empty map.

Crash dump attached.

[CrashReport.zip](https://github.com/coelckers/Raze/files/8972817/CrashReport.zip)

**Comment by coelckers** [comment]
I can reproduce it with 1.4.1, but this seems to work with the current master branch.
