### ISSUE TITLE
Shadow Warrior Wanton crane not rendered

### ISSUE THREAD

**Issue by Q3BFG10K** [coelckers/Raze#687]
Raze 1.4.1, Win10-64. WT.GRP (file only) from Steam Classic Redux. Screenshot/save attached.

From this angle the crane is invisible with blue seams in the floor. Just walk forward and it'll pop into view again.

[Crane.zip](https://github.com/coelckers/Raze/files/8972899/Crane.zip)

**Comment by coelckers** [comment]
This is caused by overlapping walls which the new renderer cannot handle well from the looks of it.

**Comment by coelckers** [comment]
This actually glitches with all renderers, albeit differently. I added a hack to let at least the new Raze3D renderer deal with this - for Polymost a fix is not doable.

What happens here plain and simply violates Build engine specs by having visible geometry extend into the void.
