### ISSUE TITLE
[BUG] Route66: Gators are girls when using commandline, but work with launcher

### ISSUE THREAD

**Issue by not43s** [coelckers/Raze#690]
### Raze version

1.4.1

### Which game are you running with Raze?

Redneck Rampage

### What Operating System are you using?

Windows 10

### Please describe your specific OS version

Windows 10

### Relevant hardware info

i7-5930K, Nvidia 980TI

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

The gators in "Carnival of Terror" are girls when you play game via commandline, but are normal when you play game via launcher.

This is also present in commit `47aa110441a7938b8a129437c3fdad17ed340acf`.

When you play with launcher:
![20220711_141159](https://user-images.githubusercontent.com/78993338/178365787-8db5fc7c-c4d4-4c25-bb08-f7f48091431c.jpg)

When you play with commandline:
![screenshot-2022 07 11-23h11 41](https://user-images.githubusercontent.com/78993338/178365794-ecd45ef1-241e-4438-900e-81da982e1137.png)

### Steps to reproduce the behaviour.

Steps to reproduce:
1. Download and extract fresh raze 1.4.1 binary
2. Create directory `rr` somewhere raze will not autodetect
3. Place `REDNECK.GRP` in `rr` (I used GOG version)
4. Place zip file in `rr` called `route66.zip` with content described here (I used GOG version): https://forum.zdoom.org/viewtopic.php?f=347&t=71962&p=1186415#p1186413
5. Create shortcut to `raze.exe` and edit target appropriately: `PATH_TO\raze.exe -gamegrp "PATH_TO\rr\REDNECK.GRP" -file "PATH_TO\rr\route66.zip" -route66`
6. Launch the game using shortcut
7. Start new game on first episode on lowest difficulty
8. Run to truck to start next level
9. Run through "Carnival of Terror" until you get to gator pit (Its about ~10 sec. into level)
10. Check out the ladies

### Provide a Log

[raze.log](https://github.com/coelckers/Raze/files/9087901/raze.log)
[raze.ini.txt](https://github.com/coelckers/Raze/files/9087909/raze.ini.txt)

**Comment by coelckers** [comment]
The -route66 switch is for launching it directly from the GOG folder without zipping it all up. The way you launch it it simply misses some stuff that is needed. 
"raze -gamegrp "PATH_TO\rr\route66.zip" would be the right way to do it.

**Comment by not43s** [comment]
Thank you for the reply.

I just tried this and I get "Unable to find any Game Data", etc. I guess I'm not understanding how the files need to be loaded. I was under the impression the base game `REDNECK.GRP` was required and the expansion `route66.zip` just overrides a bunch of files in the virtual filesystem. Again, `route66.zip` only contains the files you listed [here](https://forum.zdoom.org/viewtopic.php?f=347&t=71962&p=1186415#p1186413).

If I set shortcut to `raze -gamegrp "PATH_TO\rr\REDNECK.GRP" -file "PATH_TO\rr\route66.zip` then the game launches but the expansion is not found. I either need to set the `-route66` flag or specify `-x GAME66.CON` to override the base game.

Either way, the game loads with expansion but then the gators are missing.

**Comment by coelckers** [comment]
The thing is that this isn't how it is supposed to be launched. For that zip to work you need redneck.grp in the list of searched game directories and load route66.zip with -gamegrp.
If you want to load it as an add-on with -file the contents need to be a bit different.
