### ISSUE TITLE
[Feature] Disable joystick aiming from being affected by run toggle

### ISSUE THREAD

**Issue by OldFinbar** [coelckers/Raze#693]
### Raze version

Raze 1.4.1

### Which game are you running with Raze?

Duke Nukem 3D

### What Operating System are you using?

Windows 10

### Is your feature request related to a problem? Please describe.

I've noticed that Duke's turning and look up/down is affected whether run is toggled on or off when using a controller. He runs twice as fast when run is toggled on, but the aim movement speed is also doubled.

### Describe the solution you'd like

It'd be great if the run toggle button would only affect Duke's movement and strafing and not his aiming as well.

### Describe alternatives you've considered

I use a PS3 controller through DS4Windows which is outputting as an XBOX 360 controller, which allows me to configure the right thumbstick to emulate mouse movement, however it isn't as smooth as Raze's inbuilt joystick support.

The other alternative is to set the left thumbstick strafing and movement to "overall sensitivity=2.0" and use the stick to modulate Duke's movement speed rather than relying on using the "run toggle button"

**Comment by mjr4077au** [comment]
@OldFinbar, this can be done, and possibly should as it'd match GZDoom's behaviour here. What speed do you suggest should be the "out of the box" speed? When I was tuning the values, the running speed was probably the intended default from our end.

**Comment by OldFinbar** [comment]
Cheers for looking into it @mjr4077au. The running speed being the intended default makes sense to me and that would be my suggestion for the "out of the box" speed too as it is still very controllable on a controller. Thank you and all the best!
