### ISSUE TITLE
Blood: Rendering glitch in Spare Parts (E3M5)

### ISSUE THREAD

**Issue by mjr4077au** [coelckers/Raze#87]
Kindly supplied by Phredreeke. Video footage: https://gfycat.com/sandyknobbyherring

This occurs both with and without palette emulation, and apparently occurred for quite some time in GDX where it is now resolved. Unsure whether this occurs in NBlood.

**Comment by coelckers** [comment]
I wish GDX had better commit messages - I have no idea what to look for and when it was fixed.

**Comment by mjr4077au** [comment]
Yeah, that does suck... Apparently it _doesn't_ occur in NBlood but I know thats not much help to you either, sorry.

I might go onto the GDX Discord and see if anyone will kindly entertain me about if they know of the issue and when it was fixed.

**Comment by sinisterseed** [comment]
Considering this doesn't occur in NBlood either, I have a feeling this is something that probably broke at some point.

I don't recall seeing this either, including Raze.

**Comment by Phredreeke** [comment]
I believe this was fixed before BloodGDX was open sourced so there might not even be a commit to find for it

**Comment by mjr4077au** [comment]
@Phredreeke just wondering if you can please test these spots out? I've just pushed a commit that I hope fixes these issues. Appeared to be a ROR issue.

**Comment by sinisterseed** [comment]
> @Phredreeke just wondering if you can please test these spots out? I've just pushed a commit that I hope fixes these issues. Appeared to be a ROR issue.

Both maps are fixed now.
