### ISSUE TITLE
Blood Cryptic Passage: HOM effect in Gothic Library (CP03).

### ISSUE THREAD

**Issue by mjr4077au** [coelckers/Raze#88]
Another one from Phredreeke.

![image](https://user-images.githubusercontent.com/48643140/93406517-2f164d00-f8d3-11ea-8f3b-8362c86ebfac.png)

**Comment by coelckers** [comment]
@sinisterseed Did you

**Comment by coelckers** [comment]
See #87

**Comment by sinisterseed** [comment]
> @sinisterseed Did you

I do ;) .

**Comment by coelckers** [comment]
Sorry, that message was supposed to be deleted.
