### ISSUE TITLE
Clear usage rights of Exhumed's Mummy Staff widescreen sprites.

### ISSUE THREAD

**Issue by coelckers** [coelckers/Raze#89]
We need MaxED's ok for this but have no means to contact him, so any help would be appreciated.

**Comment by mjr4077au** [comment]
MaxED has kindly come onto the forum and confirmed the inclusion is OK 😁. https://forum.zdoom.org/viewtopic.php?f=347&t=69875&p=1168140#p1168083

**Comment by coelckers** [comment]
I've seen it - the assets will be merged in ASAP.
