### ISSUE TITLE
Weapon Switch not recognizing MouseWheelUp/MouseWheelDown

### ISSUE THREAD

**Issue by nephitejnf** [coelckers/Raze#9]
Every game I've tried to use the mouse wheel to switch weapons hasn't worked. The number hotkeys still work and when I set the weapon switch to the mousewheel bindings it reads them, but when I try to use it in game nothing happens. The keyboard binding set to apostrophe still works though.

**Comment by coelckers** [comment]
Please use the forum at zdoom.org ( https://forum.zdoom.org/viewforum.php?f=340 ) for reporting bugs. An open ticket for this one already exists here: https://forum.zdoom.org/viewtopic.php?f=340&t=67232
