### ISSUE TITLE
Blood - Guns Akimbo - Tommygun 

### ISSUE THREAD

**Issue by Axldomi** [coelckers/Raze#90]
In Blood when using the guns akimbo powerup, the tommyguns are using the firing sprites when non-firing. See screenshot attached.

![Blood_0005](https://user-images.githubusercontent.com/71838912/94169066-9c574e80-fe8e-11ea-81bd-97b50eb93838.png)

**Comment by Phredreeke** [comment]
this is the case in the original game as well - only that the game applies the grayscale palette to them.

**Comment by coelckers** [comment]
I cannot check right now, what are the other ports doing here?

**Comment by Axldomi** [comment]
FYI : the other ports (NBlood and BloodGDX) display it correctly.

**Comment by coelckers** [comment]
fixed
