### ISSUE TITLE
[Duke]: Pistol appears to be missing an animation frame as compared to EDuke32.

### ISSUE THREAD

**Issue by mjr4077au** [coelckers/Raze#93]
Thanks to the report by Vinícius M from Discord.

**Comment by coelckers** [comment]
The code was a bit messed up, because after copying in both the versions for WW2GI and Duke I forgot to actually merge them. I committed a fix for that but cannot test right now, so if someone could check it out I'd appreciate it.

**Comment by mjr4077au** [comment]
It seems fine to me now but have done some videos at 5Hz for comparison.

DN3D Raze 0.7.1-1 5Hz Pistol Reload: https://youtu.be/nRQ5jLuyrLk
DN3D EDuke32 r9257 5Hz Pistol Reload: https://youtu.be/sSdHhzV8qpY

**Comment by sinisterseed** [comment]
Yep, comparing the fix versus 0.7.1 and EDuke32 shows that it's correct now. It was indeed missing a frame, I never noticed this, huh.

So fixed.
