### ISSUE TITLE
[Duke 3d] The moment after gamesave there are weird inputs briefly

### ISSUE THREAD

**Issue by Doruk-Aksoy** [coelckers/Raze#97]
Sometimes after saving the game the player character does inputs on its own, like jumping or firing a single round. This wasn't happening before. Unfortunately I forgot the version I last played on.

**Comment by sinisterseed** [comment]
Fieing rounds sounds awfully similar to #95, but jumping would be a new one for me.

**Comment by coelckers** [comment]
What precisely did you do? I tried to reproduce #95 but the only way was to spam the Escape key while holding the left mouse button for firing so eventually I just hit the right moment where the menu opened right after the pistol firing animation started.

**Comment by mjr4077au** [comment]
On my end I've been able to replicate it by just spamming the Escape key, rapidly opening and closing the menu. It seems like random sync bits and/or input are coming through. Sometimes the gun fires, sometimes I jump, sometimes I move left slightly, etc.

**Comment by sinisterseed** [comment]
> What precisely did you do? I tried to reproduce #95 but the only way was to spam the Escape key while holding the left mouse button for firing so eventually I just hit the right moment where the menu opened right after the pistol firing animation started.

Nothing more than I said there, after you open the menu you shouldn't hold fire anymore.

I think closing it calls the wrong events, which is why it leads to input randomness.

**Comment by coelckers** [comment]
More info here:

https://forum.zdoom.org/viewtopic.php?f=340&t=70175&p=1168667#p1168667

**Comment by mjr4077au** [comment]
Captured some video of this: https://youtu.be/mvhSr36V_O0

Issue appears to only happen after some kind of movement, but eventually stops. As can be seen at the start, I didn't have the issue so I proceded to move around a bit and was able to trigger it until it effectively stopped by the end of the clip.

**Comment by duke912** [comment]
> Captured some video of this: https://youtu.be/mvhSr36V_O0
> 
> Issue appears to only happen after some kind of movement, but eventually stops. As can be seen at the start, I didn't have the issue so I proceded to move around a bit and was able to trigger it until it effectively stopped by the end of the clip.

Happens to me very often, not only in Duke, but all supported games in Raze. It seens to be easily triggered when you quicksave/load after shooting, jumping, etc.

**Comment by mjr4077au** [comment]
> Captured some video of this: https://youtu.be/mvhSr36V_O0
> 
> Issue appears to only happen after some kind of movement, but eventually stops. As can be seen at the start, I didn't have the issue so I proceded to move around a bit and was able to trigger it until it effectively stopped by the end of the clip.

@coelckers not sure if you ever had a chance to view the above video, but any thoughts on this peculiar issue and where one might look for a fix? Happy to take point on it otherwise, but I'm not sure where the issue lies (assuming in `G_Buildticcmd()` or something).

**Comment by coelckers** [comment]
I had the same happen in SW yesterday, sadly no way to reproduce and investigate it.

**Comment by mjr4077au** [comment]
I can reproduce it fairly easily by running around for ~5-10 seconds, then rapidly opening and closing the menu as per the video. Not sure if you get the same experience on your end doing something similar?
