### ISSUE TITLE
[Duke] Vertical auto-aim issues when not looking with the mouse.

### ISSUE THREAD

**Issue by mjr4077au** [coelckers/Raze#98]
Raising this from Discord as I might not get a chance to look at it before someone else can.

Auto-aim is working for all weapons if you're aiming in close proximity to an enemy, but verticality is only working for the pistol and RPG according to an end user. I haven't fully tested this and probably won't be able to for another 24 hours or so.

Hopefully these hyperlinks work here as some kind of permalink:

Raze:
https://cdn.discordapp.com/attachments/674163641934807050/760525898066690098/2020-09-29_11-33-40-1.mp4
https://cdn.discordapp.com/attachments/674163641934807050/760526011522875492/2020-09-29_11-36-19-1.mp4

EDuke32:
https://cdn.discordapp.com/attachments/674163641934807050/760528971036753940/2020-09-29_11-49-14-1.mp4

**Comment by sinisterseed** [comment]
Most peculiar, I can mostly confirm this is true.

It works fine for non-hitscan weapons, but for hitscan weapons autoaim doesn't take effect on the Shotgun and Chaingun, only the Pistol. Projectile-based weapons seem fine otherwise.

**Comment by mjr4077au** [comment]
This has effectively been broken since the rebase. Works before f307b2a954f1fda2c97fd14e2c865cb6567e3735 but not after. However I'm surprised that's the case. Even though the old interfaces have been removed, were they taking precidence over the newer code?

**Comment by coelckers** [comment]
It's because you did not use the replacement code with older versions. Add the -duke_old command line parameter to continue testing with older revisions, otherwise you play with RedNukem's code.

**Comment by mjr4077au** [comment]
Thanks and yup, just worked that out from e9925eee0fb835d0a7a8d3218b15d710dd02324b around the time you commented :)

**Comment by mjr4077au** [comment]
It broke as of 990cb2acb8341b07335d1c33fee4e822ba56c3d4, which unfortunately is a rather large commit. Assuming this code came straight from JFDuke3D, it should just work as JFDuke3D works fine.
