### ISSUE TITLE
[RR:RA] Palette emulation makes some maps turn... black

### ISSUE THREAD

**Issue by sinisterseed** [coelckers/Raze#99]
![Redneck_0000](https://user-images.githubusercontent.com/57503728/94678911-eb3a3380-0327-11eb-835b-a86c015219a0.png)

Most curious.

**Comment by coelckers** [comment]
Oh, that foggy map again?

**Comment by sinisterseed** [comment]
Yep, Sunny Shores ain't so sunny anymore 😉 .
